### ISSUE TITLE
Pago para quem desenvolver layout c/ 3 boletos por pagina

### ISSUE THREAD

**Issue by Transis-Felipe** [BoletoNet/boletonet#1001]
Se alguém tiver interesse em desenvolver layout do boleto com 3 boletos por página, fale comigo para acertarmos o valor.

![LayoutBoleto](https://github.com/user-attachments/assets/fbd6576a-f236-44a6-8d10-20ed109e9bd3)

**Comment by ivanteles** [comment]
A biblioteca ja tem uma propriedade carnê, basta setar como true que ele gera dessa forma que vc precisa

**Comment by Transis-Felipe** [comment]
Opa, vou testar, obrigado
