### ISSUE TITLE
Carteiras Implementadas

### ISSUE THREAD

**Issue by ivanteles** [BoletoNet/boletonet#103]
Boa tarde pessoal, seria interessante ter uma página listando todos os bancos e carteiras que estão implementadas implementadas, inclusive se arquivos de retornos e remessas estão também implementados.

**Comment by carloscds** [comment]
@ivanteles Ja existe uma pagina no Wiki para isto. Precisa apenas atualizar: https://github.com/BoletoNet/boletonet/wiki

**Comment by ivanteles** [comment]
@carloscds , na verdade me expressei mal, eu queria dizer era que a documentação atual deveria ser atualizada para agilizar o uso.

**Comment by carloscds** [comment]
@ivanteles Existe um projeto com exemplos, aqui mesmo no Git.

**Comment by ivanteles** [comment]
@carloscds, eu sei que tem, já tenho experiência com o projeto, é que precisei usar o BB e ao tentar gerar o arquivo remessa da um erro. Então ter um exemplo disso facilitaria.

**Comment by carloscds** [comment]
@ivanteles O erro deve estar relacionado a algum campo não preenchido ou incorreto.Tentou usar o método Valida() para analisar os registros ?
