### ISSUE TITLE
Boleto.Net e VFP

### ISSUE THREAD

**Issue by rafd75** [BoletoNet/boletonet#107]
Boa noite!

Sou usuário antigo do CobreBemX, mas como muitos aqui, pulei do barco de lá, e estou integrando nossa solução com o Boleto.Net. Espero em breve eliminar o CobreBemX de nosso sistema, e poder contribuir com o desenvolvimento desta ferramenta quando necessário.

Estou usando a Boleto.Net com o Visual FoxPro (VFP). Para tornar essa integração possível, eu devo copiar a Boleto.Net.Dll para a pasta de instalação do VFP (No caso C:\Program Files (x86)\Microsoft Visual FoxPro 9\).

Então consigo instanciar a classe, criar boletos, gerar HTML... Tudo ok! Mas ao tentar gerar o PDF, recebo este erro:

**O acesso ao caminho 'C:\Program Files (x86)\Microsoft Visual FoxPro 9\wkhtmltopdf.exe' foi negado**

Existe alguma propriedade que eu possa configurar o local onde está localizado o "wkhtmltopdf.exe" ?

Obs: Quando eu faço os testes unitários (dentro do Visual Studio), o problema não ocorre.

Abs!

**Comment by rafd75** [comment]
Opa... parece que já descobri.

Executei o VFP "como administrador" e deu certo!

---- Vou para a fase 2: remessa e retorno!

**Comment by adjanilha** [comment]
Boa tarde.
Vc tem como disponibilizar um exemplo do BoletoNet funcionando no VFP9?

**Comment by rafd75** [comment]
@adjanilha --- atualmente não uso a versão do BoletoNet original. Acabei criando uma outra versão, eliminei alguns bancos, dei uma limpada no código.

Mas quando eu mandei essa mensagem, eu precisei criar um outro projeto (chamei de ProxyBoletoNet) que instanciava a DLL do BoletoNet (essa do projeto) e fazia o meio de campo entre o VFP e a DLL (deste projeto).

Tive que fazer isso pois o VFP não tem tipos compostos que o C# tem... então, eu recebia um INT (no proxy) e convertia para outro tipo (do C#)...

Desculpe a pressa... estou muito enrolado aqui... Será que consegui te ajudar em algo ?

**Comment by adjanilha** [comment]
Ajudou sim, amigo.
Só uma dúvida, esse projeto ProxyBoletoNet, vc fez em qual linguagem? C# mesmo?

**Comment by rafd75** [comment]
Sim... C#.

Por exemplo, para criar todo o setup da cobrança, eu criei uma função assim: (você vai precisar ajustar para o BoletoNet, pois as propriedades podem estar com nome trocado)..

no VFP, eu instancio o "Proxy", e faço algo assim:

oBoletoNetProxy.SetupCobranca(...passo parametros aqui) --- veja o código abaixo


        public bool SetupCobranca(string cnpj, string razaoSocial,
                                    string enderecoLogradouro, string enderecoNumero, string enderecoComplemento, string enderecoBairro, string enderecoCidade, string enderecoEstado, string enderecoCep,
                                    int numeroBanco, string agencia, string digitoAgencia, string operacaoConta, string conta, string digitoConta,
                                    string codigoCedente, string carteira, string variacaoCarteira,
                                    int tipoCarteira, int tipoFormaCadastramento, int tipoImpressaoBoleto,
                                    ref string mensagemErro)
        {
            mensagemErro = "";
            try
            {
                if (string.IsNullOrWhiteSpace(cnpj))
                {
                    mensagemErro += "Cnpj não informado." + Environment.NewLine;
                }
                if (string.IsNullOrWhiteSpace(razaoSocial))
                {
                    mensagemErro += "Razão Social não informada." + Environment.NewLine;
                }
                if (numeroBanco == 0)
                {
                    mensagemErro += "Banco não informado." + Environment.NewLine;
                }
                if (string.IsNullOrWhiteSpace(agencia))
                {
                    mensagemErro += "Agência não informada." + Environment.NewLine;
                }
                if (string.IsNullOrWhiteSpace(digitoAgencia))
                {
                    mensagemErro += "Dígito da agência não informado." + Environment.NewLine;
                }
                if (string.IsNullOrWhiteSpace(conta))
                {
                    mensagemErro += "Conta não informada." + Environment.NewLine;
                }
                if (string.IsNullOrWhiteSpace(digitoConta))
                {
                    mensagemErro += "Dígito da conta não informado." + Environment.NewLine;
                }
                if (string.IsNullOrWhiteSpace(carteira))
                {
                    mensagemErro += "Carteira não informada." + Environment.NewLine;
                }
                if (!string.IsNullOrWhiteSpace(mensagemErro))
                {
                    return false;
                }
                if (tipoCarteira < 1 || tipoCarteira > 5)
                {
                    mensagemErro += "Tipo da Carteira inválida: 1-Simples, 2-Vinculada, 3-Caucionada, 4-Descontada, 5-Vendor" + Environment.NewLine;
                }
                if (tipoFormaCadastramento < 1 || tipoFormaCadastramento > 2)
                {
                    mensagemErro += "Tipo da Forma de Cadastramento inválida: 1-Com Registro, 2-Sem Registro" + Environment.NewLine;
                }
                if (tipoImpressaoBoleto < 1 || tipoImpressaoBoleto > 2)
                {
                    mensagemErro += "Tipo da Impressão do Boleto inválida: 1-Banco, 2-Empresa" + Environment.NewLine;
                }

                // Cria Conta Bancaria
                boletos.ContaBancaria = new ContaBancaria(agencia, digitoAgencia, operacaoConta, conta, digitoConta, carteira, variacaoCarteira, (TipoCarteira)tipoCarteira, (TipoFormaCadastramento)tipoFormaCadastramento, (TipoImpressaoBoleto)tipoImpressaoBoleto);
                // Cria Cedente
                boletos.Cedente = new Cedente
                {
                    CPFCNPJ = cnpj,
                    Nome = razaoSocial,
                    ContaBancaria = boletos.ContaBancaria,
                    Codigo = codigoCedente,
                    Endereco = new Endereco(enderecoLogradouro, enderecoNumero, enderecoComplemento, enderecoBairro, enderecoCidade, enderecoEstado, enderecoCep)
                };
                // Cria Banco
                boletos.Banco = new Banco(numeroBanco);
                boletos.Banco.Cedente = boletos.Cedente;
                boletos.Banco.FormataCedente();
                setupOk = true;
            }
            catch (Exception ex)
            {
                while (ex != null)
                {
                    mensagemErro += ex.Message + Environment.NewLine;
                    ex = ex.InnerException;
                }
                return false;
            }
            return true;
        }

**Comment by adjanilha** [comment]
Show de bola, amigão!
Ajudou muito!
Vlw mesmo!
