### ISSUE TITLE
AppVeyor não roda build a mais de 1 mês.

### ISSUE THREAD

**Issue by AlbertoMonteiro** [BoletoNet/boletonet#11]
Esse comportamento está correto?

**Comment by carloscds** [comment]
@AlbertoMonteiro Não está normal, vou verificar.

**Comment by carloscds** [comment]
@AlbertoMonteiro Consertado. Obrigado!

**Comment by AlbertoMonteiro** [comment]
@carloscds prazer foi meu :+1: 
Qual era o problema?

**Comment by carloscds** [comment]
@AlbertoMonteiro disparador no git tava com webhook incorreto.
