### ISSUE TITLE
Ler Arquivo de Retorno

### ISSUE THREAD

**Issue by phelipecalazans** [BoletoNet/boletonet#117]
Ola galera, estou com dificuldade em ler o arquivo de retorno gerado pelo BB.

Alguem poderia colocar algum exemplo ou coisa do tipo.

Grato,
Phelipe

**Comment by carloscds** [comment]
@phelipecalazans Qual a sua dúvida ?

**Comment by phelipecalazans** [comment]
Então @carloscds tentei das formas abaixo: 

                Stream fs = new FileStream(@"C:\Users\phelipecalazans\Desktop\CBR7241941201201615001.ret", FileMode.Open);
                ArquivoRetorno arq = new ArquivoRetorno(TipoArquivo.CNAB240);
                arq.LerArquivoRetorno(new Banco(001), fs);


                ArquivoRetornoCNAB240 cnab240 = new ArquivoRetornoCNAB240(@"C:\Users\phelipecalazans\Desktop\CBR7241941201201615001.ret");
                ArquivoRetornoCNAB240 cnab240 = new ArquivoRetornoCNAB240();




                cnab240.LerArquivoRetorno(new Banco(001), new Stream());
                var t = cnab240.ListaDetalhes;

e em todas as tentativas o LISTADETALHES está null. 

Ta correto essa sequencia de chamadas, tem algo diferente. Pois nunca tratei o arquivo de retorno.

**Comment by carloscds** [comment]
@phelipecalazans  Faça assim: 

`````CSharp
titulosRetorno = new List<DetalheRetorno>(); // conterá os títulos lidos

void LerArquivoBanco()
{
        Stream fs = new FileStream(@"C:\Users\phelipecalazans\Desktop\CBR7241941201201615001.ret", FileMode.Open);
        ArquivoRetorno arq = new ArquivoRetorno(TipoArquivo.CNAB240);
        arq.LinhaDeArquivoLida += retorno_LinhaDeArquivoLida;   
        arq.LerArquivoRetorno(new Banco(001), fs);
} 

 void retorno_LinhaDeArquivoLida(object sender, LinhaDeArquivoLidaArgs e)
        {
             var tituloLido = (BoletoNet.DetalheRetorno)e.Detalhe;
            // tratamentos aqui
            titulosRetorno.Add(titulo);
        }
``````

**Comment by phelipecalazans** [comment]
@carloscds, Agora funcionou.... em partes !! 

o e.Detalhe está vindo Null, mais o e.Linha está preenchido, por exemplo:
37 27559540000000000                                           00000000 1201  3475 LQR                1,00                         7,00            6,00*        

É isso mesmo ?

**Comment by carloscds** [comment]
@phelipecalazans Veja se o arquivo de retorno é realmente CNAB 240.

**Comment by phelipecalazans** [comment]
Galera continuo com o problema com o arquivo de retorno. 

void retorno_LinhaDeArquivoLida(object sender, LinhaDeArquivoLidaArgs e)
        {
             var tituloLido = (BoletoNet.DetalheRetorno)e.Detalhe;
            // tratamentos aqui
            titulosRetorno.Add(titulo);
        }

no codigo acima o e.detalhe sempre vem null, e segundo o suporte do BB o retorno já está no padrao cnab 240.

**Comment by carloscds** [comment]
@phelipecalazans Seu arquivo de retorno está um tanto estranho. O arquivo do BB não tem espaços ou virgulas. Cola um trecho do arquivo aqui.

**Comment by phelipecalazans** [comment]
@carloscds o trecho do arquivo 

> 00100000         2734719890001950027559510014       0330730000004223268 SEST SERVICO SOCIAL DO TRANSPOBANCO DO BRASIL                         22803201602315100025403000000416381634PROCESSAMEN                                                 
00100011T0100020 20734719890001950027559510014       0330730000004223268 SEST SERVICO SOCIAL DO TRANSPO                                                                                000000002803201600000000  000000000                      
0010001300001T 020330730000004223268 27559510000000067   70              29032016000000000122700001016020                         0900000000000010000000000000000000000000000000000000000   0000000000000000000000498A9        170192755951     
0010001300002U 020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002803201600000000            000000000000000                              000                           
00100015         000004000001000000000001227000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                                              
00199999         000001000006000000                                                                                                                                                            00000000000000000000000000000                    

> 

so que agora ele ta dando banco não implementado.

**Comment by carloscds** [comment]
@phelipecalazans Este arquivo está fora do padrão 240, está com linhas irregulares.
