### ISSUE TITLE
Carteira 18 Banco do Brasil

### ISSUE THREAD

**Issue by AlbertoMonteiro** [BoletoNet/boletonet#12]
Caros, tem alguém usando a carteira 18 do Banco do Brasil?

Eu usava o CobreBemX para emissão dos boletos, porém o mesmo se tornou inviável.
A geração da código de barra pelo cobrebemx, que está funcionando, é diferente da geração do Boleto.NET

Código gerado pelo CobreBemX:
00190.00009 **01220.950008 00009.125188 7** 60370000011250

Código gerado pelo Boleto.NET:
00190.00009 **50158.334743 00203.289186 2** 60370000011250

A parte em negrito, é a parte que diverge.
Analisando o código do CobreBem, ele montou da seguinte maneira
**01220.950008 00009.125188 7**
0 + "Código do cedente" + 00 + 8(DV)
0000 + NN(9125) + 18(CARTEIRA) + 8(DV)
7 DV Geral

Gostaria de saber se a geração do código no Boleto.NET está errado
Segue o código:

```csharp
boleto.CodigoBarra.Codigo = string.Format("{0}{1}{2}{3}{4}{5}{6}{7}",
    Utils.FormatCode(Codigo.ToString(), 3),
    boleto.Moeda,
    FatorVencimento(boleto),
    valorBoleto,
    boleto.NossoNumero,
    boleto.Cedente.ContaBancaria.Agencia,
    boleto.Cedente.ContaBancaria.Conta,
    boleto.Carteira);
```
Como podemos ver, a informação do cedente não é usada na geração do código de barra.

**Comment by carloscds** [comment]
@AlbertoMonteiro Você validou isto no manual do banco, no código do boletonet ele usa o convenio somente na certeira 16.

**Comment by AlbertoMonteiro** [comment]
@carloscds Validei, e essa semana subo a correção

**Comment by carloscds** [comment]
@AlbertoMonteiro Excelente!

**Comment by stivencamara** [comment]
@AlbertoMonteiro  Se você puder criar testes unitário para a carteira 16, seria perfeito.

**Comment by AlbertoMonteiro** [comment]
@stivencamara Posso fazer isso em outro pull request. Mas posso demorar, pois terei que estudar a logica dessa carteira 16
