### ISSUE TITLE
Exibir CNPJ do cedente com máscara

### ISSUE THREAD

**Issue by rodolfoghi** [BoletoNet/boletonet#123]
Quando utilizamos `MostrarCNPJnoBoleto = true` no cedente, seria interessante que o CNPJ fosse exibido com máscara no PDF do boleto. Pretendo alterar isso, mas imagino que alguém já tenha percebido e talvez já esteja desenvolvendo.

**Comment by carloscds** [comment]
@rodolfoghi Pode fazer e submeter o PR.
