### ISSUE TITLE
Remessa BB

### ISSUE THREAD

**Issue by phelipecalazans** [BoletoNet/boletonet#127]
Galera estou tentando gerar o arquivo de remessa para o BB modelo CNAB240 

mais quando vou executar esse metodo:
arquivoRemessa.GerarArquivoRemessa("2755954", new Banco(001), cedente, boleto, file, 01212101);

ele da uma exception: Referência de objeto não definida para uma instância de um objeto. Erro durante a geração do HEADER DE ARQUIVO do arquivo de REMESSA.

Alguém sabe o que pode ser ?

**Comment by GabrielSchimidtMylla** [comment]
@phelipecalazans estou com o mesmo problema, você conseguiu corrigir?

**Comment by GabrielSchimidtMylla** [comment]
@phelipecalazans consegui resolver o problema, veja se no objeto cedente vc esta passando a carteira e o convenio pois os dois são necessários para geração do header.

Espero ter ajudado.
