### ISSUE TITLE
Boleto em Windows Forms

### ISSUE THREAD

**Issue by nebrio** [BoletoNet/boletonet#135]
Pessoal, é possível gerar boletos usando Windows Forms? Ou apenas Web Forms?

Obrigado!

**Comment by carloscds** [comment]
@nebrio Você pode usar nos dois.

**Comment by nebrio** [comment]
E q estou tentando em windows forms e da problema pois a classe boletonet faz referencia a web.forms.... O q estou fazendo poderia me ajudar?
Obrigado

**Comment by carloscds** [comment]
@nebrio Adicione o assembly System.Web

**Comment by nebrio** [comment]
Valeu Carlos, muito obrigado, funcionou!
