### ISSUE TITLE
Multa em R$ ao invés de %

### ISSUE THREAD

**Issue by rodolfoghi** [BoletoNet/boletonet#147]
Boa tarde!
Existe alguma forma de imprimir a multa em R$ ao invés de em %?
Pelo que vi o BoletoNet só trabalha com multas em %, conforme código abaixo. É isso mesmo?
`case EnumInstrucoes_BancoBrasil.Percentual_Multa:
                        this.Codigo = (int)EnumInstrucoes_BancoBrasil.Percentual_Multa;
                        this.Descricao = "Após vencimento cobrar multa de " + valor + " %";
                        break;`

**Comment by carloscds** [comment]
@rodolfoghi Você poderia implementar isto ? Uma opção para multas em reais ?

**Comment by rodolfoghi** [comment]
Sim, estou implementando, em breve farei commit e enviarei o pull request.

Atenciosamente,
Rodolfo Ghiggi


On Thu, Feb 25, 2016 at 8:13 AM, Carlos dos Santos <notifications@github.com
