### ISSUE TITLE
Protesto em dias corridos - Banco do Brasil

### ISSUE THREAD

**Issue by rodolfoghi** [BoletoNet/boletonet#159]
Olá,
No manual do BB a nota 09 indica a utilização do código '06' conforme abaixo:

> 06 - Indica Protesto em dias corridos, com prazo de 6 a 29, 35 ou 40 dias Corridos.
- Obrigatório impostar, nas posições 392 a 393 o prazo de protesto desejado: 6 a
29, 35 ou 40 dias.

Porém o EnumInstrucoes_BancoBrasil utiliza os códigos 9 (Protestar), 81 (ProtestarAposNDiasCorridos) e 82 (ProtestarAposNDiasUteis) e na geração do arquivo de remessa as posições 392 e 393 sempre ficam em branco, conforme trecho de código abaixo:
`reg.CamposEDI.Add(new TCampoRegistroEDI(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0392, 002, 0, string.Empty, ' '));                              //392-393`

Ninguém usa essa instrução 06? Pensei em criar um enum para essa opção, mas vai ficar estranho e conflitante com os códigos existentes.

**Comment by carloscds** [comment]
@rodolfoghi Pode criar.
