### ISSUE TITLE
Boleto.net em WPF

### ISSUE THREAD

**Issue by vikazuo** [BoletoNet/boletonet#160]
É possível gerar boletos através de aplicações WPF?

**Comment by carloscds** [comment]
@vikazuo Sim, é possível.

**Comment by vikazuo** [comment]
Certo, mas para ele aparecer na tela? eu coloco em qual componente? StackPanel?

**Comment by carloscds** [comment]
@vikazuo Ele retorna um HTML ou PDF, então você precisará usar um controle que consiga exibir um dest tipos.

**Comment by renanmthy** [comment]
@vikazuo Conseguiu resolver este problema? Se sim, por favor, alguém finalize a Issue.
