### ISSUE TITLE
Itaú: Adição da Carteira 112

### ISSUE THREAD

**Issue by MarcielTorres** [BoletoNet/boletonet#168]
Prezados,

Acabei de implementar a adição da carteira 112 para o Banco Itaú. Nesse exato momento a equipe de homologação do Itaú está validando os boletos gerados utilizando essa carteira.

Gostaria de compartilhar com vocês essa alteração, faço um Pull Request apenas?

**Comment by carloscds** [comment]
@MarcielTorres Pode fazer um PR.

**Comment by MarcielTorres** [comment]
Beleza, vou aguardar a homologação do banco e depois faço um PR. Valeu

**Comment by MarcielTorres** [comment]
Acabei de criar o PR.

Segundo a própria documentação do banco a impressão e entrega é feita pelo próprio banco nessa carteira.
