### ISSUE TITLE
Sem informações do pagador no site do Itaú

### ISSUE THREAD

**Issue by Saccomani** [BoletoNet/boletonet#183]
Ola pessoal, implementei o boletos.net na minha aplicação mas nao consigo ver quem pagou no site do Itaú..os campos pagador, data vencimento, seu numero vem tudo em banco...

Engraçado qur no boleto constam estas informações! 

Alguem sabe oque pode ser isso!?

**Comment by ivanteles** [comment]
No tratamento do arquivo retorno você tem o número do seu débito, com essa informação você consegue ver quem pagou o débito.

**Comment by Saccomani** [comment]
Ah..entao obrigatóriamente necessito do arquivo de retorno?! 

Achei q dava pra ver direto no site do itau...vou dar uma pesquisada melhor

**Comment by ivanteles** [comment]
É mais fácil, pois através do arquivo é feito a baixa automática.

**Comment by Saccomani** [comment]
Perfeito..ja achei o arquivo de retorno no site do itau...este aplicativo boletos.net processa o arquivo de retorno?

**Comment by ivanteles** [comment]
Sim. Mas tem que codificar o tratamento do arquivo.
