### ISSUE TITLE
Tem alguma forma de colocar uma logo no boleto?

### ISSUE THREAD

**Issue by AlbertoMonteiro** [BoletoNet/boletonet#19]
Tem alguma forma de colocar uma logo no boleto?

**Comment by carloscds** [comment]
@AlbertoMonteiro Tem sim, Você pode passar o logo no método MontaHtml()

**Comment by AlbertoMonteiro** [comment]
@carloscds O método que estou usando é o ```MontaHtmlEmbedded```, nele não tem isso, vou fazer um PR depois.
