### ISSUE TITLE
Remessa BB CNAB240

### ISSUE THREAD

**Issue by phelipecalazans** [BoletoNet/boletonet#202]
Galera, 
Alguem já validou o arquivo de remessa gerado pela biblioteca no BB ?

Estou tendo retorno do banco com algumas inconsistencia.

**Comment by ivanteles** [comment]
Eu sim, usando carteira 17-019, convênio de 7 posições!

Atenciosamente.
*Ivan Teles* (Analista de Sistemas/Desenvolvimento)
*Microsoft Certified Professional*
(61) 3710-2676 (Fixo) / (61) 8406-9719 (Tim) / (61) 9345-8963 (Claro)
Gtalk/Email: ivan@idevweb.com.br
Skype: idev.web

www.idevweb.com.br (Microsoft Partner)

Esta mensagem, incluindo seus anexos, tem caráter confidencial e seu
conteúdo é restrito aos seus destinatários.

Qualquer acesso, replicação ou disseminação desta mensagem ou parte dela,
sem autorização prévia do remetente ou do destinatário, é expressamente
proibida e configura ofensa ao inciso XII do Artigo 5º da Constituição
Federal. A iDev Web se responsabiliza apenas por documentos que contenham a
assinatura de um dos seus diretores. Os demais documentos têm fim
exclusivamente informativo.


2016-05-06 15:41 GMT-03:00 phelipecalazans <notifications@github.com>:

**Comment by phelipecalazans** [comment]
Poise @ivanteles estou usando carteira 17, mandei mais um arquivo para validação.. Assim que eu tiver uma resposta mando aqui para analisarmos.

**Comment by phelipecalazans** [comment]
Então galera tiver esse retorno do Banco do Brasil.

Alguém já passou por isso ? @ivanteles ou @carloscds 

Estrutura do Arquivo
----------------------------------------------------------------------------------------------------
Linha 0005, Lote 0001, Trailer de Lote: Quantidade de Registros com erro. informado '000003'. Correto '000004'
Linha 0006, Trailer de Arquivo: Quantidade de registros com erro. informado '000005'. Correto '000006'
Header de Arquivo > Lote 0000
----------------------------------------------------------------------------------------------------
Posições 033 a 052: Preencher com o código do convênio: '002755951001417019 '
====================================================================================================
Header de Lote > Lote 0001
----------------------------------------------------------------------------------------------------
Posições 034 a 053: Preencher com o código do convênio: '002755951001417019 '
====================================================================================================
Segmento P > Lote 0001
----------------------------------------------------------------------------------------------------
Posições 058 a 058: Quando a carteira for 17, preencher com '1' ou '7' para registro na modalidade simples, '2' Vinculada, '3' Caucionada ou '4' Descontada ou '5' Vendor
