### ISSUE TITLE
[Azure] Sem Imagens e Codigo de barras

### ISSUE THREAD

**Issue by jmmccota** [BoletoNet/boletonet#210]
Estou tentando gerar o boleto no azure, porem não aparece imagens dos bancos ou codigo de barras, como resolver?
![boleto](https://cloud.githubusercontent.com/assets/10466167/15249651/1438c92e-18f7-11e6-956b-1ae30ce42133.png)

**Comment by carloscds** [comment]
@jmmccota Alguém ja resolveu este problema com Azure aqui, dá uma olhada nas Issues fechadas!

**Comment by jmmccota** [comment]
@carloscds sabe me informar qual é essa issue?

**Comment by carloscds** [comment]
@jmmccota Infelizmente não

**Comment by jmmccota** [comment]
@carloscds Muito obrigado, eu pesquisei nos que estão abertos e fechados e não achei nada referente a imagens.

**Comment by FurstLevy** [comment]
Bom dia.
Também estou com o mesmo problema. Estou usando MVC, porém sem azure.
Inclusive também já pesquisei e não encontrei ninguém resolvendo esse problema.

**Comment by FurstLevy** [comment]
Pessoal encontrei aqui, baixei a solution e identifiquei onde monta o HTML com o boleto.
Eu estava usando o return boletoBancario.MontaHtml();
dai mudei para return boletoBancario.MontaHtmlEmbedded(); e funcionou perfeitamente todas as imagens.
A diferença pelo que identifiquei é que ele monta as imagens de forma embutida na página.
Espero que te ajude @jmmccota

**Comment by jmmccota** [comment]
@FurstLevy Muito obrigado por sua solução. Realmente funcionou para mim.

**Comment by marclfv** [comment]
@FurstLevy  O código de barras hoje (08/05/2018) quando enviado para o Gmail não exibe o código de barras nem o logo do banco... 

Tentei realizar o envio Hotmail, Yahoo e para Servidor da Locaweb e todos mostram os dados em base64... somente o gmail testado continuar a não exibir as imagens...

tente utilizar a função boletoBancario.MontaHtmlEmbedded() como você passando as mais variadas combinações de parametros  boletoBancario.MontaHtmlEmbedded(boolean, boolean, boolean, boolean) e mesmo assim nada teve efeito... 

alguém resolveu esse problema de outra maneira ?

Por causa desse problema estou pensando em salvar todos os boletos em pdf para fazer o envio do mesmo em anexo ao e-mail.
Do método padrão não esta funcionando.

Alguém consegue dar uma luz ?

**Comment by jmmccota** [comment]
@marclfv Creio ser uma questão do gmail. 
Fazendo uma busca rapida na internet pode-se perceber que o gmail filtra as imagens base64:

[Filtro Gmail 1](https://stackoverflow.com/questions/41946783/gmail-blocking-small-embedded-inline-images-in-email-template)
[Filtro Gmail 2](https://productforums.google.com/forum/#!msg/gmail/TJ50pIxRVPQ/1Kr5-vHmfwMJ)
[Filtro Gmail 3](
https://stackoverflow.com/questions/3279523/base64-images-to-gmail/12786336#12786336)
[Filtro Gmail 3](https://productforums.google.com/forum/#!topic/gmail/tZ_yiS9FvqQ)

**Comment by diegorfalcao** [comment]
@FurstLevy representou... eu estava gerando apenas com MontaHtml() sem as imagens (ele busca a imagem "local") mas com o MontaHtmlEmbedded() ele retorna o boleto bonitinho com o código de barras inclusive...
