### ISSUE TITLE
boletonet arquivo zip

### ISSUE THREAD

**Issue by Westfallx** [BoletoNet/boletonet#212]
As outras versoes do boletonet eu consegui acidionar na minha Solution,
Agora quando eu incluo ele na minha solution ele não consegue fazer a verificação via nuget. tem como retirar essa verificação?

**Comment by ivanteles** [comment]
Isso resolve seu problema: http://stackoverflow.com/questions/27895504/how-do-i-enable-nuget-package-restore-in-visual-studio-2015

**Comment by Westfallx** [comment]
@ivanteles Valeu.. fucionou
