### ISSUE TITLE
Tratamento de arquivo remessa CNAB240 Sicoob

### ISSUE THREAD

**Issue by ivanteles** [BoletoNet/boletonet#213]
Alguém sabe dizer se já esta implementado e funcionamento o tratamento de arquivo de retorno do Sicoob CNAB240?

**Comment by carloscds** [comment]
@ivanteles Nós aqui implementamos a 400.

**Comment by ivanteles** [comment]
Blz. irei implementar o 240, e envio um request quando finalizar!

**Comment by carloscds** [comment]
@ivanteles Excelente Ivan!

**Comment by eternoscav** [comment]
Gostaria de gerar o arquivo de Remessa 240 para o Sicoob pela dll.
Alguém poderia me ajudar?

**Comment by ivanteles** [comment]
Olá @eternoscav ma época 2016 eu ia fazer e acabou que o cliente desistiu, mas agora já deve ta funcionando, vou usar esses dias!
Você já tentou? esta dando algum erro?

**Comment by eternoscav** [comment]
Verificarei o erro, qualquer coisa volto para comentar.
Obrigado.

**Comment by ivanteles** [comment]
@eternoscav cara, hoje fui ver a questão da remessa e realmente tem muito métodos não implementados.
Implementou algo ai? me add ai pra gente trocar uma ideia e implementar isso rápido ivan@idevweb.com.br

**Comment by eternoscav** [comment]
Boa noite !
Então estou até hoje tentando gerar o arquivo de remessa porém sem sucesso só consigo gerar o boleto.

Alguém conseguiu Gerar?

Obrigado.

**Comment by ivanteles** [comment]
Segue: https://github.com/BoletoNet/boletonet/issues/636#issuecomment-409033629
