### ISSUE TITLE
Boletos Validados

### ISSUE THREAD

**Issue by EltonRst** [BoletoNet/boletonet#216]
Pessoal, alguém tem algum código já validado para criar boletos para o banco `Sicredi ` ai
na mão ?
O sistema que desenvolvo possui, Caixa Econômica Federal, Banco do Brasil e Sicredi.
Com o Banco do Brasil e Caixa tudo OK.
Mas estou com dificuldades com o Sicredi.

@carloscds a gente podia abrir um lugar pro pessoal ir postando seus códigos já validados, estou encontrando bastante gente perdida por ai com dúvidas, não de como usar o Boleto.Net, mas sim
como ter certeza que está tudo validado certinho com seus códigos, talvez ajudasse em algo.. fica a
sugestão, se já houver um lugar ainda não é do meu conhecimento, eu sei que temos exemplos de 
como proceder para gerar, mas fui validar o Sicredi e deu zebra.

Desde já agradeço e aguardo retorno do pessoal ai, quem se sentir a vontade em ajudar só chamar.

**Comment by carloscds** [comment]
@EltonRst Existe o WIKI do projeto.

**Comment by Westfallx** [comment]
Cara vc pode usar o mesmo código para todos os bancos. mudando apenas como vc define o nosso número. e as instruções.
É o que eu faço aqui no meu sistema.

por exemplo essa parte do meu código é genérico independente do banco
"Cedente cedente = new Cedente(empresa.dsCnpj, empresa.dsRazao, banco.nragencia.ToString(), banco.dgagencia.ToString(),  banco.nrcedente.ToString(), banco.dgcedente.ToString(), banco.nroperacao.ToString());"
"Boleto boleto = new Boleto(DateTime.Today.AddDays(40), vlBoleto, banco.dscarteira, nsNumero.ToString("D5"), cedente);"
