### ISSUE TITLE
erro retorno banco Itaú campo carteira.

### ISSUE THREAD

**Issue by digsistemas** [BoletoNet/boletonet#226]
Pessoal, trabalhando no retorno do banco Itaú, identificamos que o código: 

detalhe.Carteira = registro.Substring(107, 1);

está buscando apenas um caracter e na posição errada, o correto seria buscar 3 dígitos na posição 83.

Como proceder para conferir e corrigir?

**Comment by carloscds** [comment]
Já corrigido via PR
