### ISSUE TITLE
Carteira 109 ITAU - Boleto Não homologado

### ISSUE THREAD

**Issue by Saccomani** [BoletoNet/boletonet#229]
O banco recusou o boleto por causa dos seguintes itens !

Esta versão nova já contempla estas mudanças? 

_Uso a versão 2.1.0.186_

>  O ENDEREÇO BENEFICIÁRIO (antigo CEDENTE) / SACADOR AVALISTA deve ser informado o endereço completo do BENEFICIÁRIO com o CNPJ. Se o título possuir a figura de Sacador Avalista o endereço informado deverá ser do Sacador Avalista, conforme Lei Federal 12.039 de 01/10/2009, conforme modelo do boleto pag.52, Layout Cobrança Itaú cnab 400 pos, ou pag.40, Layout Febraban 240 pos;

**Comment by rafaelsgripp** [comment]
@Saccomani, Boa Tarde, Estou com o mesmo problema, você conseguiu uma solução?

**Comment by Saccomani** [comment]
Cara, desisti deste componente...integrei meu sistema com o boletobancario.com melhor coisa q fiz..da uma olhada

**Comment by rafaelsgripp** [comment]
Obrigado pelo retorno @Saccomani, parece ser uma ótima solução, mas fica cara demais para a minha realidade.

Bom consegui resolver a situação, bastava atribuir a True para a propriedade **MostrarEnderecoCedente** da objeto da classe BoletoBancario.

Abraço!
