### ISSUE TITLE
Boleto BB carteira 11

### ISSUE THREAD

**Issue by marcusbarbosanet** [BoletoNet/boletonet#236]
Estou com bastante dificuldade para gerar o código de barras do BB, igual ao código de barras do boleto gerado direto no site do Banco do Brasil. Alguém pode ajudar?

**Comment by marcus2vinicius** [comment]
@marcusbarbosanet primeiramente vc precisa identificar qual região do código de barras está diferente. Feito isso basta adquirir a documentação do layout do boleto do BB e verificar a que se refere a parte que está diferente para que possa efetuar as alterações necessárias.

**Comment by marcusbarbosanet** [comment]
@marcus2vinicius obg
