### ISSUE TITLE
Gerar Boleto Sicredi

### ISSUE THREAD

**Issue by EltonRst** [BoletoNet/boletonet#238]
Pessoal, estou com um problema no meu boleto do Sicredi,
ao gerar ele não valida dos dados, algum cristo de alma boa na face
dessa WEB que já implantou o Sicredi e queira me disponibilizar o código
C# utilizado ?

**Comment by kelvindules** [comment]
Por que não explicar melhor e contribuir para que outros com o mesmo problema também resolvam?

**Comment by EltonRst** [comment]
@kelvindules ele não valida as carteiras, o sicredi só possui duas, e também não valida o código do cedente, eu não entendo essa parte de código do cedente, os dados de conta corrente e agência vão de boa e as instruções também.

**Comment by marcus2vinicius** [comment]
@EltonRst o seu cedente é igual ao número da conta para Unicred. Qual carteira vc esta usando?

**Comment by EltonRst** [comment]
@marcus2vinicius Eu uso a carteira "A", segue um exemplo do meu código.

```
namespace Sistema
{
// Dados para Cálculo do Número no Banco
    public class DadosCalculoNNB
    {
        public string Agencia { get; set; } // 4 dígitos
        public string Posto { get; set; } // 2 Dígitos
        public string Conta { get; set; } // Conta Corrente / Cedente
        public string Ano { get; set; } // Ano da Geração  DateTime.Now.ToString("yy");
        public string Byte { get; set; } // byte de Geração de 2 a 9
        public string Sequencial { get; set; } // Número Sequencial com 5 Dígitos
    }

public class Boletos
    {
        public ActionResult GerarBoleto()
        {
            byte[] boletoPDF = meuBoletoSicredi();
            return File(byte, "application/pdf", "Boleto.pdf");
        }

        public static byte[] meuBoletoSicredi()
        {

            BoletoBancario boletoBancario = new BoletoBancario();
            boletoBancario.CodigoBanco = 748;

            string agencia = "0123";
            string posto = "02";
            string conta = "12345";

            DadosCalculoNNB dadosCalculo = new DadosCalculoNNB()
            {
                Agencia = agencia,
                Posto = posto,
                Conta = conta,
                Ano = "16",
                Byte = "2",
                Sequencial = "00003"
            };

            Cedente cedente = new Cedente("000.000.000-00", "UMA PESSOA FÍSICA", agencia, conta);
            cedente.Codigo = agencia;

            string numeroNoBanco = CalculoNNB(dadosCalculo); // Calculamos o Número
            Boleto boleto = new Boleto(DateTime.Now.AddDays(30), 500.50m, "176", numeroNoBanco, cedente); // "176" carteira ?

            string documento = "0000012345"; // 000001 docuemto, 23 parcela, 45 filial
            boleto.NumeroDocumento = documento;

            boleto.LocalPagamento = "PAGÁVEL PREFERENCIALMENTE NAS COOPERATIVAS DE CRÉDITO DO SICREDI";
            //boleto.Carteira = "A"; // ou "C"; // A = Carteira Simples com Registro, C = Carteira Simples sem Registro
            boleto.Aceite = "N";

            boleto.Sacado = new Sacado("000.000.000-00", "OUTRA PESSOA FÍSICA");

            boleto.Sacado.Endereco.End = "RUA DE TESTE 12345";
            boleto.Sacado.Endereco.Bairro = "BAIRRO DE TESTE";
            boleto.Sacado.Endereco.Cidade = "CIDADE DE TESTE";
            boleto.Sacado.Endereco.CEP = "12345678";
            boleto.Sacado.Endereco.UF = "UF";

            // Informa o número do título no Boleto nas informações do sacado
            boleto.Sacado.InformacoesSacado.Add(new InfoSacado(string.Concat("Título: ", documento)));

            //Adiciona as instruções ao boleto
            Instrucao item = new Instrucao(748);
            item.Descricao = string.Concat("Teste 1", "<br/>", "Teste 2", "<br/>", "Teste 3");
            boleto.Instrucoes.Add(item);

            boleto.EspecieDocumento = new EspecieDocumento_Sicredi("A"); // DMI, Duplicata Mercantil por indicação

            boletoBancario.Boleto = boleto;
            boletoBancario.Boleto.Valida();

            return boletoBancario.MontaBytesPDF();

        }

        public static string CalculoNNB(DadosCalculoNNB dadosCalculo)
        {

            string dados = string.Concat(
                dadosCalculo.Agencia,
                dadosCalculo.Posto,
                dadosCalculo.Conta,
                dadosCalculo.Ano,
                dadosCalculo.Byte,
                dadosCalculo.Sequencial
            );

            // efetuamos o cálculo
            int soma = 0;
            for (int controle = 0; controle < dados.Length; controle++)
            {
                int n = int.Parse(dados.Substring(controle, 1));

                if (controle == 0 || controle == 8 || controle == 16)
                {
                    soma += n * 4;
                }
                else if (controle == 1 || controle == 9 || controle == 17)
                {
                    soma += n * 3;
                }
                else if (controle == 2 || controle == 10 || controle == 18)
                {
                    soma += n * 2;
                }
                else if (controle == 3 || controle == 11)
                {
                    soma += n * 9;
                }
                else if (controle == 4 || controle == 12)
                {
                    soma += n * 8;
                }
                else if (controle == 5 || controle == 13)
                {
                    soma += n * 7;
                }
                else if (controle == 6 || controle == 14)
                {
                    soma += n * 6;
                }
                else if (controle == 7 || controle == 15)
                {
                    soma += n * 5;
                }
            }

            // se for maqior que 9 será 0
            string digitoAutoConferencia = 11 - (soma % 11) > 9 ? "0" : (11 - (soma % 11)).ToString(); 

            return dados.Substring(11) + digitoAutoConferencia; // Número no Banco já Montado
        }
    }
}
```

**Comment by Westfallx** [comment]
@EltonRst  Tem certeza que a carteira é A , eu utilizo carteira 1 e 3  (1-regitro e 3 - sem registro)
A é a espécie.. da uma olhada no manual

**Comment by EltonRst** [comment]
Segundo o Manual está correto, muito obrigado @Westfallx , mas ainda persiste meu problema,
linha Digitavel difere dos dados do Boleto, e o código de Barras nem se fala..... gerei um boleto de 10 centavos, na linha digitavel saiu 1 centavo e no código de barras leu como 99.000.000.01,
muito louco.

**Comment by EltonRst** [comment]
Agencia=0123
Posto=02
Conta/Cedente=12345

Identifiquei o meu problema, bom, pra quem tiver com o mesmo problema, o Boleto.Net funciona da seguinte maneira: Ele já gera o número no banco pra você a partir dos dados informados, de conta/cedente, agencia e tal, na remessa tem uma frescura de Byte da geração que vai de 2 a 9 mas não achei isso no Boleto.Net, mas esse não era o problema, o problema se encontra ao informar a agência,
a agência do Sicredi é composta por 4 dígitos da agencia e 2 dígitos do posto ficando "012302", onde esses 2 dígitos do posto  servem para calcular o número no Banco segundo Manual do Sicredi, bom deixando a agencia com 6 dígitos passa tudo "OK" na validação, porém no boleto sai no Campo "Agencia / Codigo do Beneficiario" no seguinte formato: 012302..12345, e o valor do boleto sai totalmente bugado, e se eu se não preencher o Posto da agencia ele calcula tudo certinho porém ele fica no seguinte formato
no campo comentado acima: 0123..12345, já se eu colocar o posto no objeto do Cedente na propriedade ContaBancaria-->OperacaConta ele coloca no formato correto 0123.02.12345 co campo citado acima,
porém os valores ainda continuam sendo calculados errados, a solução que eu achei, foi  não preencher Esse Campo do posto, mantendo sómente a agencia com 4 dígitos, e outa o Byte de 2 a 9 não sei o que fazer, acredito que não vou ter problemas, já as carteiras 1 e 3 parecem ter dado certo no lugar de A e C, porém ainda preciso saber como operar com cobrança REGISTRADA e NÃO REGISTRADA... aonde configurar isso no código ?

**Comment by EltonRst** [comment]
Bom dia Pessoal, aos que acompanharam meu problema e aos que estão com o mesmo problema, fica aqui um exemplo bem detalhado de código de como emitir o boleto do `Sicredi`, agradeço a todos pela ajuda.

```
public ActionResult GerarBoleto()
        {
            byte[] boletoPDF = meuBoletoSicredi();
            return File(boletoPDF, "application/pdf", "Boleto.pdf");
        }

        public static byte[] meuBoletoSicredi()
        {
            // Nosso Boleto Bancário
            BoletoBancario boletoBancario = new BoletoBancario();
            boletoBancario.CodigoBanco = 748; // 748-X Sicredi

            // Dados do Portador e boleto
            string agencia = "0123"; // Agencia 4 dígitos
            string posto = "02"; // Posto da Agencia, 2 dígitos
            string conta = "12345"; // Código do cedente/ Conta Corrente, 5 dígitos
            string byteGeracao = "2"; // Byte de Geração do número no banco, de (2 a 9), 1 dígito
            string sequencial = "00003"; // Sequencial de Geração do número no banco, 5 dígitos.
            string documento = "0000010203"; // Número do Documento na Empresa, 10 dígitos
            string carteira = "1"; // "1" – Com Registro, "3" – Sem Registro, 1 dígito
            decimal valor = 0.10m; // Valor do Boleto

            // Cedente
            Cedente cedente = new Cedente("10.823.650/0001-90", "SAFIRALIFE", agencia, conta);
            cedente.Codigo = conta;
            cedente.MostrarCNPJnoBoleto = true;
            cedente.ContaBancaria.OperacaConta = posto;

            // Boleto
            DateTime dataDocumento = new DateTime(2016,08,10); // Data da Emissão do Documento
            DateTime vencimento = DateTime.Now.AddDays(10); // Vencimento
            string nossoNumero = string.Concat(byteGeracao, sequencial); // Nosso número Montado para cálculo

            // Vencimento,Valor,Carteira,Cedente
            Boleto boleto = new Boleto(vencimento, valor, carteira, nossoNumero, cedente);
            boleto.NumeroDocumento = documento;
            boleto.DataDocumento = dataDocumento;
            boleto.EspecieDocumento = new EspecieDocumento_Sicredi("A");

            // Sacado
            boleto.Sacado = new Sacado("000.000.000-00", "Nome do seu Cliente");
            boleto.Sacado.Endereco.End = "Endereço do seu Cliente ";
            boleto.Sacado.Endereco.Bairro = "Bairro";
            boleto.Sacado.Endereco.Cidade = "Cidade";
            boleto.Sacado.Endereco.CEP = "00000000";
            boleto.Sacado.Endereco.UF = "UF";

            // Exemplo de como adicionar mais informações ao sacado
            ulong doc = Convert.ToUInt64(documento);
            documento = documento.Length < 9 ? doc.ToString(@"000000\-00") : doc.ToString(@"000000\-00\/00");
            // Emcima fiz a formatação do documento.
            boleto.Sacado.InformacoesSacado.Add(new InfoSacado("TÍTULO: " + documento));

            // Instruções
            boleto.LocalPagamento = "PAGÁVEL PREFERENCIALMENTE NAS COOPERATIVAS DE CRÉDITO DO SICREDI";
            Instrucao_Sicredi item1 = new Instrucao_Sicredi(9, 5);
            boleto.Instrucoes.Add(item1);

            // Atribuição e Validação
            boletoBancario.Boleto = boleto;
            boletoBancario.Boleto.Valida();

            // Monto os bytes do pdf
            return boletoBancario.MontaBytesPDF();

        }
```

**Comment by Westfallx** [comment]
@EltonRst  
Eu faço o seguinte, 
Cedente c = new Cedente("CNPJ", "Nome Empresa", "agencia", "DG Ag", "Cedente", "DG Cedente", "Operacao");

do jeito que eu faço ele já identifica que o cedente é o número da conta

**Comment by EltonRst** [comment]
@Westfallx, o que você quer dizer é que no DG Ag vai o posto com 2 dígitos e no DG Cedente vai o dígito verificador da conta com 1 digito só ? não entendí a "Operação"....

**Comment by Westfallx** [comment]
Dg. Ag = digito da agencia,  Dc cedente = Digito do cedente.
Você não tem o manual de como montar a linha digitavel? ele pede o UF ou operação o que eu uso é o UF 46, ai vc tem que ver da agencia da qual vc está fazendo
Ele identifica o Registro quando vc informa a Carteira 1   e Sem registro quando informa a carteira 3
Não sei se vc continua fazendo o calculo do nosso número conforme o seu primeiro post.  mas não precisa fazer tudo aquilo basta voce pegar apenas o ano, + o controle de 2 -9 e sequncial. o resto ele calcula o digito pra vc

**Comment by EltonRst** [comment]
@Westfallx, Obrigado pela ajuda, consegui concluir o boleto, já está funcionando, obrigado também a todos que colaboraram e colaboram todos os dias para o projeto.

**Comment by eversonclei** [comment]
Pessoal, boa tarde.

Na documentação do manual CNAB 400 do sicredi, a formação do nosso número contem:

AA/bnnnnn-d

AA = Ano de geração do título
b  =  Geração nosso número: 1 - Cooperativa  /  2 a 9 - Cedente 							
Nnnnn = Número sequencial por cedente
d     = Digito verificador mod 11							

Minha dúvida está na variação do item ( b ) de 2 a 9 quando emitida pelo próprio cedente ... este valor é escolhido aleatório ou eu tenho que escolher uma variação e aplicar sempre para todos os boletos ? 

Ex: 7 

Como funciona esta parte da geração ?

**Comment by Marlonwg** [comment]
Bom dia sei que o POST e antigo mas tem este codigo para .net minha plataforma quando add para C# aqui da um erro no Pacote NuGet nao encontra a versao 1.1.7

**Comment by carloscds** [comment]
@Marlonwg Use a versão mais atual do pacote.

**Comment by Marlonwg** [comment]
![image](https://user-images.githubusercontent.com/58432414/69970249-4aef6480-14f4-11ea-8869-3c7fae312e7b.png)

Este são os erros gerados quando utilizo o Boleto2.net

**Comment by Marlonwg** [comment]
Carlos eu consegui abrir o Boletonet aqui e visualizar ele como no caso agora eu add ele ao meu SH para fazer um boleto bancario precizo importa-lo o projeto todo do boleto.net para ele ?

**Comment by Marlonwg** [comment]
Tem algum tutorial de implementação desta API ? passo a passo como implementar e gera boleto pelo Sicred ?

**Comment by Marlonwg** [comment]
> @Marlonwg Use a versão mais atual do pacote.

Tem algum tutorial de implementação desta API ? passo a passo como implementar e gera boleto pelo Sicred ?
