### ISSUE TITLE
CEF - arquivo remessa CNAB240

### ISSUE THREAD

**Issue by alfmarc** [BoletoNet/boletonet#239]
No arquivo Banco_Caixa.cs é preciso corrigir GerarTrailerLoteRemessaCNAC240SIGCB(int numeroRegistro)
Alterar o 3o. parâmetro de TRegistroEDI dos 3 campos abaixo porque tem quantidade de caracteres (15) menores que intervalo entre posições (17)
posição 30 até 46   (15) - Valor Total dos Títulos em Carteiras (CORRETO: 17)
posição 53 até 69   (15) - Valor Total dos Títulos em Carteiras (CORRETO: 17)
posição 76 até 92   (15)- Quantidade de Títulos em Carteiras    (CORRETO: 17)
Já testei junto ao banco e a alteração está correta.

**Comment by marcus2vinicius** [comment]
Agradecemos seu feedback.

**Comment by ivanteles** [comment]
![caixa](https://cloud.githubusercontent.com/assets/843086/16842432/dc3ab968-49b3-11e6-8374-ee03b651690e.JPG)
Cara, fiz essa implementação esses dias, e segundo manual como imagem em anexo, são 15.
Já tenho 2 clientes usando em produção.

**Comment by marcus2vinicius** [comment]
De acordo com esse layout informa que o tamanho é 17.
http://www.caixa.gov.br/Downloads/cobranca-caixa-manuais/Manual_Leiaute_CNAB240_SIGCB.pdf

**Comment by ivanteles** [comment]
Verdade, eu segui outro manual fornecido pela caixa e homologuei os boletos e remessa.
E como disse, está em produção de forma automática a geração da remessa e tratamento do retorno em uma app web.

**Comment by marcus2vinicius** [comment]
Quando foi efetuada a homologação @ivanteles ? Pois, o layout acima é de 14/10/2015.

**Comment by ivanteles** [comment]
Dia 16/06/2016, junto a empresa que fornece o aplicativo VAN para meu cliente conforme mensagem abaixo, e nesta mesta data enviamos os mesmos arquivos para o GIRET e está 100% funcionando.

Boa tarde!

Prezados, segue análise do boleto:

A análise inicial foi concluída com sucesso, porém a homologação final é feita pela GIRET na CAIXA.
HOMOLOGAÇÃO TÉCNICA DOS BOLETOS DE COBRANÇA
 Antes do envio de boletos aos Pagadores, o Cliente Beneficiário deve obrigatoriamente encaminhar à sua Agência CAIXA amostras dos boletos por ele emitidos, para que haja a devida homologação técnica. Em caso do envio por e-mail, anexar os boletos no formato PDF e zipado.
 As amostras devem possuir no mínimo 10 e no máximo 20 boletos, contendo:
- Todos os Dígitos Verificadores Geral do Código de Barras possíveis (de 1 a 9);
- Todas os Dígitos Verificadores do Campo Livre possíveis (de 0 a 9).
 O Cliente Beneficiário assume total responsabilidade pelas consequências advindas da emissão de boletos sem a validação da CAIXA.

**Comment by marcus2vinicius** [comment]
Bom, então devemos manter o que já está funcionando.

**Comment by alfmarc** [comment]
Os tamanhos dos campos de TRegistroEDI são:
3 + 4 + 1 + 9 + 6 + 6 + 15 + 6 + 15 + 6 + 15 + 31 + 117
o que dá 234 no total.
Ao tentar enviar para a VAN FINNET falhou porque a linha não tem 240 caracteres.

Talvez a CEF aceite, e nem verifique isso, porque a nota destes campos diz que:
C071 Valor Total dos Títulos em Carteiras
Somatória dos valores dos títulos de cobrança enviados no lote do arquivo de acordo com o Código da
Carteira. Só serão utilizados para informação do arquivo retorno.

O ideal seria que algum dos colegas que já homologaram junto à CEF com 234 caracteres pudessem tentar com 240. É possível isso?

**Comment by daldegam** [comment]
Estou também realizando a homologação e estou tendo justamente esse problema.

Vejam o retorno da homologação:
`Registro numero 5 com tamanho 234 (OBSERVE QUE NA LINHA 5 PRECISA TER 240 POSIÇÕES)`

Acabei de alterar aqui as três linhas de 15 para 17, e envie novamente para analise.

O manual que estou utilizando é de 14/10/2015.

**Comment by marcus2vinicius** [comment]
@alfmarc essa issue poderá ser fechada pois foi  resolvido.

**Comment by cezarant** [comment]
@alfmarc  tudo bem? Poderia encerrar a issue por favor? Parece que a discussão foi encerrada.
