### ISSUE TITLE
Erro no fonte.

### ISSUE THREAD

**Issue by m98proxy** [BoletoNet/boletonet#240]
Acredito que exista um erro a partir linha 571 do arquivo:

`https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net/Banco/Banco_Brasil.cs`

Existe uma condição if mas não existe o else o que faz com que o código de barras não seja gerado.

Claro que deve ser verificada a RN mas mesmo assim, deve ter uma condição de contradição para gerar o código de barras.

Mudei a condição para :

`if (boleto.Cedente.Convenio.ToString().Length == 6 && boleto.TipoModalidade.Equals("21"))`

Parece ter funcionado.

**Comment by carloscds** [comment]
@m98proxy Envie um PR com a sua correção

**Comment by m98proxy** [comment]
Feito.

**Comment by cezarant** [comment]
@m98proxy  tudo bem? Poderia encerrar a issue por favor? Parece que a discussão foi encerrada.
