### ISSUE TITLE
Comprovante de Entrega

### ISSUE THREAD

**Issue by igorocampos** [BoletoNet/boletonet#255]
Bom dia a todos, uso a biblioteca do Boleto.NET a tempos, e hj um cliente me pediu para incluir o comprovante de Entrega no final do boleto. Vi que tinha uma propriedade HtmlComprovanteEntrega, e concatenei o conteudo dessa propriedade ao final do Metodo MontaHtml(); para imprimir o que ja estava aparecendo + o comprovante, porém na parte do comprovante ao invés de aparecer as informações, está @CEDENTE, @SACADO, @LOCALPAGAMENTO, @NOSSONUMERO, etc.

É pra eu substituir manualmente ?

**Comment by rodolfoghi** [comment]
Hoje aqui tivemos esta mesma solicitação, apenas setei a propriedade `boletoBancario.MostrarComprovanteEntrega = true;` e o comprovante foi impresso corretamente.

**Comment by cezarant** [comment]
@igorocampos  tudo bem? Poderia encerrar a issue por favor? Parece que a discussão foi encerrada.
