### ISSUE TITLE
Código de Barras não Aparece depois de Sistema Publicado

### ISSUE THREAD

**Issue by lduarteoliveira** [BoletoNet/boletonet#257]
Pessoal,

Publiquei o sistema em um servidor e o código de barras do boleto não aparece. Em desenvolvimento, ao realizar o debug, o código de barras aparece, alguém pode me ajudar?

Att,

**Comment by EltonRst** [comment]
Já deu um Rebuild no Projeto do Boleto.Net ?
O projeto de exemplo do Boleto.Net está em MVC, já deu uma olhada lá ?

Já deu uma analisada nos caminhos das imagens ao gerar o html to boleto pra ver se encontra algo, cria um método que salva o html do boleto em um boleto.html dai analisa os caminhos.

**Comment by lduarteoliveira** [comment]
Olá Elton,

Muito obrigado pela ajuda. O projeto não está em MVC, ainda é webform.

A imagem do código de barras não está sendo gerada. TODAS as imagens do boleto são geradas, menos a do código de barras.

Engraçado que em debug a imagem é criada.

Dei o rebuild e não funcionou.

O caminho da imagem da logo é esse:  <td class="imgLogo Al"><img src="/Estudo/WebResource.axd?d=f-2p2aTmRclgCiMQ36KvNOtNpZVNE0X8PDIM7fe7WtyKios-cvL0Xgo3fZUm-clcosTWTRv66V67r3gqIOtygvOK_HmTU1WkK4d_87twLZzl10-eiYiwg58HOCqKTV790&t=636070296124245678" /></td>


O caminho da imagem do código de barras é esse: <td class="EcdBar Al pL10"><img src="ImagemCodigoBarra.ashx?code=03399689700000150009000000000000000001240102" alt="Código de Barras" /></td>

Estou vendo como criar este método para salvar o boleto em html, ainda não achei.

Muito obrigado pela ajuda.

**Comment by lduarteoliveira** [comment]
Elton,

Gerei o HTML do boleto e a imagem é gerada na pasta temp: C:\Users\leandro\AppData\Local\Temp\tmpF3C5.tmp

Será que pode ser alguma configuração do IIS?

Obrigado,

**Comment by lduarteoliveira** [comment]
Elton,

Gerei o arquivo no sistema publicado no IIS, porém, não gera o código de barras nem no arquivo.

Att,

**Comment by EltonRst** [comment]
A princípio nada com o IIS, algum problema de código mesmo.
