### ISSUE TITLE
Sicoob pontos para implementação 

### ISSUE THREAD

**Issue by guigomesa** [BoletoNet/boletonet#267]
Após algum tempo pelejando com o código eu entendi algumas coisas que me ajudaram, fica aí pra quem estiver com problemas também.
- A quantidade de dígitos no nosso número tem de ser igual a 7.
- No código tem de ter 6 casas, valores menores completar com 0 a esquerda.
- Na modalidade usar dois digitos exemplo: "01"

Recomendaria implementar isso pra disparar erro no código e já avisar o que houve facilitaria mil porcento a vida.

**Comment by hernanicamargo** [comment]
Cara, estou precisando implementar o boleto para sicoob e estou com muitas dificuldades. Você teria um exemplo pra compartilhar?

**Comment by RPaiva2108** [comment]
Boa tarde, também estou a procura de um exemplo do sicoob, se alguém tiver para compartilhar :dancer:

**Comment by guigomesa** [comment]
Deixei comentários tentando explicar, mas se houver alguma outra dúvida deixem aí que caso eu saiba tento ajudar.

https://gist.github.com/guigomesa/fdd6491f7875c8123e5a16c0deb8441f

**Comment by RPaiva2108** [comment]
Ótimo exemplo guigomesa, ajudou bastante.
Vou colocar o código que eu usei no exemplo [tirado do exemplo do guigomesa] de teste da boleto.net.arquivo para gerar o boleto, se alguém conseguir incluir nos fontes pra ajudar o pessoal que não está conseguindo, fico grato.  :+1:  

#region BOLETO SICOOB
public void GeraBoletoSicoob(int qtde)
{
	BoletoBancario BoletoBancario;
	List<BoletoBancario> Boletos = new List<BoletoBancario>();

	for (int i = 0; i < qtde; i++)
	{
		// Cria o boleto, e passa os parâmetros usuais
		BoletoBancario = new BoletoBancario();
		BoletoBancario.CodigoBanco = 756; // Codigo do banco Sicoob
		BoletoBancario.MostrarEnderecoCedente = true; // se sim, tem que implementar o [Boleto.Cedente.Endereco]

		//Data não pode ser antigo pois há uma questão da febraban que 
		DateTime Vencimento = new DateTime(2016, 11, 15);

		//Cnpj inclusive com os digitos
		// Numro da conta e digito não fizeram a diferença para mim
		// Agência com 4 dígitos
		Cedente Cedente = new Cedente("00.000.000/0001-00", "Nome do Cedente", "0000", "", "", "");

		// Código do cedente com 6 casas (sem o dígito) se houver menos casas completar com 0 (zero) a esquerda.
		Cedente.Codigo = "053976";
		// Digito do cedente
		Cedente.DigitoCedente = 7;
		// Número da carteira
		Cedente.Carteira = "1";

		// Aqui foi onde mais tive problemas pra entender de fato
		// O "nosso número" pode ter no máximo 7 dígitos
		Boleto Boleto = new Boleto(Vencimento, 10, "1", "9000002", Cedente);
		// Optei por repetir o nosso número mas aqui pode variar conforme a necessidade
		Boleto.NumeroDocumento = "9000002";
		// Aqui vai de acordo com a modalidade mas ela deve ser com duas casas se a modalidade é 1 (um)
		// por exemplo você deve colocar '01' [REGISTRO DE TITULOS]
		Boleto.TipoModalidade = "01";
		// Por segurança também passei o número de parcelas no meu caso '1' (um)
		Boleto.NumeroParcela = 1;
		Boleto.EspecieDocumento = new EspecieDocumento_Sicoob("1"); // Duplicata Mercantil

		// Obrigatorio se o MostrarEnderecoCedente = true
		Endereco CendenteEndereco = new Endereco();
		CendenteEndereco.End = "Endereço do cedente";
		CendenteEndereco.Bairro = "Bairro";
		CendenteEndereco.Cidade = "Cidade";
		CendenteEndereco.CEP = "14700-000";
		CendenteEndereco.UF = "SP";
		Boleto.Cedente.Endereco = CendenteEndereco;

		// Daqui pra baixo não há muita diferença são apenas informativos 
		Boleto.Sacado = new Sacado("000.000.000-00", "Nome do seu Cliente");
		Boleto.Sacado.Endereco.End = "Endereço do seu Cliente";
		Boleto.Sacado.Endereco.Bairro = "Bairro";
		Boleto.Sacado.Endereco.Cidade = "Cidade";
		Boleto.Sacado.Endereco.CEP = "14700-000";
		Boleto.Sacado.Endereco.UF = "SP";
		Boleto.Sacado.Endereco.Logradouro = "Avenida";
		Boleto.Sacado.Endereco.Numero = "123";

		BoletoBancario.Boleto = Boleto;
		BoletoBancario.Boleto.Valida(); //Faz a validação

		Boletos.Add(BoletoBancario);
	}

	GeraLayout(Boletos);
}
#endregion

**Comment by TMaiaBR** [comment]
guigomesa, vc esta conseguindo gerar o arquivo de remessa? Estou gerando mas meu cliente diz que ao enviar o arquivo o site do Sicoob informa que o número do cliente não foi encontrado. Meu cliente pegou esse número do cliente com o gerente dele e me passou, mas mesmo assim continua mensagem.

Seguindo o manual do Sicoob, no header do remessa, na posição 27 é o prefixo da cooperativa, o componente coloca ai o número da agencia. Na posição 31 é o dígito do prefixo, o componente esta colocando o dígito da agência. Na posição 32 é o número do cliente, o componente esta colocando o código do cedente e na posição 40 é o dígito do código, o componente esta colocando o dígito da conta.

Tudo ok, mas o cliente me diz que deu o tal erro quando ele envia o arquivo. Pesquisando na internet já vi pessoas dizendo que não deve colocar os dígitos da agência e conta nas posições 31 e 40. Então removi esses caracteres e ajustei o hearder de modo a ficar igual o do Itau respeitando as posições, mas novamente o cliente disse que deu o mesmo erro.

Não sei mais o que fazer.

**Comment by RPaiva2108** [comment]
TMaiaBR

Eu consegui homologar com o banco, se precisar de ajuda manda um email que te ajudo, vlw.

**Comment by TMaiaBR** [comment]
Eu estou tendo problemas, no arquivo remessa gerado pelo Boleto.Net o gerente do Siscoob esta dizendo que não foi informado o Nosso Número.


Vc usou a última versão do Boleto.Net?


________________________________
De: RPaiva2108 <notifications@github.com>
Enviado: segunda-feira, 16 de janeiro de 2017 09:12
Para: BoletoNet/boletonet
Cc: TMaiaBR; Comment
Assunto: Re: [BoletoNet/boletonet] Sicoob pontos para implementação (#267)


TMaiaBR

Eu consegui homologar com o banco, se precisar de ajuda manda um email que te ajudo, vlw.

-

**Comment by TMaiaBR** [comment]
Eu estou tendo problemas, no arquivo remessa gerado pelo Boleto.Net o gerente do Siscoob esta dizendo que não foi informado o Nosso Número.


Vc usou a última versão do Boleto.Net?

**Comment by RPaiva2108** [comment]
Cara, tenta fazer essas alterações ai e ve se da certo.

Formatar o nosso numero com 7 casas [Preenchido com 0 a esquerda].
Formatar o codigo do cedente com 6 [Preenchido com 0 a esquerda].
Informar o digito da agencia "0".
TipoModalidade = "01"; // REGISTRO DE TITULOS
NumeroParcela = 1;

Obs: Use a função Valida(), no boleto que vai gerar o arquivo remessa, pq é na Valida() que monta o nosso numero [Que eu me lembre no sicoob].

**Comment by TMaiaBR** [comment]
Tudo isso já tinha feito, exceto o Valida() antes de inserir o boleto na coleção de boletos. Após fazer isso realmente o nosso número ficou diferente, porém desde o dia que vc respondeu a cliente ainda não me deu um retorno se funcionou ou não. Estava esperando ela me responder para eu postar arqui o resultado final, mas nada ainda.

OBS: Eu uso o Nosso Número com 8 posições, quando troquei para 7 passou a dar erro na geração da linha digitável. Debugando vi que o problema ocorre quando um Substring é feito, como o Nosso Numero ficou com 7 posições dava erro de matriz, voltei para 8 posições e funcionou. Só preciso do retorno da cliente para saber se esta tudo ok.

**Comment by cezarant** [comment]
@guigomesa  tudo bem? Poderia encerrar a issue por favor? Parece que a discussão foi encerrada.

**Comment by TMaiaBR** [comment]
> @TMaiaBR , poderia me ajudar? estou trabalhando na geração do arquivo de remessa.
> me envia um email: [fabio.jose.mendonca@gmail.com](mailto:fabio.jose.mendonca@gmail.com)

Cara, na época deste post eu não consegui resolver o problema. Perdi o cliente. Desde então não tive mais clientes com esse banco.

**Comment by guigomesa** [comment]
Oi @cezarant  eu não consigo encerrar as issues, tem de ser alguém com acesso de editor no projeto do github
