### ISSUE TITLE
Banco do Brasil: Variação 17-051

### ISSUE THREAD

**Issue by rafasilvabh** [BoletoNet/boletonet#268]
Olá, boa tarde

O banco liberou uma nova variação para empresa no qual trabalho. Quando chamo o método "bolBancoDoBrasil.Boleto.Valida()" da classe Banco_Brasil caio na exception throw new NotImplementedException("Carteira não informada. Utilize a carteira ...... 17, 17-019, 17-027, 18, 18-019, 18-027, 18-035........");

Tenho conhecimento no TFS/VSOnline, baixei este projeto via GIT do Visual Studio e incluí uma nova variação 051 para carteira 17, sendo idêntica a variação 027 (conforme orientações que tive). 
Gostaria que nas próximas versões já recebecem este código para que no futuro possamos continuar com uso sem maiores dores de cabeça, posso realizar um Commit no projeto ou qual procedimento devo tomar para solicitar incluir?

Obrigado,
Rafael Silva
Coordenador em Gerenciam. de Projetos

**Comment by rafasilvabh** [comment]
A quem solicito autorização para commint? Não localizei este tipo de orientação no projeto. Obrigado.

**Comment by rafaelorasmo** [comment]
Olá Rafael,

Abri um issue pareceido https://github.com/BoletoNet/boletonet/issues/252
Como você fez a implementação? Tem como você incluir a carteira 17/043? Assim seria somente um commit.
Abs

**Comment by rafasilvabh** [comment]
Então, baixei o projeto via GIT no Visual Studio, alterei 2 classes no diretório "src" e criei uma na teste, mas não estou conseguindo realizar commit, não sei se tenho permissão para colaborar no projeto, estou aguardando retorno.
Banco_Brasil.cs; BoletoBancario.cs; BancoBrasil17051Teste.cs [add]

**Comment by rafaelorasmo** [comment]
OK, ficaremos no aguardo.
Abs

**Comment by cezarant** [comment]
@rafasilvabh  tudo bem? Poderia encerrar a issue por favor? Parece que a discussão foi encerrada.
