### ISSUE TITLE
Por onde começar

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/boletonet#303]
Boa noite,

Vou começar a implementar o boleto, já implementei a um tempo atrás em Object Pascal usando o componente ACBr, mas essa é meu primeiro contato com boletos usando C#.Net.

Minha aplicação é uma Winforms, gostaria de saber se existe algum demo ou documentação de como funciona o componente ou se alguém poderia simplesmente dar um ctrl c ctrl v na implementação do seu próprio sistema para eu ter um start.

PS: Sobre a impressão, é usada alguma biblioteca externa ou é nativa? como funciona com winforms?]

Obrigado desde já,

abraços

**Comment by carloscds** [comment]
@marcosgerene Existem alguns exemplos no projeto, você pode começar analisando como é feito.

**Comment by marcosgerene** [comment]
@carloscds,

Dei uma olhada nos exemplos, mas não consigo entender algumas coisas, como a diferença entre Boleto e BoletoBancario e como gerar uma remessa pro Bradesco CNAB 400 (exemplo) sendo que a função que geraria a remessa da classe arquivo resultaria num exception de não implementado.

**Comment by carloscds** [comment]
@marcosgerene Já deu uma olhada aqui: https://github.com/BoletoNet/boletonet/wiki

**Comment by marcosgerene** [comment]
@carloscds 

Sim, olhei o wiki e alguns exemplos antes de abrir a insue, e a abri pois o que achei "pronto" nesse sentido não sanaram minhas dúvidas, de qualquer forma obrigado pela ajuda, vou olhar o código, tentar "desenhar" algo e postar aqui para ver se estou fazendo o correto

abraço

**Comment by carloscds** [comment]
@marcosgerene Percisando, abra uma issue 👍
