### ISSUE TITLE
Espaçamento entre letras

### ISSUE THREAD

**Issue by renanmthy** [BoletoNet/boletonet#304]
Boa tarde pessoal

Gostaria de saber se existe alguma forma de aumentar o espaçamento entre as letras do boleto gerado a partir da função "MontaBytesListaBoletosPDF", pois as mesmas ficam coladas umas nas outras, dificultando demais a leitura.

Estou gerando meus boletos com o seguinte método:

```
private void GeraLayout(List<BoletoBancario> boletos)
{
    try
    {
        var arquivo = System.IO.Path.GetTempPath() + @"boleto.pdf";

        BoletoBancario bol = new BoletoBancario();
        var pdf = bol.MontaBytesListaBoletosPDF(boletos);

        FileStream flStr = new FileStream(arquivo, FileMode.Create);
        flStr.Write(pdf, 0, pdf.Length);
        flStr.Close();
    }
    catch (Exception ex)
    {
        MessageBox.Show(ex.Message);
    }
}
```

Já tentei alterar os arquivos **BoletoNet.css** e **BoletoNetPDF.css**, adicionando a propriedade "**letter-spacing**" ficando da seguinte forma:
`.ct {
font: 9px "arial narrow";
color: #000033;
letter-spacing: 1px;
}`

Porém o valor mínimo que ele aceita é 1px, ficando assim um espaço muito grande, deformando o PDF. 

**OBS.:** 
1. Já tentei valores decimais, ou até mesmo trocar a unidade de 'px' para 'mm, em e etc', porém sem exito.
2. Ao gerar apenas o HTML, o espaçamento fica perfeito, sem necessidade de alteração. Já após a conversão para PDF, ele ocasiona esse problema.

Grato pela atenção desde já.

**Comment by kelvindules** [comment]
Para o caso de outras pessoas chegarem neste issue, aconselho talvez alterar a fonte de .ct e .ctn para consolas tamanho 10. O resultado tem sido satisfatório.

**Comment by cezarant** [comment]
@renanmthy  tudo bem? Poderia encerrar a issue por favor? Parece que a discussão foi encerrada.

**Comment by antoniojp** [comment]
Existe alguma forma de realizar essa alteração de fonte, sem ter que alterar o fonte do BoletoNet? Ou invariavelmente eu tenho que baixar os fontes da framework, alterar o CSS e gerar outra Dll?

**Comment by kelvindules** [comment]
@antoniojp Hoje em dia já existe um método melhor, utilizando o método AjustaTamanhoFonte da classe Boleto Bancário assim:
```c#
AjustaTamanhoFonte(double tamanhoFonteTextos = 10, 
                   double tamanhoFonteRotulos = 9.8, 
                   double tamanhoFonteInstrucaoImpressao = 9,
                   double tamanhoFonteInstrucoes = 10)
```
Mais detalhes aqui: https://github.com/BoletoNet/boletonet/wiki/Guia-do-Desenvolvedor

**Comment by antoniojp** [comment]
Obrigado, @kelvindules!! Eu usei este método e melhorou um pouco a aparência, mas queria mudar a fonte mesmo. A "Arial Narrow" dos títulos, deixa um espaçamento muito curto entre as letras, gerando uma estranheza na geração do PDF.

Vou seguir a sua sugestão, e vou ver se acho outra coisa, sem ter que necessariamente alterar a framework do BoletoNet.

Valeu!!!

**Comment by kelvindules** [comment]
@antoniojp fiz um pull request adicionando um método AjustaFamiliaFonte aqui #798 . Vê se te ajuda

**Comment by antoniojp** [comment]
Obrigado @kelvindules!!! 

Já vi seu pull request. Você acha que passa quanto tempo para ficar disponível no Nuget do VisualStudio? Olhei agora e vi que ainda está a versão anterior (2.1.0.76).

**Comment by kelvindules** [comment]
Putz não tenho certeza... Acredito que quem cuida dessa parte é o @carloscds .

**Comment by carloscds** [comment]
@antoniojp O nuget é gerado a cada 30 dias mais ou menos. Eu adicionei o feed para o build automatico, este acontece a cada PR. Você pegar na home do projeto: https://github.com/BoletoNet/boletonet/blob/master/README.md
