### ISSUE TITLE
Gerar múltiplos boletos

### ISSUE THREAD

**Issue by MarlonEtiene** [BoletoNet/boletonet#308]
Olá  a todos,
É possível gerar múltiplos boletos, inclusive para "sacado" diferentes? E também gerar a remessa para esse conjunto de boletos gerados?
Se possível, podem me dar um exemplo?

Obrigado!

**Comment by henriquevc** [comment]
![image](https://cloud.githubusercontent.com/assets/10618168/19645150/19e4bf8e-99d2-11e6-99fe-fd6f674ae0fe.png)

Nesse método eu gero vários boletos e gero o arquivo de remessa. Acho que com isso da pra ter uma ideia de como é. Se tiver alguma dúvida estou a disposição.

**Comment by MarlonEtiene** [comment]
@henriquevc Muito obrigado por sua resposta, resolveu meu problema!

**Comment by marcosgerene** [comment]
@henriquevc ,

Poderia disponibilizar essa função Util.GerarBoleto?

**Comment by henriquevc** [comment]
@marcosgerene ela é meio grande, tem 130 linhas
[GerarBoleto.txt](https://github.com/BoletoNet/boletonet/files/648775/GerarBoleto.txt)

**Comment by marcosgerene** [comment]
@henriquevc muito obrigado
