### ISSUE TITLE
Geração de arquivo remessa - Caixa

### ISSUE THREAD

**Issue by diegomodolo** [BoletoNet/boletonet#32]
Bom dia, verifiquei que na classe Banco_Caixa.cs, as funções:
GerarDetalheRemessa()
GerarTrailerRemessa()
não estão implementadas, então o método abstract é chamado e não gera nenhum registro.
Também verifiquei que já existem as funções GerarDetalheRemessaCNAB240  e GerarDetalheRemessaCNAB400, assim como GerarTrailerRemessaCNAB240SIGCB e GerarTrailerRemessa400.

Eu criei as duas funções acima e chamei as que já existiam, mas não sei se foi deixado sem implementar por algum motivo. 
Posso fazer o commit com as alterações?

**Comment by carloscds** [comment]
@diegomodolo Pode mandar o PR

**Comment by diegomodolo** [comment]
@carloscds Não tenho permissão para fazer o Push.

**Comment by carloscds** [comment]
@diegomodolo Sim, você manda como Pull Request a partir do seu fork do git.

**Comment by diegomodolo** [comment]
@carloscds, criei o fork e fiz o pull. Não sei se fiz tudo certo, primeira vez usando o git, mas qualquer coisa me fale por favor. Obrigado.

**Comment by carloscds** [comment]
@diegomodolo Não veio o pull request. No seu repositório crie um pull request apontando para o master do boletonet.

**Comment by diegomodolo** [comment]
Acho que agora foi @carloscds. Desculpe o incômodo, realmente nunca havia usado o github.

**Comment by carloscds** [comment]
@diegomodolo Fica tranquilo e mande quantos PRs quiser. A idéia é o projeto crescer!
