### ISSUE TITLE
Planos para .net core?

### ISSUE THREAD

**Issue by lfreneda** [BoletoNet/boletonet#320]
.Net core está por ai, planos para suporte?

**Comment by carloscds** [comment]
@lfreneda Sim.

**Comment by lfreneda** [comment]
@carloscds estou disposto a ajudar, vocês tem algum "roadmap" para isso?
alguem já começou ou algo assim?

**Comment by lfreneda** [comment]
atenção nota 10

**Comment by carloscds** [comment]
@lfreneda Desculpe estava fora do pais com acesso reduzido a web. Iremos primeiramente mudar para a versão 2.0. Para .net core, será na sequencia. Mas se quiser fazer algum estudo e ajudar, é bem vindo!

**Comment by lindembergz** [comment]
Como anda essa conversão ?

**Comment by carloscds** [comment]
@lindembergz Precisamos de colaboradores para isto acontecer ? Topa ?

**Comment by lindembergz** [comment]
Estamos precisando... :-\  ... de alguma forma teremos que portar para o core... mais especificamente o arquivo  BoletoBancorio.cs

**Comment by carloscds** [comment]
@lindembergz Teremos que criar um novo projeto, para não quebrar a compatibilidade com outros. posso criar o projeto na estrutura. Você já deu uma olhada no BoletotNet 2 ?

**Comment by rodolfoghi** [comment]
@carloscds pode contar comigo.

**Comment by LinlindembergCz** [comment]
decidimos fazer seguinte ideia...  agente vai criar uma "camada" no ambiente  .Net CORE que irá se comunicar via Rest com a solucao BoletoNET que está hospedado em um container windows na Amazon. SIMPLES, você só precisará implementar as requisoes (Post ou Get)  e deixar o BoletoNet fazer o resto...

**Comment by LinlindembergCz** [comment]
Vimos que o .Net CORE não está preparado para implementar controles visuais... gerar Código de barras, desenhar imagens, gerar PDF... então o custo de conversão será muito alto.

Bem, quando estiver terminado, vou colaborar com a solução via Rest ... boa sorte!
