### ISSUE TITLE
Problem Parse decimal 

### ISSUE THREAD

**Issue by claucometa** [BoletoNet/boletonet#322]
Reparei que quando faz parse de um número decimal dá erro se o windows estiver no idioma inglês. Por isso, faça substituição também de pontos. Seria mais correto uma extensão para fazer essa conversão, não?

```
   static internal string ParseCash(this decimal cash, string format = "0.00")
        {
            return cash.ToString(format).Replace(",", "").Replace(".", "");
        }
```

**Comment by celsojr** [comment]
Parece que esse problema já foi corrigido. Veja #317

**Comment by cezarant** [comment]
@claucometa  tudo bem? Poderia encerrar a issue por favor? Parece que a discussão foi encerrada.
