### ISSUE TITLE
Seção beneficiário do boleto deve conter Nome, Endereço e CNPJ

### ISSUE THREAD

**Issue by marcus2vinicius** [BoletoNet/boletonet#330]
Ao homologar o boleto da **Caixa SIGCB** foi exigido acrescentar na seção beneficiário o endereço e o CNPJ.
**Especificações Técnicas para Emissão de Boletos Cobrança Bancária CAIXA - SIGCB** 
http://www.caixa.gov.br/Downloads/cobranca-caixa/ESP_COD_BARRAS_SIGCB_COBRANCA_CAIXA.pdf

![caixa](https://cloud.githubusercontent.com/assets/5714631/20534326/9abb84ae-b0bf-11e6-9143-2123076f4344.png)

**Obs.:** Conforme Lei Federal 12.039/2009, os documentos de cobrança de dívida encaminhados ao consumidor devem constar o Nome, o Endereço e o CPF/CNPJ do fornecedor do produto ou serviço. Dessa forma, caso o Endereço do Beneficiário não conste na Ficha de Compensação deve constar no Recibo do Pagador.
http://www.planalto.gov.br/ccivil_03/_Ato2007-2010/2009/Lei/L12039.htm

**Diante disso o que devemos fazer?**

**Comment by rodolfoghi** [comment]
Acredito que alterando a propriedade MostrarEnderecoCedente para true resolva. Aqui temos usado assim.

```
BoletoBancario boletoBancario = new BoletoBancario();
boletoBancario.MostrarEnderecoCedente = true;
```

**Comment by marcus2vinicius** [comment]
Obrigado @rodolfoghi

**Comment by marcus2vinicius** [comment]
**ps.:** E para mostrar o CNPJ na ficha de compensação deve-se usar:
```c#
cedente.MostrarCNPJnoBoleto = true;
```
