### ISSUE TITLE
Carnê - Tres boletos por folha

### ISSUE THREAD

**Issue by dionathanbatista** [BoletoNet/boletonet#347]
Bom Dia.
Como fazer para que a dll imprima 3 boletos por folha no formato carne??
Tentei aqui mas sai cortando

![imgboletos](https://cloud.githubusercontent.com/assets/19978403/20970306/aee813d6-bc6b-11e6-9462-7969c6898c4f.png)

Alguem poderia me dar uma luz

**Comment by jeffersonshibuya** [comment]
Bom dia, não consegui gerar 3 arquivos por folha, somente 2, e não sei se foi a melhor maneira, mas fiz via css. Meu código ficou assim: 

![2titulospor folha](https://cloud.githubusercontent.com/assets/10772632/21228018/59309324-c2c3-11e6-944c-fb7a21872106.jpg)

ele verifica se a qtd eh par ele adiciona um css para quebrar a pagina

**Comment by EltonRst** [comment]
@jeffersonshibuya Sim, não é a melhor maneira, mas não tem como fugir muito disso, dá uma olhada num Isssue meu bem antigo: [Issue 165](https://github.com/BoletoNet/boletonet/issues/165)

Nesse caso usei algo parecido para implementar sem mexer na estrutura toda, mas te dou mais um conselho, em vez de usar `(dynamic loteBoletos)`   já receba na lista `(List<BoletoBancario> lote)`
ajuda a economizar memória.

**Comment by hugofialho** [comment]
Consegui imprimir 3 boletos por folha, dois arquivos foram alterados:

Arquivo: Html.resx 
Variável : ReciboCedenteParte12
Valor: <table class="ctN w666"><tr class="h13"><td /></tr><tr><td class="Ar">Corte na linha ontilhada</td></tr><tr><td class="cut" /></tr></table>


Arquivo: BoletoNetPDF.css
.ebc {
	width: 4px;
	height: 436px;
	border-right: dotted 1px #000000;
	margin-right: 4px;
}

**Comment by hugofialho** [comment]
Segue o valor da variável ReciboCedenteParte12

`<table class="ctN w666">
<tr class="h13"><td /></tr>
<tr><td class="Ar">Corte na linha pontilhada</td></tr>
<tr><td class="cut" /></tr>
</table>`

**Comment by cezarant** [comment]
@dionathanbatista  tudo bem? Poderia encerrar a issue por favor? Parece que a discussão foi encerrada.
