### ISSUE TITLE
Endereco tem prorpiedades redundantes

### ISSUE THREAD

**Issue by rcdmk** [BoletoNet/boletonet#35]
A classe `Endereco` tem uma propriedade `Logradouro` e uma `End`.

A propriedade `Logradouro` seria a mais descritiva e correta para ser utilizada, mas a `End` é que é a utilizada na geração de HTML dos boletos.

Minha sugestão é a substituição da propriedade `End` pela `Logradouro` e a remoção dela, para evitar confusões.

Eu só descobri porque o endereço saia em branco porque olhei o código fonte aqui no GitHub e vi a propriedade que era utilizada.

**Comment by carloscds** [comment]
@rcdmk Você pode fazer uma modificação no get da propriedade Logradouro para ele pegar End. Faça a mudança e submenta o pull request.
