### ISSUE TITLE
Função Valida()

### ISSUE THREAD

**Issue by marcosgerene** [BoletoNet/boletonet#355]
Boa noite,

Estou trabalhando com Bradesco, CNAB 400 e estou tendo alguns problemas.

Se eu não chamo a função valida() os campos não tem a formatação correta (como 11 digitos no nosso numero) e não consigo, porém se eu chamo ele formata o nossonumero com / e - e de novo não consigo gerar a remessa...

Alguém pode me dar um exemplo EM CÓDIGO de como gerar os boletos e a remessa a partir de uma lista de registros do contas a receber?

Meu código está +/- assim: https://github.com/BoletoNet/boletonet/issues/354

**Comment by JimmyWesley** [comment]
Cara o nosso numero do Itaú só tem 8 posições no meu caso, fiz uma remessa aqui e coloquei um parâmetro na configuração da conta para falar quantas posições vai usar e na hora de criar o nosso numero eu coloquei a chamada da variavel.
Assim ele funciona. já homologuei a remassa CNAB400 no Itaú.

var nossoNumero = string.Format("{0,30}", Cobranca.id.ToString("D" + Cobranca.Conta.nPosicoesCarteira.ToString())).Trim();

Abraços,

**Comment by marcosgerene** [comment]
@JimmyWesley,
Obrigado pela ajuda, mas no meu caso como uso winforms optei por fazer uma ferramenta à parte em lazarus usando o ACBrBoleto, tinha urgência e muitas dúvidas/problemas.

De qualquer forma, obrigado, abraços

**Comment by fmfabiano** [comment]
pessoal bom dia!
estou com dificuldade, em alterar para a carteira 138 do banco itau(registrado),quando entra na função valida apresenta mensagem de erro ao gerar boleto,vi que no código, a carteira 138 nao existe. nao estou conseguindo alterar o codigo via git, ja baixei o codigo ,mas nao consigo compilar.alguem pode me ajudar,porque estou com prazo vencendo pra colocar esta carteira em produção.
obrigado e abraços a todos
