### ISSUE TITLE
Geração dos nossoNumero

### ISSUE THREAD

**Issue by aurelioaraujo** [BoletoNet/boletonet#361]
Bom dia pessoal, existe algum mecanismo que facilite a geração do nosso número? 

Por exemplo, na caixa o nosso número deve conter **17 dígitos**, sendo os dois primeiros relativos a carteira, ao passar um número qualquer, esse  mecanismo iria concatenar os  dois dígitos da carteira e completar os 17 dígitos com algum número escolhido.

Se não existe, qual seria a melhor forma de implementa-lo?

O que acham a respeito? É válido/coerente inserir tal mecanismo na biblioteca?   
Fico no aguardo, desde já obrigado :D

**Comment by JimmyWesley** [comment]
Cara o nosso numero do Itaú só tem 8 posições, qual banco tá gerando essa remessa? Fiz uma remessa aqui e coloquei um parâmetro na configuração da conta para falar quantas posições vai usar e na hora de criar o nosso numero eu coloquei a chamada da variavel.
Assim ele funciona. já homologuei a remassa CNAB400 no Itaú.

var nossoNumero = string.Format("{0,30}", Cobranca.id.ToString("D" + Cobranca.Conta.nPosicoesCarteira.ToString())).Trim();

Abraços,

**Comment by aurelioaraujo** [comment]
Colocou essa linha em alguma classe do framework? Qual?

**Comment by JimmyWesley** [comment]
"var nossoNumero = " é uma string para armazena temporariamente o nosso numero, essa linha vc coloca na sua class do sistema onde vai gerar o boleto, no meu caso o nosso numero é baseado no id da cobrança que vem do DB, e o resto dos números eu coloco 0, to fazendo um ToString("D8") pro Itaú para que o nosso numero fique "00000001" sendo assim o itaú aceita.
