### ISSUE TITLE
Convênio na remessa para Sofisa 

### ISSUE THREAD

**Issue by diegomodolo** [BoletoNet/boletonet#364]
Boa tarde, estou desenvolvendo e homologando o boleto e a remessa para o Banco Sofisa, porém o convênio no mesmo é alfanumérico. 
Alguém já passou por isso em algum outro banco?

**Comment by diegomodolo** [comment]
@carloscds, gostaria de tirar umas dúvidas com você sobre o projeto, posso lhe enviar um e-mail? Se positivo, me informe algum endereço por favor.

**Comment by carloscds** [comment]
@diegomodolo Entra no meu blog: www.carloscds.net e me manda uma mensagem por lá que falamos.
