### ISSUE TITLE
Carteira numérica de 4 digitos

### ISSUE THREAD

**Issue by ffelipebc** [BoletoNet/boletonet#378]
Estou fazendo a implementação para gerar boletos para o Banpará, a carteira deles é numérica de quatro dígitos, basta eu passar esse valor para o método?
Não é necessário utilizar os tipos que estão implementadas na biblioteca?

Desde já, agradeço a ajuda.

**Comment by carloscds** [comment]
@ffelipebc Use os campos necessários para o layout.
