### ISSUE TITLE
Erro na Sigla de Especie Documento Santander

### ISSUE THREAD

**Issue by bcesars** [BoletoNet/boletonet#382]
Senhores,

**boletonet/src/Boleto.Net/Boleto/EspecieDocumento/EspecieDocumento_Santander.cs**

Na linha 124 do arquivo do caminho especificado logo acima consta a Sigla do EspecieDocumento do Santander como apenas "R".
Este deveria vir com a sigla "RC" para **Recibo.**
Uma vez que tentamos homologar com o banco, este item acaba sendo discriminado para correção na geração dos boletos. sendo imprescindível que apareça com esta sigla.

Por favor, verifiquem para que possam alterar esta linha uma vez que ficarei impossibilitado para gerar os boletos sem a sigla correta.

Att.
Fico aguardando o retorno.

**Comment by rfiori** [comment]
Feito com base no Wiki do Santander, arquivo "Layout Cobranca - 240 posicoes padrão Multibanco 02.08.doc" página 14 

![image](https://cloud.githubusercontent.com/assets/4339513/21990581/8de9df2a-dbf6-11e6-8ecb-2f9df7a0aa9c.png)

**Comment by rfiori** [comment]
Olá @carloscds , já houve a correção desse Issue, pode fecha-lo.
