### ISSUE TITLE
Dúvida campos NossoNumero e NumeroDocumento

### ISSUE THREAD

**Issue by brunoheringer** [BoletoNet/boletonet#384]
Prezados, fiquei com uma dúvida com esses dois campos.  NossoNumero e NumeroDocumento
1º: Qual seria a diferença entre eles no boleto?
2º: Ví nos exemplos que é mais utilizado o NumeroDocumento. Procede?
3º: Sabem me dizer se posso padroniza-los para serem o mesmo valor?

Desde já agradeço a comunidade

**Comment by leandrossantos** [comment]
@brunoheringer o NossoNumero é o número sequencial dos boletos e o NumeroDocumento você pode usar para informar o numero da Venda, Fatura, Nota Fiscal, ou seja, o documento que originou o boleto, podendo até informar junto com o numero do documento a identificação da parcela, 123 1/2, 123 2/2 por exemplo.

**Comment by brunoheringer** [comment]
Obrigado @leandrossantos. Entendido.
