### ISSUE TITLE
Dúvidas de campos | Código Ocorrência e Tipo Documento

### ISSUE THREAD

**Issue by brunoheringer** [BoletoNet/boletonet#387]
Pessoal, estou com uma dúvida em dois campos específicos.
Campos Código Ocorrência e Tipo Documento
Ambos estão dentro de Boleto.Remessa.

Esses campos são obrigatório para todos os bancos? O que seriam estes campos?
O BoletoNet "seta" eles automaticamente ou tenho q preencher?

Grato à comunidade;

**Comment by NickeManarin** [comment]
`CodigoOcorrencia ` é o comando da remessa, geralmente é "1" que significa "registrar". Ao alterar dados, diferentes bancos fornecem códigos para informar sobre o que foi alterado.
