### ISSUE TITLE
Leitura do Arquivo de Retorno

### ISSUE THREAD

**Issue by brunoheringer** [BoletoNet/boletonet#396]
Pessoal, estou com dúvidas de como fazer o processamento do arquivo de remessa. 
Se possível, alguém poderia postar o trecho de código que realiza esta função. 

Minha dificuldade está em transformar para regra de negócio em minha aplicação, visto que o método LerArquivoRetorno é void, assim não estou conseguindo "enxergar" o retorno do banco.

**Comment by brunoheringer** [comment]
Se alguém tiver um exemplo de um arquivo seria muito útil para encorporar também e ajudar outros para testarem.

**Comment by bilhega** [comment]
@brunoheringer basicamente eu utilizo a função ArquivoRetornoCNAB400 ( ou 240 ) para "carregar" o arquivo de retorno e depois um foreach para manipulá-la. Algo do tipo : 

ArquivoRetornoCNAB400 cnab400 = new ArquivoRetornoCNAB400();
cnab400.LerArquivoRetorno(xBanco,  streamReaderdoArquivoRetorno.BaseStream );

foreach (DetalheRetorno detalhe in cnab400.ListaDetalhe)
{
 ...
}          


Blz?

**Comment by brunoheringer** [comment]
Top Bilhega. Sua solução veio depois que eu tinha conseguido, mas de qualquer forma vale manter o trecho de código para ajudar os colegas...
