### ISSUE TITLE
Dúvida conceitual sobre arquivos de retorno

### ISSUE THREAD

**Issue by brunoheringer** [BoletoNet/boletonet#401]
Pessoal, gostaria de tirar uma dúvida mais conceitual. 
Sobre o arquivo de retorno ele é gerado de acordo com cada remessa inserida ou pode ser solicitado a qualquer hora pelo cliente do banco para verificar status recente de alguns boletos?

Por exemplo: Solicitar arquivo de retorno 15 dias depois de ter registrado os boletos, para verificar quais boletos foram pagos.

**Comment by rodolfoghi** [comment]
Acredito que o banco devolva 1 arquivo por dia, informando os recebimentos/pagamentos do dia anterior.

**Comment by cezarant** [comment]
@brunoheringer  tudo bem? Poderia encerrar a issue por favor ? Parece que o assunto foi encerrado
