### ISSUE TITLE
Sac no rodapé do Boleto Caixa

### ISSUE THREAD

**Issue by PhilippeDuarte** [BoletoNet/boletonet#405]
Olá pessoal,

Estou com problemas para validar os boletos caixa, o banco está exigindo que para validar o boleto necessita possuir do Sac da Caixa Econômica Federal. 
O seguinte erro foi reportado por eles:

"Em cumprimento ao disposto no Artigo 7º do Decreto 6.523, de 31/07/08, e na Circular BACEN 3.370/07, se no Recibo do Pagador houver a impressão da logomarca CAIXA, é ainda obrigatório constar:
SAC CAIXA: 0800 726 0101 (informações, reclamações, sugestões e elogios)
Para pessoas com deficiência auditiva ou de fala: 0800 726 2492
Ouvidoria: 0800 725 7474
caixa.gov.br"

Alguém já lidou com esse problema?

Obrigado.

**Comment by rfiori** [comment]
Você pode adicionar esta informação na 3ª descrição do boleto que você gera. Isso deve resolver seu problema.

**Comment by ivanassisleal** [comment]
Olá PhilippeDuarte, você consegui resolver esse problema? Estou tendo ele também.

**Comment by PhilippeDuarte** [comment]
Consegui Ivan, não ficou perfeito mas a caixa homologou. Eu resolvi criando uma condição para caso o código do banco seja 104 (Caixa econômica). Com isso eu criei um rodapé customizado. Faça o seguinte abra o arquivo BoletoBancario.cs e adicione os códigos abaixo: 
No método HtmlOffLine vc troca a chamada  HtmlOfflineFooter(html); pelo código abaixo

if (CODBANCO != "104")            
       HtmlOfflineFooter(html);
else
      HtmlOfflineFooterCAIXA(html); 

isso vai fazer com que o sistema invoque um método de rodapé específico para a caixa, porém ainda falta criarmos esse método.  logo abaixo do método HtmlOfflineFooter, adicione esse: 

protected static void HtmlOfflineFooterCAIXA(StringBuilder saida)
        {

            saida.Append("SAC CAIXA: 0800 726 0101 (Informações, reclamações, sugestões e elogios) <p> Para pessoas com deficiência auditiva ou de fala: 0800 726 2492 <p> Ouvidoria: 0800 725 7474 <p> caixa.gov.br");
            saida.Append("</body>\n");
            saida.Append("</html>\n");
        }

A informação ficará logo abaixo da linha onde fica escrito "Corte aqui", além disso ela não vai seguir os padrões de formatação de fonte do resto do boleto. Porém a caixa homologou, então para mim funcionou.

**Comment by ivanassisleal** [comment]
Obrigado

**Comment by PhilippeDuarte** [comment]
Consegui um modo mais fácil e com melhor aparência. No arquivo BoletoBancario.cs, adicione o código abaixo antes da ultima linha: 
if (CODBANCO == "104")
                {
                    _instrucoesHtml = _instrucoesHtml + "<br><br><p>SAC CAIXA: 0800 726 0101 (Informações, reclamações, sugestões e elogios)</p> <p> Para pessoas com deficiência auditiva ou de fala: 0800 726 2492 </p><p> Ouvidoria: 0800 725 7474 - caixa.gov.br   </p>";
                }

**Comment by PhilippeDuarte** [comment]
Consegui um modo mais fácil e com melhor aparência. No arquivo BoletoBancario.cs, adicione o código abaixo antes da ultima linha:
`if (CODBANCO == "104")
                {
                    _instrucoesHtml = _instrucoesHtml + "<br><br><p>SAC CAIXA: 0800 726 0101 (Informações, reclamações, sugestões e elogios)</p> <p> Para pessoas com deficiência auditiva ou de fala: 0800 726 2492 </p><p> Ouvidoria: 0800 725 7474 - caixa.gov.br   </p>";
                }`

**Comment by PhilippeDuarte** [comment]
Consegui um modo mais fácil e com melhor aparência. No arquivo BoletoBancario.cs, método MontaInstrucoes, adicione o código abaixo antes da ultima linha:
`if (CODBANCO == "104") { _instrucoesHtml = _instrucoesHtml + "<br><br><p>SAC CAIXA: 0800 726 0101 (Informações, reclamações, sugestões e elogios)</p> <p> Para pessoas com deficiência auditiva ou de fala: 0800 726 2492 </p><p> Ouvidoria: 0800 725 7474 - caixa.gov.br </p>"; }`

**Comment by cezarant** [comment]
@PhilippeDuarte tudo bem? Poderia encerrar a issue por favor?
