### ISSUE TITLE
NossoNumero - Santander 240

### ISSUE THREAD

**Issue by jaiconM** [BoletoNet/boletonet#409]
Bom dia pessoal,
Estou implementando o boleto santander 240.
Está me retornando uma mensagem dizendo que o NossoNumero deve ter 12 caracteres.
Porém, o nosso número tem 13 caracteres. Esse dado pode ser conferido no pdf do layout 240 do santander - Pagina 3 -> (http://www.wmcsistemas.com/instalar/Layouts%20-%20Boletos_Cheques_Integracoes/Layout%20Santander/Santander%20-%20CNAB%20240.pdf)
O que estou achando estranho é que este arquivo é de 2009. Será que eu estou entendendo algo errado?
Alguém já passou por isso? Tem solução?

**Comment by jaiconM** [comment]
Favor desconsiderar, já vi aqui o que é. O 13º caracter é calculado. Como eu já tenho o NossoNumero pronto, que vem no arquivo retorno do banco, tenho que remover o ultimo caracter e deixar a biblioteca recalcular.

**Comment by alexsandro-xpt** [comment]
@jaiconM, voce conseguiu implementar o boleto Santander? Voce pode me ajudar? Eu recebi um documento do banco para implementar com a carteira 101, vem dizendo sobre Código de Transmissão 240 posições e Código de Transmissão 400 posições que eu não sei qual dos 2 usar. Pode me ajudar?

**Comment by jaiconM** [comment]
@alexsandro-xpt , qualquer uma das duas opções é possível, 240 ou 400. Isso você terá que acertar com  o seu banco. O contrato que você faz com eles que vai dizer qual das duas opções que você vai usar.
Depois é só seguir o Layout cnab respectivo.
Eu só implementei a geração do boleto. Se você tiver que implementar o arquivo remessa não saberei te ajudar pois não fiz isso.

Abs

**Comment by alexsandro-xpt** [comment]
@jaiconM Eles me deram codigo paras duas( 240 e 400) é eu que escolho qual homologar?

Voce disse: "Depois é só seguir o Layout cnab respectivo."

Eu recebi mesmo uns PDFs e 2 dele é sobre `Layout Cobrança CNAB 240 posições padrão Santander Multibanco junho 2015 v 2.7.pdf` e `Layout 400 atual.pdf`

A library Boleto.net já nao tem implementando isto?

**Comment by alexsandro-xpt** [comment]
@jaiconM acho que entendi... andei lendo sites como https://blog.vindi.com.br/o-que-e-o-cnab-e-para-que-ele-serve/ e o codigo de fonte do Boleto.net e vi que tem sim uma função gerador de CNAB, tem até um exemplo para o CNAB240 para o Santander no aplicativo Windows Forms, porem ta erro ao gerar e o motivo é um monde de operações com objectos C# NULL.

Pelo visto ta cheio de problemas e precisa se consertada. Vou dar mais uma olhada de como poderei gerar este arquivo.
