### ISSUE TITLE
Homologação - Banco Mercantil do Brasil

### ISSUE THREAD

**Issue by RPaiva2108** [BoletoNet/boletonet#430]
Bom dia

Vou começar a homologar o banco mercantil e após a homologação vou precisar de uma ajuda para implementa-lo na dll, pois não faço ideia de como subir para o github rs

Obs: Se alguém tiver algum material do banco mercantil e puder postar aqui pra me ajudar eu agradeço.

Grato

**Comment by ernanisp** [comment]
Paiva você tem o pdf do banco que é o manual de desenvolvimento?

**Comment by RPaiva2108** [comment]
Eles me mandaram 4 vou anexar aqui.
[CobrancaCNAB240.pdf](https://github.com/BoletoNet/boletonet/files/776812/CobrancaCNAB240.pdf)
[CobrancaCNAB240Mensagens.pdf](https://github.com/BoletoNet/boletonet/files/776813/CobrancaCNAB240Mensagens.pdf)
[CobrancaCNAB400.pdf](https://github.com/BoletoNet/boletonet/files/776814/CobrancaCNAB400.pdf)
[CobrancaCodigoBarrasFatorVencimento.pdf](https://github.com/BoletoNet/boletonet/files/776815/CobrancaCodigoBarrasFatorVencimento.pdf)
