### ISSUE TITLE
JUNTAR DIGITALIZAÇÕES FRENTE COM AS DIGITALIZAÇÕES DE VERSO (PDF)

### ISSUE THREAD

**Issue by welintonv** [BoletoNet/boletonet#471]
OLA PESSOAL!, GALERA É O SEGUINTE, LA NO MEU SERVIÇO TEM UMA IMPRESSORA QUE ESCANEIA VÁRIOS ARQUIVOS DE UMA SÓ VEZ, POREM NÃO ESCANEIA FRENTE E VERSO, E NORMALMENTE TENHO QUE ESCANEAR 40 FOLHAS FRENTE E VERSO POR DIA E FAÇO ASSIM:  ESCANEIO A FRENTE VIRO A FOLHA E CLICO NO PROGRAMA PARA ESCANEAR DE NOVO E AI ELE COLOCA OS DOIS EM UM ARQUIVO SÓ, IMAGINA FAZER ISSO FOLHA POR FOLHA?, EU QUERIA ESCANEAR TODOS SO FRENTE DEPOIS TODOS SO VERSO E AI DEPOIS DE SER CRIADO OS PDF, JUNTAR AUTOMATICAMENTE OS ARQUIVOS EM UM SÓ ATRAVÉS DO VBA DO EXCEL OU ATRAVÉS DE UM ARQUIVO .BAT OU PELO CMD PORQUE OS TECNICOS DE INFORMATICA AQUI NAO DEIXA INSTALAR PROGRAMAS :(, OBRIGADO.

**Comment by carloscds** [comment]
@welintonv Desculpe, mas acho que você colocou sua dúvida no projeto errado! Aqui é impressão de boletos!

**Comment by cezarant** [comment]
@welintonv tudo bem? Você poderia encerrar a issue?

**Comment by welintonv** [comment]
.
