### ISSUE TITLE
Transmissão de arquivo remessa

### ISSUE THREAD

**Issue by jrlubas** [BoletoNet/boletonet#477]
Boa tarde pessoal.
Tenho uma dúvida quanto ao envio de boleto para a Caixa.
Tenho sempre que usar o internet banking para enviar o arquivo?
Para clientes que não utilizam a versão web e sim o Cobrança Caixa (instalado no PC), dá pra fazer via linha de comando o envio desse arquivo remessa?
Resumindo: como automatizar isso?
Alguém já fez algo parecido?

**Comment by aasf86** [comment]
olá @jrlubas , tambem tive esta mesma preocupação, mas no nosso caso que é Bradesco, é feito envio via upload no bradesconet. infelizmente conosco esta sendo assim. tomara que tenha uma forma de automatizar isso

**Comment by cezarant** [comment]
@jrlubas  tudo bem? Seria possível fechar a issue? Parece que o assunto foi encerrado.
