### ISSUE TITLE
Tamanho (resolução) do pdf gerado

### ISSUE THREAD

**Issue by ferne-br** [BoletoNet/boletonet#478]
Boa tarde,

Estou gerando o PDF através do boletonet, mas ao imprimir, o texto e o código de barras fica muito pequeno, tão pequeno que nem consigo ler o código de barras com meu leitor.

O código de barras está gerando corretamente, pois quando eu dou zoom no PDF e leio o código a partir da tela do computador, o leitor consegue ler normal, mas quando imprime fica tão pequeno que o leitor não consegue ler...

Minha duvida é, existe algum parâmetro que permita deixar o pdf um pouco "maior"... fonte maior, código de barras maior, da maneira que está agora está pouco legível..

![image1](https://cloud.githubusercontent.com/assets/13426367/25355303/87fa38fe-290c-11e7-8bcc-f72ad7878911.JPG)

Obrigado.

**Comment by thiago-cavalini89** [comment]
https://github.com/BoletoNet/boletonet/issues/120

**Comment by ferne-br** [comment]
@thiago-cavalini89 infelizmene esse tópico não me ajuda, mas obrigado pela dica

**Comment by ferne-br** [comment]
Alguém mais tem alguma dica de como deixar o PDF com fonte e código de barras maior?

**Comment by danilobreda** [comment]
Tente alterar algum parametro de tamanho do codigo de barras desse arquivo css:
[BoletoNetPDF.css](https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net/BoletoImpressao/BoletoNetPDF.css)

**Comment by ferne-br** [comment]
parece boa a ideia @danilobreda!! vou tentar.. obrigado!!

**Comment by prmces** [comment]
Veja a função MontaBytesListaBoletosPDF na BoletoBancario.Cs.

Lá existe um parametro ZOOM que vc pode utilizar na geração do PDF.

**Comment by wmeneguim** [comment]
@ferne-br Se possível, pode me mostrar o exemplo do código para geração do PDF? Estou apanhando aqui!

**Comment by cezarant** [comment]
@ferne-br  tudo bem? Seria possível fechar a issue? Parece que o assunto foi resolvido.

**Comment by ferne-br** [comment]
> @ferne-br tudo bem? Seria possível fechar a issue? Parece que o assunto foi resolvido.

Podemos fechar sim... acabei gerando o PDF através do Crystal Reports...

Obrigado à todos pela ajuda.
