### ISSUE TITLE
Implementação de geração de boletos MVC

### ISSUE THREAD

**Issue by RicardoConceptOne** [BoletoNet/boletonet#481]
Boa tarde,

Sou novo no mundo do MVC e estou com dúvidas de como começar a implementação de geração de boletos e de arquivos de remessa no meu projeto.

Eu baixei o projeto para o meu computador porém no exemplo de MVC está meio confuso pra mim, e não sei como começar para gerar os boletos.

Se não for muito, gostaria de uma ajuda quanto a isso.

Att,

**Comment by rodolfoghi** [comment]
De forma bem resumida:

1. Crie um projeto MVC. Talvez [este link](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/introduction/getting-started) ajude.
2. Instale o package do Boleto.Net.
3. Popule um objeto do tipo BoletoNet.BoletoBancario.
4. Chame o método desejado, por exemplo o MontaBytesPDF se quiser os bytes do PDF para exibir em tela, disponibilizar como download, enviar por e-mail etc.

**Comment by RicardoConceptOne** [comment]
Olá, obrigado pela resposta!

Eu estava estudando o exemplo MVC que vem junto com o projeto e ele não menciona este 'BoletoNet.BoletoBancario'.

Existe alguma documentação ou algum arquivo exemplo que deixe mais claro como implementar a geração de boletos e arquivos de remessa em meu projeto?

Att,

**Comment by rodolfoghi** [comment]
Dá uma olhada na classe [Exemplos](https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net.MVC/Models/Exemplos.cs). Ela possui uma propriedade **BoletoBancario** que é inicializada no construtor.
```
public Exemplos(int Banco)
{
    boletoBancario = new BoletoBancario();
    boletoBancario.CodigoBanco = (short)Banco;
}
```
