### ISSUE TITLE
Arquivo remessa banco do brasil

### ISSUE THREAD

**Issue by ivanteles** [BoletoNet/boletonet#486]
Bom dia pessoal.
Estou com problema com arquivo remessa do BB. 
Convenio de 07 posições, carteira 17-019.

Ao gerar a remessa "posições 38 a 57 do registro P"
esta sendo gerado um número estranho: 245088817/2450888, o mais estranho que é esse arquivo remessa está sendo gerado desde 25/05/2016 e só agora o banco reclamou do erro.
Alguém está passando por isso?

O que vi de estranho é, na impressão do boleto está sendo gerado e impresso um nosso número assim: 24508880000005068

E no arquivo remessa em modo debug esta sendo gerado assim: 17/24508880000005068.

**Comment by hericss** [comment]
Olá,

tive o mesmo problema, alterei o código para testar se carteira 17-019, amanhã postarei a classe aqui para verificar se resolve para você.

Se ficar legal, teremos que solicitar a alteração no repositório.

**Comment by hericss** [comment]
Postei o código no #489

**Comment by cezarant** [comment]
@ivanteles tudo bem? Seria possível fechar a issue? Parece que o assunto foi resolvido.
