### ISSUE TITLE
CEF remessa

### ISSUE THREAD

**Issue by hugofialho** [BoletoNet/boletonet#487]
Bom dia pessoal,

estou trabalhando com a caixa econômica federal e preciso criar o arquivo remessa para o banco imprimir e distribuir os boletos. Alguém trabalha dessa maneira?

**Comment by aasf86** [comment]
clone o projeto em sua maquina, nele tem exemplos de como gerar remessas e boletos

**Comment by jrlubas** [comment]
@hugofialho Você conhece uma maneira mais fácil de transmitir os arquivo gerados?
Como você pensa em fazer isso, só por curiosidade?
Tenho que resolver essa questão conforme Issue #477

**Comment by aasf86** [comment]
bom vou falar do nosso caso, nosso sistema gera as remessas através do boletonet, o usuário baixa esta remessa e faz upload na plataforma bradesco net, depois o usuário consegue saber se o boleto foi pago ou não. E também a plataforma do bradesco net fornece o arquivo de retorno diário para fazer a quitação em nosso sistema de forma automática (mas isso é, baixando o retorno na plataforma e fazendo o upload em nosso sistema interno).

**Comment by jrlubas** [comment]
Pois é @aasf86 
Pensei em "automatizar" isso no Cobrança Caixa criando um serviço que pega o arquivo gerado pelo sistema web e salva na pasta de arquivo remessa do cobrança caixa e faz o inverso "escutando" a pasta de arquivo retorno e subindo para processamento no sistema web.
O problema é que, de qualquer forma, o usuário tem que abrir o Cobrança Caixa e mandar enviar ou receber os arquivo através da VAN.
Emito boleto pela caixa assim, mas não sei se há alguma coisa mais "atual" para a CEF, como um webservice, por exemplo.

**Comment by hugofialho** [comment]
@jrlubas não estou tão avançado, comecei a trabalhar hoje com o boleto.net, por enquanto o cliente vai enviar o remessa e pegar o retorno manualmente pelo app da caixa. No seu caso o banco que imprime e distribui os boletos? se sim, quem gera o nosso número do boleto?

**Comment by jrlubas** [comment]
@hugofialho no meu caso o cliente gera o boleto e o nosso número é gerado pelo Cobrança Caixa.
Até peço desculpas porque acabei saindo um pouco do foco do seu post, trocando mensagens com o @aasf86 .
Se você encontrar alguma forma de transmissão e recebimento dos arquivo, que não seja feito pelo Cobrança Caixa, por favor entre em contato comigo.
Queria automatizar o processo de envio/recebimento.
Espero que você tenha sucesso na sua questão.

**Comment by ivanteles** [comment]
@jrlubas Eu automatizei tanto o envio da remessa quanto o tratamento do retorno da seguinte maneira.
O sistema é web então convenci o cliente que contratar um servido dedicado.
E nele tem instalamos a van da caixa e configuramos um task pra ela enviar e receber os arquivo de tempo em tempo.
E na minha app de tempo em tempo tb, gero as remessa e trato os retornos se necessário.

**Comment by jrlubas** [comment]
@ivanteles vc fez isso via linha de comando?
Poderia me explicar quais os arquivos e comandos envolvidos?

**Comment by aasf86** [comment]
poderiam me explicar o que é "van da caixa"

**Comment by ivanteles** [comment]
@aasf86  Van são as empresas terceirizadas responsáveis por instalar os aplicativos que fazem a comunicação com o banco.
Elas que instalam, configuram e treinam as empresas a utilizarem programas como o cob caixa.

**Comment by aasf86** [comment]
tendi...

**Comment by jrlubas** [comment]
@aasf86 são responsáveis pelos "gateways" de transmissão de dados entre aplicativos de conciliação bancária. Nesses gateways há criptografia dos dados, compactação, etc.
Não é simplesmente um "envio de arquivo".

**Comment by aasf86** [comment]
sinistro...

**Comment by AllefBastos** [comment]
Bom dia, desde o comeco da semana estou tentando enviar uma remessa para a caixa e so me retorna este erro ''REMESSA REJEITADA - 11/21/17 AS 11.25.18ERROS ENCONTRADOS: REG.TIPO 1 - COD.DE ERRO POSICOES 30/31 E 74/75.'' Por favor alguém me da uma luz, já liguei no suporte e não conseguiram me falar a causa.
