### ISSUE TITLE
Versão 2.1.0.62 do pacote nuget não contém mais a classe ArquivoRetornoCRB643

### ISSUE THREAD

**Issue by AlbertoMonteiro** [BoletoNet/boletonet#49]
Até a versão Boleto.Net 2.1.0.24 eu usava a classe ArquivoRetornoCRB643
Porém quando atualizei para a 2.1.0.62 ela não é mais reconhecida.

**Comment by carloscds** [comment]
@AlbertoMonteiro A classe ainda existe e a ultima mudança foi feita por você.

**Comment by AlbertoMonteiro** [comment]
@carloscds Pois é, pois isso que achei estranho.
Investiguei mais e vi que a build do appveyor que gerou o pacote foi essa abaixo:
https://ci.appveyor.com/project/carloscds/boletonet/build/2.1.0.62

Essa build usou o commit **59aa24b407d3b43947e0fb39ad5bc2cbf8c54566**
Esse classe deveria estar dentro dessa pasta **boletonet/src/Boleto.Net/Arquivo/CBR643**
E se olharmos a estrutura de pastas do projeto desse commit acima, a pasta **CBR643** não existe dentro de **Arquivo**, segue o link: https://github.com/BoletoNet/boletonet/tree/59aa24b407d3b43947e0fb39ad5bc2cbf8c54566/src/Boleto.Net/Arquivo

Para não usar o ultimo commit, vou usar esse f522a33ed0f66f5282ba59ce0cd340ee32931821 como referência, que é o commit quando você colocou a badge do gitter.

Se olharmos a estrutura de pasta dele, vamos encontra a pasta **CBR643**. Segue o link: https://github.com/BoletoNet/boletonet/tree/f522a33ed0f66f5282ba59ce0cd340ee32931821/src/Boleto.Net/Arquivo

Acho que houve algum problema no build do AppVeyor e ele usou um commit anterior as minhas modificações

**Comment by AlbertoMonteiro** [comment]
Só para completar a informação,

Segue o link da página inicial do GitHub ne época desse commit que o appveyor usou para gerar a versão:

https://github.com/BoletoNet/boletonet/tree/59aa24b407d3b43947e0fb39ad5bc2cbf8c54566

Da para ver que só tem 69 commits

Na época que eu fiz meu commit, o repositório já tinha 99 commits, como podemos ver no link https://github.com/BoletoNet/boletonet/tree/0c26d1a6fd5956f7131e5bf84917481cdf7e8ff4

**Comment by carloscds** [comment]
@AlbertoMonteiro Realmente o appveyor deu alguns problemas que agora foram normalizados. Você poderia gerar um novo Pr por favor com as mudanças ?

**Comment by AlbertoMonteiro** [comment]
@carloscds Acho que nem vai precisar, pois eu usei a ultima versão que o appveyor gerou la no MyGet, a versão 2.1.0.66 e a classe está lá novamente.
Acho que na próxima vez que você deployar no nuget, vai corrigir.

Obrigado!!
