### ISSUE TITLE
 Boleto.Net Asp.Net Core

### ISSUE THREAD

**Issue by mcorrearodrigues** [BoletoNet/boletonet#496]
Alguém já implementou o Boleto.Net no framework Asp.Net Core ?

**Comment by hdamasceno** [comment]
Estou iniciando os testes com o Asp.NET Core e o Boleto.NET conseguindo alguma coisa eu posto aqui.

Você conseguiu testar alguma coisa?

**Comment by mcorrearodrigues** [comment]
Bom dia.

Iniciei a conversão, mas tive problemas com System.Draw e gerar em PDF. A system Draw não tinha sido convertido para Cross, há alguns projetos beta desta dll no NuGet. É o PDF é uma dll proprietária que a versão free tb não está em core.  

Por fim, devido ao tempo eu acabei gerando uma api via framework 4.5 e chamo do core.

Qualquer novidade me avisa.

Abs

**Comment by lcmjunior** [comment]
Ola senhores boa noite. Alguem conseguiu utilizar o boleto.net no asp.net core ? vlw

**Comment by aubrym** [comment]
Existe sim um fork que está funcionando perfeitamente no .NET Core.
A versão atual do Boleto.Net não funciona.

O fork que está funcionando no .NET Core é o https://github.com/Tagliatti/BoletoNetCore

**Comment by cezarant** [comment]
@mcorrearodrigues é possível fechar a issue? Parece que o assunto foi encerrado.
