### ISSUE TITLE
Geração de Boletos em Lote

### ISSUE THREAD

**Issue by RicardoConceptOne** [BoletoNet/boletonet#499]
Boa tarde,

Estou com um problema ao tentar gerar vários boletos ao mesmo tempo.
Estou puxando os dados do boleto de um banco de dados e usando um foreach para o loop, porém sempre que ele vai gerar o SEGUNDO boleto ele dá o seguinte erro na hora de validar o boleto BoletoBancario.Boleto.Valida();

> Detalhes da Exceção: System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
> Linha 149:                            BoletoBancario.Boleto.Valida();

Segue o código que estou usando:

                        foreach (var boleto in sqlProcura)
                        {
                            Instrucao_Bradesco item = new Instrucao_Bradesco(9, 5);

                            //Carteiras 
                            Boleto b = new Boleto(boleto.DataVencimentoBoleto, Convert.ToDecimal(boleto.ValorBoleto), "09", boleto.NossoNumeroBoleto.ToString(), c);
                            b.NumeroDocumento = boleto.NumeroDocumentoBoleto.ToString();
                            b.DataVencimento = boleto.DataVencimentoBoleto;
                            b.LocalPagamento = "Até o vencimento, preferencialmente na rede Bradesco ou Bradesco Expresso";

                            b.Sacado = new Sacado(boleto.CpfSacadoBoleto, boleto.NomeSacadoBoleto);
                            b.Sacado.Endereco.End = boleto.EnderecoSacadoBoleto;
                            b.Sacado.Endereco.Bairro = boleto.BairroSacadoBoleto;
                            b.Sacado.Endereco.Cidade = boleto.CidadeSacadoBoleto;
                            b.Sacado.Endereco.CEP = boleto.CepSacadoBoleto;
                            b.Sacado.Endereco.UF = boleto.UfSacadoBoleto;

                            item.Descricao += " após " + item.QuantidadeDias.ToString() + " dias corridos do vencimento.";
                            b.Instrucoes.Add(item); //"Não Receber após o vencimento" 

                            Instrucao i = new Instrucao(237);
                            i.Descricao = "Pagável preferencialmente na Rede Bradesco ou Bradesco Expresso";
                            b.Instrucoes.Add(i);

                            b.EspecieDocumento = new EspecieDocumento(237, "12");

                            BoletoBancario.Boleto = b;
                            BoletoBancario.Boleto.Valida();

                            BoletoBancario.MostrarEnderecoCedente = true;

                            listBoletos.Add(BoletoBancario);
                        }

Alguém poderia me ajudar?

**Comment by eternoscav** [comment]
Boa noite Pessoal!

Tenho o banco Bradesco funcionando tanto boleto como Arquivo de Remessa,
mas precisei colocar algumas instruções e incluindo o sistema não consegue gerar,
alguém poderia me ajudar?Alguma sugestão.

Quando incluo no meu projeto o
"'Dim item As Instrucoes = New Instrucao_Bradesco(9,5)"
"b.Instrucoes.Add(item)"

Ele dá erro de Geração de arquivo de Remessa"

Obrigado.
