### ISSUE TITLE
Remessa Brasil 17-019 CNAB240

### ISSUE THREAD

**Issue by hericss** [BoletoNet/boletonet#500]
Olá pessoal,

estou com problemas na homologação do banco do brasil na carteira 17-019, onde o arquivo gerado foi aprovado no site de validação on-line, mas o gerente da agência está retornando o seguinte erro no sistema dele:

------------------------------------------------------------------------------
 Seq. - Registro - Ocor. Registro - Comando - Resp. Atual.
------------------------------------------------------------------------------
   - 015894 - 641-Reg.excl.-cpo '641-cmdo' inval.  - 999  - CBRPR001

Alguma sugestão?

**Comment by homerokzam** [comment]
Heric,

Como você fez essa validação on-line? Tem algum cadastro? É direto no gerenciador financeiro?

Obrigado,
Homero

**Comment by hericss** [comment]
Olá,

consegui utilizar pelo Firefox, pois tem que instalar os certificados, segue link:

[http://www.bb.com.br/pbb/pagina-inicial/aplicativos-bb#/](url)

**Comment by hericss** [comment]
Pessoal, sobre o assunto desta questão, favor desconsiderar... O convênio do cliente está cadastrado para a carteira 17 e a variação 027, o gerente do banco tinha me passado 17-019 :(
