### ISSUE TITLE
Criação de Boletos em Lote

### ISSUE THREAD

**Issue by RicardoConceptOne** [BoletoNet/boletonet#501]
Boa tarde,

estou com um problema ao gerar um pdf com mais de um boleto, estou usando a seguinte função
`new BoletoBancario().MontaBytesListaBoletosPDF(List, "Boletos Bancarios");`

porém quando passa por ela, o seguinte erro é retornado:
`System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.`

Não sei como resolver e estou com um prazo muito curto para entregar esse projeto, poderiam me ajudar?

Agradeço desde já

**Comment by hugofialho** [comment]
eu tive vários problemas com referencia de objeto, deixei de usar a dll compilada e adicionei o projeto ao meu
