### ISSUE TITLE
Documentação para geração de CNAB400 BB

### ISSUE THREAD

**Issue by homerokzam** [BoletoNet/boletonet#503]
Alguma documentação para saber quais as informações devemos preencher para que a geração de arquivo CNAB400 BB seja bem sucedida?

Obrigado.

**Comment by hericss** [comment]
Recomendo que verifique com a agência se realmente será no CNAB400, pois iniciei o trabalho e depois a agência me informou que deveria ser no CNAB240.

Neste link temos material do banco: 
[http://www.bb.com.br/pbb/pagina-inicial/aplicativos-bb#/](url)

**Comment by homerokzam** [comment]
Muito obrigado @hericss !

**Comment by cezarant** [comment]
@homerokzam tudo bem?  Você poderia fechar a issue?
