### ISSUE TITLE
Boleto CEF

### ISSUE THREAD

**Issue by cnascimento** [BoletoNet/boletonet#52]
O boleto da caixa está funcional? Na documentação vi que ele não se encontra implementado.

**Comment by Westfallx** [comment]
Está funcionando sim, eu já implementei em um cliente a 2 meses atrás e já foram mais de 3000 boletos na praça.
Ele tem um bug quando vc vai fazer geração de carnes, mas isso é para todos os bancos..
Ele pode repedir o mesmo código de barras para até 3 boletos.
Por exemplo na minha aplicação eu tipo uma remessa de carnes,  10 carnês, e cada carnê conteando 12 boletos.   ele estava duplicanco e até triplicando o código de barras
mas vou ver se essa semana eu subo uma versão com a correção pro pessoal dar uma olhada

**Comment by cnascimento** [comment]
Valho, muito obrigado pelo retorno. É bom saber que ele está funcional, os carnês não utilizar, preciso só do boleto mesmo não registrado.

**Comment by Westfallx** [comment]
então os carnes eu estou gerando sem registro.. se vc for gerar 1 por vez blz.. mas se for mais de 1 ai pode dar problemas.
