### ISSUE TITLE
Informativo/Extrato no topo da página

### ISSUE THREAD

**Issue by kelvindules** [BoletoNet/boletonet#548]
Olá. Gostaria de saber se o projeto já possui a possibilidade de inserir um informativo acima do boleto, na mesma página, pois não encontrei isso no MontaHtml. Se já existe poderia me apontar? Ex. de informativo na imagem referida abaixo:

![asd](https://user-images.githubusercontent.com/13211356/29220708-561a3830-7e92-11e7-8991-9fbb11bbd444.PNG)

Caso não exista, seria interessante para o projeto implementar essa funcionalidade?

**Comment by diegomodolo** [comment]
Bom dia Kelvin,

Eu desenvolvi isso há algum tempo e estou usando regularmente em alguns clientes.

Segue um exemplo básico:
if (grupoDemonstrativoCollection != null)
                                {
                                        boletoBancario.OcultarReciboSacado = true;
                                        boletoBancario.ExibirDemonstrativo = true;

                                        foreach (var grupo in grupoDemonstrativoCollection)
                                        {
                                                var grupoTemp = new BoletoNet.DemonstrativoValoresBoleto.GrupoDemonstrativo { Descricao = grupo.Descricao };

                                                foreach (var item in grupo.ItemDemonstrativoCollection)
                                                {
                                                         var itemTemp = new ItemDemonstrativo
                                                                                                 {
                                                                                                         Descricao = item.Descricao,
                                                                                                         Referencia = item.Referencia,
                                                                                                         Valor = item.Valor
                                                                                                 };

                                                        grupoTemp.Itens.Add(itemTemp);
                                                }

                                                boleto.Demonstrativos.Add(grupoTemp);
                                        }
                                }

Mas é basicamente assim:
Atribui a propriedade ExibirDemonstrativo = true, ai você adiciona os grupos e para cada grupo você adiciona os itens.

[cid:image002.png@01D294D4.C6D12AA0]

Diego Modolo Ribeiro

Néctar Informática Ltda.

Diretor Administrativo

+55 (064) 3611-5200

+55 (064) 99653-0351

Rua João José Fonseca, Quadra 80 Lotes 01,02 e 03
Setor Morada do Sol, Rio Verde, Goiás

diego.ribeiro@nectarnet.com.br<mailto:diego.ribeiro@nectarnet.com.br>

nectar.inf.br<http://nectar.inf.br/>



De: Kelvin Dias Dules [mailto:notifications@github.com]
Enviada em: sexta-feira, 11 de agosto de 2017 12:44
Para: BoletoNet/boletonet <boletonet@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [BoletoNet/boletonet] Informativo/Extrato no topo da página (#548)


Olá. Gostaria de saber se o projeto já possui a possibilidade de inserir um informativo acima do boleto, na mesma página, pois não encontrei isso no MontaHtml. Se já existe poderia me apontar? Ex. de informativo na imagem referida abaixo:

[asd]<https://user-images.githubusercontent.com/13211356/29220708-561a3830-7e92-11e7-8991-9fbb11bbd444.PNG>

Caso não exista, seria interessante para o projeto implementar essa funcionalidade?

**Comment by kelvindules** [comment]
Putz, não sei como deixei passar o .Demonstrativos. Obrigado @diegomodolo !
