### ISSUE TITLE
Gerar Remessa CNAB400 Bradesco - Erro Instrução

### ISSUE THREAD

**Issue by cetimarcelo** [BoletoNet/boletonet#560]
Boa tarde, 

Quando vou gerar remessa para o Bradesco, usando o CNAB400 está apresentando erro de tipos incompatives nessa linha de GerarDetalheRemessaCNAB400:

foreach (Instrucao_Bradesco instrucao in boleto.Instrucoes)

Diz que BoletoNet.Instrucao não pode ser convertido em BoletoNet.Instrucao_Bradesco.
Alguma solução?

**Comment by dieggop** [comment]
Brother, estou com problema similar, conseguisse resolver?

**Comment by cetimarcelo** [comment]
Bom dia @dieggop,

era um erro de minha parte, que em testes antigos funcionava, mas atualizei o Boleto.Net e ai começou a dar problemas quando fui realmente usar.
Eu tinha um código onde preparava o boleto tanto para impressão quanto para gerar arquivo de remessa que era assim:
```
 Boleto7 b7altera = os.FindObject<Boleto7>(CriteriaOperator.Parse("Oid = ?", b7.Oid));
 if (b7altera != null)
 {
        b7altera.DigitoNossoNumero = bb.Boleto.DigitoNossoNumero;
        foreach (IInstrucao inst in bb.Boleto.Instrucoes)
        {
               if (b7altera.Instrucoes == string.Empty)
               {
                      b7altera.Instrucoes = inst.Descricao;
                }
                else
                {
                       b7altera.Instrucoes += "\r\n" + inst.Descricao;
                 }
       }
  }
```

E alterei para isso:

```
 Boleto7 b7altera = os.FindObject<Boleto7>(CriteriaOperator.Parse("Oid = ?", b7.Oid));
 if (b7altera != null)
 {
       b7altera.DigitoNossoNumero = bb.Boleto.DigitoNossoNumero;
        b7altera.Instrucoes = bb.Boleto.Instrucoes.ToString();
 }

```

**Comment by dieggop** [comment]
Eu não estou conseguindo gerar a Guia de Remessa para os boletos do banco Bradesco. Ele ta dando pau sempre.  Estou com essa bronca, vê:

![image](https://user-images.githubusercontent.com/3966705/31011568-2421d792-a4e5-11e7-9dea-2bb668be719d.png)

**Comment by cetimarcelo** [comment]
Alguma coisa está nula ai, é necessário parar com o Debug nessa linha e ver o que está indo nulo e corrigir isso.

**Comment by dieggop** [comment]
Eu não consigo iniciar com o Debug, sempre inicio com o Visualizar No Chrome.

**Comment by cetimarcelo** [comment]
Então tenta criar um log ou algo assim em que possa ver os valores de todos os parâmetros onde está dando o erro. Se não tiver como isso é um problema mesmo.

**Comment by dieggop** [comment]
Deixa te aperriar novamente, sabes dizer quais os campos que ele pede para serem preechidos? e onde encontraria o RemessaCNAB240 implementado ?

**Comment by cetimarcelo** [comment]
Olha, tem que olhar toda documentação do banco, nela você tem todas as informações necessárias, quanto a CNAB240 existem novas regras e muitos bancos não irão aceitar mais, somente o CNAB400, consulte os banco para se informar melhor.

**Comment by dieggop** [comment]
Entendi! Valeu brother...  vou continuar tentando

**Comment by cetimarcelo** [comment]
Encerrando.
