### ISSUE TITLE
Carteira - Santander

### ISSUE THREAD

**Issue by PetrusJonas** [BoletoNet/boletonet#587]
Olá,

Tentei homologar o boleto do santander e recebi o seguinte retorno do banco:
_Favor informar 101- RCR (RÁPIDA COM REGISTRO)._

Pesquisando um pouco, vi que a nomenclatura da carteira foi alterada de ERC (Cobrança Simples Com Registro) para RCR (Cobrança Simples Rápida Com Registro). 
Por favor, vcs poderiam verificar isso?

**Comment by rafaelsgripp** [comment]
Bom Dia, 
Estou com a mesma solicitação do Santander, como você resolveu?

**Comment by PetrusJonas** [comment]
Bom dia.

Pra resolver o meu problema, eu peguei o código fonte do boletonet e alterei a nomenclatura no arquivo Carteira_Santander.cs

**Comment by rafaelsgripp** [comment]
Blz, Obrigado, vou fazer o mesmo

**Comment by cezarant** [comment]
@PetrusJonas tudo bem? Você poderia fechar a issue? Me parece que o assunto foi encerrado.
