### ISSUE TITLE
Erro LerArquivoRetorno ITAU CNAB 400

### ISSUE THREAD

**Issue by Yukibashiri** [BoletoNet/boletonet#593]
Boa tarde,
Estou tendo um problema, estou gerando a remessa, enviando para o banco, mas quando tento inserir o retorno na aplicação dá um erro falando que o formato é invalido. O código está logo a baixo.
Irei postar os erros nos comentários.

  [HttpPost]
        public ActionResult ImportarRetorno()
        {
            log = "";
            if (Session["funcionarioLogado"] != null)
            {
                if (Request.Files.Count > 0 && Request.Files["arquivo_retorno"] != null && Request.Files["arquivo_retorno"].FileName != "")
                {
                    ArquivoRetornoCNAB400 cnab400 = new ArquivoRetornoCNAB400();
                    Banco bancoItau = new Banco(341);
                    try
                    {
                        cnab400.LerArquivoRetorno(bancoItau, Request.Files["arquivo_retorno"].InputStream);
                    }
                    catch(Exception error)
                    {
                        cnab400 = null;
                        error.ToString();
                    }

**Comment by Yukibashiri** [comment]
![image](https://user-images.githubusercontent.com/14343036/31956992-f1fa4e48-b8cb-11e7-9343-e1e35b425a13.png)

**Comment by Yukibashiri** [comment]
01REMESSA01COBRANCA       012900327177        INTERNACIONAL TRAVESSIAS SALVA341BANCO ITAU SA  171017                                                                                                                                                                                                                                                                                                      000001
10220413924000127012900327177    000000000009                 000000090000000000000109                     I0100000009  20101700000000040003410000001N171017910000000000000002010170000000000000000000000000000000000000000221272590000181MINERACAO SPAZIO ALPHA CONCORD          AV ANTONIO CARLOS MAGALHAES SALA 101, 21CENTRO      48700000SERRINHA       BA                                  20101700 000002
10220413924000127012900327177    000000000010                 000000100000000000000109                     I0100000010  20101700000000040003410000001N171017910000000000000002010170000000000000000000000000000000000000000219142004000132Elienice Santos Souza                   RUA LALITA COSTA 192, APT 104 RESEDA VILVILA LAURA  40255265SALVADOR       BA                                  20101700 000003
10220413924000127012900327177    000000000011                 000000110000000000000109                     I0100000011  20101700000000040003410000001N171017910000000000000002010170000000000000000000000000000000000000000215155336000281Associacao Nacional de Instruc          RUA LEOVIGILDO FILGUEIRAS 683, 683      GARCIA      40100000SALVADOR       BA                                  20101700 000004
10220413924000127012900327177    000000000012                 000000120000000000000109                     I0100000012  20101700000000040003410000001N171017910000000000000002010170000000000000000000000000000000000000000221260387000195Apeletrica                              TRAV. SILVEIRA , 74                     FAZENDA GRAN40353560SALVADOR       BA                                  20101700 000005
10220413924000127012900327177    000000000013                 000000130000000000000109                     I0100000013  20101700000000250003410000001N171017910000000000000002010170000000000000000000000000000000000000000214549315000105Federacao dos Pescadores e Aqu          AVENIDA ESTADOS UNIDOS EDIFICIO CERVANTECOMERCIO    40010020SALVADOR       BA                                  20101700 000006
10220413924000127012900327177    000000000014                 000000140000000000000109                     I0100000014  20101700000000230003410000001N171017910000000000000002010170000000000000000000000000000000000000000221260387000195Apeletrica                              TRAV. SILVEIRA , 74                     FAZENDA GRAN40353560SALVADOR       BA                                  20101700 000007
9                                                                                                                                                                                                                                                                                                                                                                                                         000008

**Comment by leticiacnavarro** [comment]
Olá, estou com um erro similar. Poderia me falar o que fez para solucionar?

**Comment by Yukibashiri** [comment]
Olá Letícia, infelizmente não consegui solucionar, lembro de ter anotado aqui exatamente o problema encontrado, contudo não possuía uma das bibliotecas necessárias (Utils) e não consegui aplicar a solução. 
O erro se encontra na leitura  dos detalhes, quando ele pega o arquivo e "quebra" as partes definindo quem é quem, nesse momento o numero de caracteres está errado, ele está pegando menos ou mais que deveria e por isso o erro ocorre. 
A solução é colocar o tamanho certo da string que ele espera para decodificar, contudo não apliquei a solução devido a outras demandas com maior urgência passarem na frente.

**Comment by leticiacnavarro** [comment]
Entendi... Mas isso aconteceu apenas nesse banco ou em outros também?

**Comment by Yukibashiri** [comment]
Não utilizamos outros bancos, então não posso te responder essa pergunta.
