### ISSUE TITLE
Erro ao validar layout arquivo remessa itau cnab 400 com multa

### ISSUE THREAD

**Issue by mateushideaki** [BoletoNet/boletonet#610]
Estou tendo problemas para validar o arquivo gerado pelo boletonet no Itaú quando a multa é especificada, gerando a parte opcional do complemento, localizado na página 9 do manual (http://download.itau.com.br/bankline/layout_cobranca_400bytes_cnab_itau.pdf).

O erro retornado pelo validador de layout no ambiente de testes do Itaú é:

**Layout:
 Registro: detalhe
 Linha: 2
 Posição 001 - Campo: Identificação do Registro - Conteúdo fixo difere do esperado. (2)** 

A linha gerada pelo boletonet para especificar a multa tem o seguinte começo, que por sinal, segue exatamente o especificado pelo layout do itaú:

**22301120170000000000200**

além disso, só é especificado o número sequencial no final da linha.

Quando a multa não é especificada no código, ou a linha é removida manualmente, o problema desaparece. 

Caso alguém tenha passado por problema similar e saiba como resolver, agradeço muito se puder ajudar.

**Comment by hugofialho** [comment]
Estou com o mesmo problema @mateushideaki, o BoletoNet gera duas linhas com o registro número 2, uma com o valor da multa e outra com as mensagens das instruções do boleto. Verifiquei o manual do itau e não encontrei nada referente a esse segundo registro das mensagens. Vou fazer um teste removendo esse segundo registro e te mantenho informado.

**Comment by mateushideaki** [comment]
Olá Hugo, o que eu fiz foi não preencher as instruções na remessa. Mandei os arquivos para o banco e foi homologado sem problemas.

**Comment by fllsilva** [comment]
Olá @mateushideaki  , na verdade o que você fez foi abrir mão do seu direito de cobrança da multa por atraso ao remover a informação, em detrimento de uma instituição bancária que até onde pude ver está a mais de 1 ano e meio (hoje é 21/08/2018) som esse problema e não providenciou uma solução para o mesmo.

**Comment by cezarant** [comment]
@mateushideaki  tudo bem? Poderia encerrar a issue por favor?

**Comment by mateushideaki** [comment]
@cezarant ok, fechando.
