### ISSUE TITLE
Retorno CNAB 400

### ISSUE THREAD

**Issue by leticiacnavarro** [BoletoNet/boletonet#611]
Estou fazendo um programa que lê arquivos retorno utilizando a DLL do boletonet. Os arquivos com CNAB 240 lêem direitinho, mas os de CNAB400 dão erro " System.Exception: Erro ao ler header do arquivo de RETORNO / CNAB 400."
Já tentei com arquivos do Itaú, banco do brasil, sicoob, todos dão o mesmo erro. 
O código que utilizo abaixo, para verificar e setar.
![cod](https://user-images.githubusercontent.com/33257158/33321746-eb4482ee-d42d-11e7-9cc0-d2aeb87b5286.png)

**Comment by mateushideaki** [comment]
Tente criar um outro fileStream para ler o arquivo de retorno, acredito que o comando sr.Readline() usando o mesmo fileStream possa interferir.

**Comment by leticiacnavarro** [comment]
Funcionou agora, muito obrigada!

**Comment by mateushideaki** [comment]
Por nada! :)
