### ISSUE TITLE
Erro ao referenciar o projeto Boleto.Net em outra solução

### ISSUE THREAD

**Issue by marcus2vinicius** [BoletoNet/boletonet#614]
Este é o erro apresentado ao compoilar

`Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Erro		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\Users\marcus\Documents\Projects\apiboleto\boletoapi\\.nuget\NuGet.targets.	Boleto.Net	C:\Users\marcus\source\repos\boletonet\src\Boleto.Net\Boleto.Net.csproj	349	
`

Antigamente eu apenas o referenciava, fazia as edições e depois compilava toda a solução e funcionava.
Agora estou usando o visual studio 2017, não sei se faltei configurar algo.
Alguém poderia me ajudar ?

**Comment by marcus2vinicius** [comment]
A ultima versão do VS que usei foi a 2013, então acredito que o problema seja a nova maneira de tratar os pacotes nuget.

**Comment by marcus2vinicius** [comment]
Consegui utilizando este post

https://chrismay.org/2015/01/07/nuget-switching-from-enable-package-restore-to-automatic-package-restore/

Porém tive que fazer modificações `Boleto.Net.csproj` que não achei interessante pois os usuário de versões anteriores a 2015 talvez não consigam rodar o projeto.
Se alguém souber de uma solução melhor informe aqui.

**Comment by cezarant** [comment]
@marcus2vinicius  poderia fechar a Issue? Parece que o assunto foi resolvido.
