### ISSUE TITLE
Dúvida boleto Itaú sem cobrança de juros

### ISSUE THREAD

**Issue by brunobueno** [BoletoNet/boletonet#641]
Estou dando manutenção na rotina de boletos aqui na empresa e peguei o bonde andando. Estamos com o seguinte problema: os boletos que estão sendo gerados não podem cobrar juros nem protestar.

Para isso seria só colocar as instruções no arquivo de remessa?

Pelo que vi no arquivo de instruções do Itaú para não protestar o código é o 10, e para não cobrar juros o código é o 47.

Mais algumas informações: estou usando a carteira 109.

Gerei alguns boletos e enviei desta maneira mas o Itaú rejeitou.

**Comment by brunobueno** [comment]
Mais algumas informações: estou usando a carteira 109.

Gerei alguns boletos e enviei desta maneira mas o Itaú rejeitou.

**Comment by rodolfoghi** [comment]
Aqui temos utilizado assim:
```
var instrucaoItau = new Instrucao_Itau((int)EnumInstrucoes_Itau.JurosdeMora, (double)valorJuroDiario, AbstractInstrucao.EnumTipoValor.Reais);
boleto.Instrucoes.Add(instrucaoItau);
boleto.JurosMora = valorJuroDiario;
```
```
var instrucaoItau = new Instrucao_Itau((int)EnumInstrucoes_Itau.ProtestarAposNDiasCorridos, numeroDiasProtestar);
boleto.Instrucoes.Add(instrucaoItau);
```

**Comment by marciuspimentel** [comment]
Cara, aqui na empresa usamos itau como Banco Correspondente.
Nossa transmissão é feita com o Safra, só que o Boleto é ITAU (Carteira 109), no começo tivemos uma certa dificuldade com protestos e cobrança de Juros.
Mesmo mandando a instrução para não cobrar juros nem protestar, o sistema deles não acatavam a instrução.
Isso foi resolvido via acordo comercial mesmo, o Gerente da nossa conta no Safra em contato com a área responsável do Itau removeram essa "configuração"  e desde então nossos boletos não são mais protestados ,nem cobrado juros.
