### ISSUE TITLE
Erro ao gerar arquivo remessa Banco Brasil

### ISSUE THREAD

**Issue by Malavos** [BoletoNet/boletonet#65]
[Esse erro já foi reportado no codeplex.](https://boletonet.codeplex.com/discussions/632700)
-----------------------
Estou conseguindo gerar um boleto do banco brasil, mas não consigo gerar Arquivo Remessa. 

Erro durante a geração do HEADER DO LOTE do arquivo de REMESSA. 

Algum exemplo de código ou algo a ter especial atenção? 

Obrigado!
------------------------
Esse erro foi reportado no codeplex por outro usuário, mas em nosso sistemas, tivemos o mesmo problema com o arquivo remessa, com a mesma exceção. Podem nos ajudar?

**Comment by carloscds** [comment]
@Malavos Poderia dar mais detalhes do erro ? Alguma mensagem ?

**Comment by Malavos** [comment]
@carloscds Olá, Carlos, eu anexei uma imagem do stack trace:

![erro_arquivo_remessa_bb](https://cloud.githubusercontent.com/assets/5607619/9258866/464b3a6e-41d4-11e5-853d-2e32d3cd9b27.PNG)

Mais detalhes aqui:

Erro ao gerar arquivo remessa.
Erro durante a geração do HEADER DO LOTE do arquivo de REMESSA.
Erro durante a geração do registro HEADER do arquivo de REMESSA.
em BoletoNet.Banco.GerarHeaderLoteRemessa(String numeroConvenio, Cedente cedente, Int32 numeroArquivoRemessa, TipoArquivo tipoArquivo)
em BoletoNet.ArquivoRemessaCNAB240.GerarArquivoRemessa(String numeroConvenio, IBanco banco, Cedente cedente, Boletos boletos, Stream arquivo,
Int32 numeroArquivoRemessa)

**Comment by carloscds** [comment]
@Malavos Ok, mas o ideal é você baixar o código e anexar ao seu projeto. Roda em modo debug e veja o erro. Isto pode ser falta de algum parametro de configuração.

**Comment by Malavos** [comment]
@carloscds  Vamos verificar e testar aqui e qualquer coisa respondo aqui, okay? Vamos deixar essa issue aberta por enquanto.

Não sou eu quem está delegado com essa tarefa, apenas estou postando aqui porque já tenho perfilo no github...  Enfim, obrigado pela breve resposta!

**Comment by Malavos** [comment]
@carloscds  baixamos o projeto de exemplo aqui, e ele chega a gerar o arquivo de remessa do Banco do Brasil; Mas o arquivo vem vazio.

Se você executar o windows form e tentar gerar o mesmo a partir dali, ele nem chama o evento de geração de remessa. Ele para ali, seja 400 ou 240.

**Comment by carloscds** [comment]
@Malavos Você configurou a carteira e o convenio ?

**Comment by Malavos** [comment]
@carloscds  Carlos, obrigado pela ajuda! Deu certo com o layout CNAB400.
Mas não conseguimos gerar com o 240, que gera o erro descrito na issue, mesmo com a carteira e convênio.

Se você souber o que pode ser no caso do 240, por favor, me informe.

**Comment by Malavos** [comment]
O problema foi resolvido, já conseguimos gerar com o layout 400, mediante a carteira e o convênio.

**Comment by carloscds** [comment]
@Malavos Excelente!
