### ISSUE TITLE
Arquivo de remessa pagamentos

### ISSUE THREAD

**Issue by willsrosa** [BoletoNet/boletonet#652]
A Biblioteca boleto.net gera arquivos de remessa de pagamentos para fornecedores ?

**Comment by nikolasmagno** [comment]
também gostaria de saber isto! alguem ajuda ai plz?

**Comment by carloscds** [comment]
@willsrosa No nomento não. Gostaria de implementar ?

**Comment by willsrosa** [comment]
Bom dia Carlos, fiz a integração com a remessa de pagamentos para o banco
Santander se alguém precisar de algo ou quiser.

2018-06-26 21:20 GMT-03:00 Carlos dos Santos <notifications@github.com>:

**Comment by carloscds** [comment]
@willsrosa manda um PR.

**Comment by willsrosa** [comment]
não entendi o que precisa.

2018-06-27 9:44 GMT-03:00 Carlos dos Santos <notifications@github.com>:

**Comment by carloscds** [comment]
@willsrosa Se você fez o pagamento, por quê nao envia para o projeto do boletoNet ?

**Comment by willsrosa** [comment]
eu fiz parametrizado no meu sistema mais posso fazer a implantação para o
boleto.net vou adaptar e subo para ajudar os companheiros.

2018-06-27 10:18 GMT-03:00 Carlos dos Santos <notifications@github.com>:

**Comment by carloscds** [comment]
@willsrosa Show!

**Comment by willsrosa** [comment]
resolvi o problema mais ainda não tive tempo de implementar no projeto.net se alguém precisar de ajuda ou quiser me ajudar a implementar estou a disposição
