### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by diegodariolli** [BoletoNet/boletonet#653]
Boa tarde a todos,

Sou novo no github, fiz algumas alterações no boletoNet que acredito serem persistentes e gostaria de disponibilizá-las para os responsáveis darem uma olhada, porém estou meio perdido aqui ainda.

Abraços.

**Comment by carloscds** [comment]
@diegodariolli Me manda msg no blog que te ajudo: www.carloscds.net

**Comment by diegodariolli** [comment]
O campo do captcha está desabilitado.

**Comment by carloscds** [comment]
@diegodariolli Resolvido, manda lá!

**Comment by diegodariolli** [comment]
Mandei
