### ISSUE TITLE
Conciliação Bancaria 

### ISSUE THREAD

**Issue by dpukata** [BoletoNet/boletonet#658]
Olá a todos.

Gostaria de saber se existe algo a respeito de importação de conciliação bancaria fluxo de importação.
Obs.: Essa importação seria o retorno do extrato bancário enviado no formata .ofx para importação no sistema.

Já viram algo assim aqui na dll?

Grato

**Comment by carloscds** [comment]
@dpukata Hoje nao tem esta funcionalidade.

**Comment by dpukata** [comment]
@carloscds Obrigado
