### ISSUE TITLE
Erro ao gerar remessa do Bradesco

### ISSUE THREAD

**Issue by Malavos** [BoletoNet/boletonet#66]
Boa tarde,

Ao gerar o arquivo de remessa, encontro o seguinte erro:

No layout CNAB240, este erro é gerado:
Erro durante a geração do registro HEADER do arquivo de REMESSA.

E  no layout CNAB400, já este erro ocorre:
Erro durante a geração do DETALHE arquivo de REMESSA.

![erro_remessa_bradesco](https://cloud.githubusercontent.com/assets/5607619/9312205/a763e70e-44f1-11e5-84ae-b68e0e7ba163.PNG)

Segue acima a massa de testes que utilizamos para reproduzir o erro.

**Comment by carloscds** [comment]
@Malavos Você validou os dados do banco ?

**Comment by Malavos** [comment]
@carloscds  Você está falando sobre ao método ArquivoValidarArquivoRemessa? Se sim, sim, estamos validando.

**Comment by Malavos** [comment]
@carloscds  Segue o nosso código de como estamos tentando gerar o arquivo:

```
public void GeraArquivoRemessaCNAB400(IBanco banco, Cedente cedente, Boletos boletos)
       {
           try
           {
               var dir = ConfigurationManager.AppSettings["DiretorioArquivoRemessa"];

               if (!Directory.Exists(dir)) { Directory.CreateDirectory(dir); }

               Stream arquivoRemessa = new FileStream(string.Format(@"{0}\RemessaCNAB400{1}{2}.rem",
               dir, banco.Nome, DateTime.Now.ToString("ddMMyyyyHHmmss")),
               FileMode.Create, FileAccess.ReadWrite);

               ArquivoRemessa arquivo = new ArquivoRemessa(TipoArquivo.CNAB400);
               //Valida a Remessa Correspondentes antes de Gerar a mesma...
               string vMsgRetorno = string.Empty;
               bool vValouOK = arquivo.ValidarArquivoRemessa(cedente.Convenio.ToString(), banco, cedente, boletos, 1, out vMsgRetorno);
               if (!vValouOK)
               {
                   throw new Exception(String.Concat("Foram localizados inconsistências na validação da remessa!", Environment.NewLine, vMsgRetorno));
               }

               arquivo.GerarArquivoRemessa(cedente.Convenio.ToString(), banco, cedente, boletos, arquivoRemessa, 1);

           }
           catch (Exception ex)
           {
               throw new Exception(string.Format("Erro ao gerar arquivo remessa. {0}", ex.Message));
           }
       }
```

**Comment by carloscds** [comment]
@Malavos não, estou perguntando sobre os dados para a cobrança, da mesma maneira que ocorreu com o BB.

**Comment by Malavos** [comment]
Estamos passando o convênio 0, e a carteira 06 (sem registro).
E sim, esses dois foram realmente o problema com o BB.

Esquecemos de mais algum detalhe? Mesmo com essas duas informações, que já estávamos repassando, o problema ocorre.

**Comment by carloscds** [comment]
@Malavos Cada banco tem uma particularidade, já deu uma olhada no manual da cobrança do banco ?

**Comment by Malavos** [comment]
@carloscds  Oi Carlos, no caso da issue foi resolvido da seguinte forma (fica para futura referência caso alguém tenha o mesmo problema).

O que mudou no Bradesco foi o nosso número (talvez outros bancos também). O nosso número pode conter letras, mas para geração do arquivo, o mesmo não pode receber caracteres. Então formatamos o valor antes da geração da remessa.

Obrigado pela ajuda, e fica aí documentado para futura referência.

**Comment by carloscds** [comment]
@Malavos Obrigado pelo retorno!

**Comment by joelcc** [comment]
Bom dia @Malavos , tem como vc me ajudar? Pois está dando o mesmo erro que apareceu no seu para o Bradesco más o Nosso numero só tem valor numeral.

**Comment by Malavos** [comment]
@joelcc  nossa, isso já faz muitoooooo tempo. Eu não lembro de cabeça :| Tem como você debugar?

**Comment by joelcc** [comment]
O problema está ai @Malavos, eu só tenho instalado no projeto a dll. Más obrigado pelo retorno.
