### ISSUE TITLE
Quando Leio um Arquivo Retorno está aparecendo vários MessageBox. Tem como tirar?

### ISSUE THREAD

**Issue by fabiohcnobre** [BoletoNet/boletonet#663]
Quando do 
`  cnab400.LerArquivoRetorno(bco, openFileDialog.OpenFile()); `
esta aparecendo vários MessageBox.
Tem como tirar?

**Comment by fabiohcnobre** [comment]
O problema que eu também não sei onde estão vindo esse MessageBox. Já deu uma olhada.

**Comment by carloscds** [comment]
@fabiohcnobre Veja se não está no seu código, pois no componente do boleto nao tem messagebox. No seu exemplo acima, existe a janela o OpenFileDialog()

**Comment by fabiohcnobre** [comment]
O OpenFileDialog vem do System.Windows e o mesmo não mostra nenhuma Messagebox. E outra ele esta mostrando linha por linha do detalhe do arquivo de remessa. Parece que esta dentro de um while.

**Comment by carloscds** [comment]
@fabiohcnobre Eu acabei de olhar o código do boleto e nao tem messagebox lá. A versao que vc esta usando é a que está no git ?

**Comment by fabiohcnobre** [comment]
Sim, versão 2.1.0.626

**Comment by fabiohcnobre** [comment]
@carloscds 
Achei ->
Eu copiei o codigo do Main.cs 
https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net.Arquivo/Main.cs

O MessagerBox esta nessa função:
`     cnab400.LinhaDeArquivoLida += new EventHandler<LinhaDeArquivoLidaArgs>(Cnab400_LinhaDeArquivoLida);`

Onde que ->
```
       void Cnab400_LinhaDeArquivoLida(object sender, LinhaDeArquivoLidaArgs e)
        {
           MessageBox.Show(e.Linha);
        }

```

Tirando essa função parrou de ler linha por linha.
Obrigado!!!! 😀

**Comment by carloscds** [comment]
@fabiohcnobre ok. Manda um PR.
