### ISSUE TITLE
Arquivo de Remessa - Sicoob

### ISSUE THREAD

**Issue by fabiojmj** [BoletoNet/boletonet#672]
Pessoal, boa tarde, estou trabalhando na criação do arquivo de remessa para o Sicoob. 
Estou precisando de ajuda para gera-lo. Alguém que tenha conseguido pode me ajudar?

**Comment by rodolfoghi** [comment]
Qual seria a sua dúvida?

**Comment by rlrpara** [comment]
Qual a dúvida?

**Comment by FabioDlink** [comment]
@fabiojmj Conseguiu gerar a remessa do sicoob?

**Comment by eternoscav** [comment]
Pessoal alguém ae conseguiu gerar o arquivo de Remessa 240 para o Sicoob pela dll.
Obrigado.

**Comment by carloscds** [comment]
@eternoscav vejam este exemplo: https://gist.github.com/guigomesa/fdd6491f7875c8123e5a16c0deb8441f

**Comment by eternoscav** [comment]
Farei mais testes, qualquer coisa volto aqui para comentar novamente.
Obrigado.

**Comment by eternoscav** [comment]
Boa noite!
 
Fiz os testes porém sem sucesso, por acaso não teria mas nenhum exemplo , consigo gerar o boleto mas o arquivo de remessa está bem complicado.

Obrigado.

**Comment by carloscds** [comment]
@eternoscav Passe mais detalhes do problema

**Comment by eternoscav** [comment]
Carlos consegui resolver, na issue https://github.com/BoletoNet/boletonet/issues/636#issuecomment-409033629.

Mas obrigado por tentar ajudar.
