### ISSUE TITLE
Gerar arquivo de remessa banco caixa layout cnab 240

### ISSUE THREAD

**Issue by robsonsilvar** [BoletoNet/boletonet#680]
Estou recebendo erro de null reference ao chamar o metodo "ArquivoRemessa.ValidarArquivoRemessa" mas nao tenho nenhuma pista de que campo está nulo ou se realmente é algum campo. Alguem consegue me ajudar? A pilha é essa:

[NullReferenceException: Referência de objeto não definida para uma instância de um objeto.]
   BoletoNet.Banco_Caixa.ValidarRemessaCNAB240(String numeroConvenio, IBanco banco, Cedente cedente, Boletos boletos, Int32 numeroArquivoRemessa, String& mensagem) +320
   BoletoNet.Banco_Caixa.ValidarRemessa(TipoArquivo tipoArquivo, String numeroConvenio, IBanco banco, Cedente cedente, Boletos boletos, Int32 numeroArquivoRemessa, String& mensagem) +63
   BoletoNet.Banco.ValidarRemessa(TipoArquivo tipoArquivo, String numeroConvenio, IBanco banco, Cedente cedente, Boletos boletos, Int32 numeroArquivoRemessa, String& mensagem) +44

[Exception: Erro durante a validação do arquivo de REMESSA.]
   BoletoNet.AbstractArquivoRemessa.ValidarArquivoRemessa(String numeroConvenio, IBanco banco, Cedente cedente, Boletos boletos, Int32 numeroArquivoRemessa, String& mensagem) +52

**Comment by rodolfoghi** [comment]
Consegue fazer debug? Se você referencia a DLL no seu projeto, pode compilar ela em modo debug, executar o seu projeto em release e depois fazer attach do Boleto.Net no processo do seu aplicativo, daí é só colocar um breakpoint no método ValidarRemessaCNAB240.

Se por algum motivo não consegue fazer debug, dá uma conferida se você está preenchendo todas as propriedades utilizadas, vide linha 708 da classe [Banco_Caixa](https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net/Banco/Banco_Caixa.cs).

**Comment by robsonsilvar** [comment]
Opa @rodolfoghi, resolvido!
Para descobrir, baixei o codigo do projeto do Boletonet e a dll e o pdb, coloquei na bin e consegui entrar nos detalhes do metodo. 
Vlw!
