### ISSUE TITLE
Boletos Registrados

### ISSUE THREAD

**Issue by ericvalenzi** [BoletoNet/boletonet#681]
Boa Noite,

Descobri o BoletoNet agora, estou implementando a geração no meu Sistema, gostaria de saber dos Bancos Homologados e se são Boletos Registrados.
O WIKI ta bem desatualizado então não me baseei por ele se alguém puder responder, e ajudarei no desenvolvimento como Puder, tenho no Delphi quase todos Homologados, mas como estou migrando pro ASP.NET não queria refazer tudo.

**Comment by rodolfoghi** [comment]
Utilizamos com registro e geração de arquivo CNAB400 nos seguintes bancos. Obs: O Boleto.Net suporta outros bancos e também geração de arquivo CNAB240.

- CAIXA_ECONOMICA_FEDERAL
- BANCO_DO_BRASIL
- BRADESCO
- ITAU
- SANTANDER
- SICREDI
- BANRISUL
- SICOOB
- DAYCOVAL
- BANESTES
- CECRED

**Comment by ericvalenzi** [comment]
Rodolfo Obrigado pela Resposta estarei analisando o componente junto a minha gerencia mas planejo implentar ele mesmo em nosso sistema pelo que me disse irá supir nossas necessidades

**Comment by ericvalenzi** [comment]
> @ericvalenzi poderia fechar a Issue? Parece que o assunto foi resolvido.

Fechando Cezarnt
