### ISSUE TITLE
Imagens quebradas na geração do Boleto

### ISSUE THREAD

**Issue by mpghelli** [BoletoNet/boletonet#684]
Olá. Tenho uma aplicação asp.net mvc, onde uso o Boleto.Net para geração de boletos.

Ele está gerando o boleto corretamente no Método MontaHtml(), porém as imagens ficam quebradas.

Percebi que o componente grava as imagens em uma pasta temporária. E minha aplicação não consegue acessar esta pasta, dando o seguinte erro no console do browser:

Not allowed to load local resource: file:///C:/Windows/TEMP/BoletoNetBarra.gif

É possível alterar o caminho da pasta onde as imagens são salvas, para que sejam salvas no próprio diretório da aplicação? Ou obrigatoriamente tenho que dar permissão à pasta C:/Windows/TEMP/ para o usuário da aplicação?

Grato

**Comment by guiadevoo** [comment]
Utilize o método MontaHtmlEmbedded, assim as imagens são incluídas no HTML em formato de dados e não como link para arquivo.

**Comment by mpghelli** [comment]
É isso mesmo. Obrigado!
