### ISSUE TITLE
Texto especifico no boleto da Caixa

### ISSUE THREAD

**Issue by robsonsilvar** [BoletoNet/boletonet#691]
Estou gerando boleto da Caixa e foi validado que preciso inserir um texto especifico da caixa num quadro que nao é o de instruções. Alguem sabe como coloco esse texto? Segue imagem do modelo enviado pela Caixa: https://drive.google.com/file/d/1ykMLTU4d8-cIGyHh1ahHHVeDgl1hPDUr/view?usp=sharing

**Comment by ivanteles** [comment]
Eu passei por isso, mas comigo pediram pra por nas instruções e foi homologado

**Comment by robsonsilvar** [comment]
Resolvi dessa forma tb e atualizando a DLL. Obrigado!
