### ISSUE TITLE
Erro Geração Boleto Caixa!

### ISSUE THREAD

**Issue by eternoscav** [BoletoNet/boletonet#700]
Pessoal estou com o problema na geração do Boleto da Caixa, o que posso estar passando errado.
Segue o Código em VB:

  Case 104 '#3544

                        boletoBancario = New BoletoBancario()
                        boletoBancario.CodigoBanco = 104
                        boletoBancario.MostrarEnderecoCedente = True
                        'DateTime(vencimento = New DateTime(2016, 11, 15))

                        Dim c1 As Cedente = New Cedente("11.111.111/0001-11", "Nome do Cedente", "1111", "1111", "1") ' VERIFICAR
                        Dim codigo As String = "053976"
                        c1.Codigo = codigo 'VERIFICAR
                        c1.DigitoCedente = 7 'VERIFICAR
                        c1.Carteira = "24"
                        b = New Boleto(vencimento, 30, carteira, nosso, c1)
                        b.NumeroDocumento = "24000000000000001"
                        b.TipoModalidade = "01" 'VERIFICAR
                        b.NumeroParcela = 1 'VERIFICAR
                        b.EspecieDocumento = New EspecieDocumento_Caixa("1")

                        Dim CendenteEndereco As Endereco = New Endereco()
                        CendenteEndereco.End = "Endereço do cedente"
                        CendenteEndereco.Bairro = "Bairro"
                        CendenteEndereco.Cidade = "Cidade"
                        CendenteEndereco.CEP = "14700-000"
                        CendenteEndereco.UF = "SP"
                        b.Cedente.Endereco = CendenteEndereco

                        b.Sacado = New Sacado("000.000.000-00", "Nome do seu Cliente")
                        b.Sacado.Endereco.End = "Endereço do seu Cliente"
                        b.Sacado.Endereco.Bairro = "Bairro"
                        b.Sacado.Endereco.Cidade = "Cidade"
                        b.Sacado.Endereco.CEP = "14700-000"
                        b.Sacado.Endereco.UF = "SP"
                        'b.Sacado.Endereco.Logradouro = "RUA"
                        b.Sacado.Endereco.Numero = "123" 'VERIFICAR

                        boletoBancario.Boleto = b
                        boletoBancario.Boleto.Valida()
                        'Boletos.Add(boletoBancario)

Ele me da o o seguinte erro: 
"Nosso número inválido. Para Caixa Econômica - SIGCB carteira rápida, o nosso número deve conter 17 caracteres"

Obrigado

**Comment by eternoscav** [comment]
Complementando:
        Public nosso As String = "24000000000000001"
        Public carteira As String = "SR"

**Comment by ivanteles** [comment]
Carteira sem registro SR, não são mais aceitas...

**Comment by cezarant** [comment]
@eternoscav o problema foi resolvido?

**Comment by eternoscav** [comment]
Sim
