### ISSUE TITLE
Novo logo AILOS 085 (antigo CECRED) e demais imagens otimizadas

### ISSUE THREAD

**Issue by guiadevoo** [BoletoNet/boletonet#707]
O sistema CECRED (085) mudou de nome para AILOS, 
estou anexando a imagem atualizada e demais dos outros bancos otimizadas, 
na minha compilação a DLL passou de 1.4M para 839Kb

[Imagens.zip](https://github.com/BoletoNet/boletonet/files/2275552/Imagens.zip)

**Comment by guiadevoo** [comment]
O local de pagamento foi alterado para:
boleto.LocalPagamento = "Pagar preferencialmente nas cooperativas do Sistema AILOS.";

**Comment by carloscds** [comment]
@guiadevoo Mande um PR por favor.

**Comment by guiadevoo** [comment]
Olá Carlos, já mandei, mas bagunçõu meus arquivos aqui, acabei tendo que ajustar manualmente,
no momento estou aguardando a AILOS retornar com a aprovação dos boletos e Remessa,

**Comment by carloscds** [comment]
@guiadevoo Se precisar de ajuda com o PR me avise ok!

**Comment by guiadevoo** [comment]
AILOS OK, so configurei o convênio errado e mandaram corrigir, mas ta aprovado o layot com o novo novo. Se puder me ajudar com o PR fico grato, fiquei com medo de ter bagunçado o repositorio. Pode me chamar @guiadevoo

**Comment by carloscds** [comment]
@guiadevoo Faz um contato pelo meu blog: www.carloscds.net
