### ISSUE TITLE
Usar a lib Boleto.Net para o novo padrão de envio

### ISSUE THREAD

**Issue by leandrossantos** [BoletoNet/boletonet#709]
Gostaria de saber se tem como usar a lib Boleto.Net para o novo padrão de envio dos bancos via JSON/WebService.

**Comment by carloscds** [comment]
@leandrossantos Exite uma issue falando disto: #306

**Comment by cezarant** [comment]
@leandrossantos  poderia fechar a Issue? Parece que o assunto foi resolvido.
