### ISSUE TITLE
Pedido de Correção no Detalhe do Arquivo de Remessa Bradesco!!

### ISSUE THREAD

**Issue by eternoscav** [BoletoNet/boletonet#714]
Alguém poderia por favor corrigir essa linha, fiz as alterações no fonte e deu certo.
No Banco Bradesco ao incluir o código de protesto, ao gerar o arquivo de remessa não estava trazendo a quantidade de dias. Obrigado

Código Antigo:
      case EnumInstrucoes_Bradesco.Protestar:
           vInstrucao1 = "06"; //Indicar o código “06” - (Protesto)
           vInstrucao2 = "00; 
           break;

Código Novo:
      case EnumInstrucoes_Bradesco.Protestar:
           vInstrucao1 = "06"; //Indicar o código “06” - (Protesto)
           vInstrucao2 = Utils.FitStringLength(instrucao.QuantidadeDias.ToString(), 2, 2, '0', 0, true, true, true);
           break;

**Comment by cezarant** [comment]
@eternoscav  poderia fechar a Issue? Parece que o assunto foi resolvido.
