### ISSUE TITLE
Registro de cobrança

### ISSUE THREAD

**Issue by jetdev** [BoletoNet/boletonet#72]
Com a normativa do BCB sobre a obrigatoriedade do registro de boletos, estamos passando por alguns problemas. A normativa obriga que todos os convênios abertos a partir de Julho desde ano sejam com registro. Em alguns poucos casos, por conta do volume de boletos, conseguimos que o banco abrisse mão do registro. 

Quando temos que registrar, o sacado só consegue pagar o boleto no banco emissor após o registro, e isso limita muito o uso de boleto bancário. 

* Imagina que você emita um boleto agora e coloque a data mínima para pagamento amanhã. 

Alguém mais está tendo este problema?

**Comment by carloscds** [comment]
Isto é norma, quem já tem convênio o prazo é 31/12. O que está em discussão, inclusive pela Assesspro é sobre a validade disto ou os valores cobrados.

**Comment by jetdev** [comment]
O problema que vejo é que os bancos não tem estrutura de serviços para receber boletos em tempo real, algum webservice ou algo do tipo. Praticamente todos os bancos trabalham com um gerenciador financeiro web ou desktop que não se consegue automatizar o registro. Então não podemos emitir um boleto para que ele seja pago imediatamente. 

A exigência deveria ser primeiro para a criação de uma estrutura tecnológica para suportar esse tipo de norma. Você não acha?

**Comment by carloscds** [comment]
Remessa e retorno, infelizmente!
