### ISSUE TITLE
Dúvida sobre o retorno do Banrisul

### ISSUE THREAD

**Issue by NickeManarin** [BoletoNet/boletonet#754]
Olá, eu tenho uma dúvida para quem trabalha com o Banrisul e faz a leitura do retorno gerado por eles.
(Não é bem uma dúvida ligada a esse projeto)

Em um cliente meu, ele faz a baixa e leitura dos retornos, mas nunca vem com a situação '02 - Entrada confirmada'.
Os boletos são enviados, aceitos pelo banco, mas não vem esse retorno.
Pra vocês, está vindo normal? Será que isso é alguma configuração do internet banking? (Ou talvez esteja escondida em algum outro botão?)

**Comment by carloscds** [comment]
@NickeManarin A maioria dos bancos envia o aceite, que confirma que o título esta no banco. Sugiro você entrar em contato com o banco.

**Comment by NickeManarin** [comment]
@carloscds Pois é, vou perguntar para o banco. Obrigado.
