### ISSUE TITLE
Adequação Banrisul

### ISSUE THREAD

**Issue by ericvalenzi** [BoletoNet/boletonet#761]
Bom dia @carloscds ,

Existe uma adequação necessária no Banrisul nos detalhes do CNAB400
recebi uma requisição do próprio banco para adequar segundo a nova implantação do sistemas de cobrança do Febraban
Mudanças implementadas no layout CNAB400 em 27/04/2018 para padronização do mesmo mediante funcionamento da Nova Plataforma de Cobrança – FEBRABAN

Já fiz a alteração porem não tenho permição de subir minha branch como pode ver 

$ git push origin banrisul_febraban                                              remote: Permission to BoletoNet/boletonet.git denied to ericvalenzi.             fatal: unable to access 'https://github.com/BoletoNet/boletonet.git/': The reque sted URL returned error: 403
--
portando dei um commit na master se puder analisar ou vc mesmo alterar fica no arquivo
Banco_Bansirul.cs
Linha 867

reg.CamposEDI.Add(new TCampoRegistroEDI(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0352, 018, 0, string.Empty, ' '));                              //352-369
                //reg.CamposEDI.Add(new TCampoRegistroEDI(TTiposDadoEDI.ediNumericoSemSeparador_, 0352, 004, 1, 0, '0'));                                         //352-355
                //reg.CamposEDI.Add(new TCampoRegistroEDI(TTiposDadoEDI.ediAlphaAliEsquerda_____, 0356, 001, 0, string.Empty, ' '));                              //356-356
                //reg.CamposEDI.Add(new TCampoRegistroEDI(TTiposDadoEDI.ediNumericoSemSeparador_, 0357, 013, 2, 0, '0'));                                         //357-369

**Comment by carloscds** [comment]
@ericvalenzi Você nao pode fazer commit diretamente no projeto, precisa fazer um fork, alterar e depois enviar um Pull Request.

**Comment by ericvalenzi** [comment]
@carloscds  bom dia, desculpe mas não conheço muito de Git como faço um fork, ate então só trabalhei com branches

**Comment by carloscds** [comment]
@ericvalenzi Tem um botao "Fork" no menu do GitHub, você clica e ele faz uma cópia do projeto para sua conta do GitHub. Depois você faz as alterações nesta conta. Quando enviar um push para sua conta, você pode criar um PR, que é o envio do projeto da sua conta para o projeto principal. Eu vou fazer um vídeo explicativo sobre isto e vou postar do meu blog ainda esta semana: www.carloscds.net

**Comment by ericvalenzi** [comment]
Obrigado @carloscds  vou fazer o fork e subir a alteração

**Comment by carloscds** [comment]
@ericvalenzi PR aceito! Obrigado pela contribuição!
