### ISSUE TITLE
Add tabela na área em branco do boleto sicredi

### ISSUE THREAD

**Issue by devyourcode** [BoletoNet/boletonet#774]
Bom dia, 

Gostaria de saber se é possível inserir uma tabela na área em branco do boleto sicredi. Alguém poderia nos tirar essa dúvida? 

Observação: não é dentro das instruções mas sim na parte de baixo do boleto!

Saudações, 

YourCode

**Comment by devyourcode** [comment]
Precisaria de algo assim:

[https://user-images.githubusercontent.com/29052240/53587929-6777fe00-3b6a-11e9-857c-880592d864d6.png]

**Comment by kelvindules** [comment]
@devyourcode  Seu link não é válido (não abriu aqui, pelo menos). 
É possível personalizar o layout no arquivo [Html.resx](https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net/Html.resx).

Provavelmente você irá precisar modificar essa parte:
```csharp
<data name="ReciboCedenteParte11" xml:space="preserve">
    <value>
        &lt;table class="w666"&gt;
        &lt;tr&gt;
	&lt;td class="EcdBar Al pL10"&gt;@IMAGEMCODIGOBARRA&lt;/td&gt;
	&lt;/tr&gt;
	&lt;/table&gt;
    </value>
</data>
```
Que é onde fica o código de barras.

**Comment by devyourcode** [comment]
![boleto-template](https://user-images.githubusercontent.com/29052240/55430202-e0041d00-5563-11e9-979e-c52a067cc414.jpg)

Veja se consegue ver a imagem agora.

**Comment by devyourcode** [comment]
Muito obrigado pela ajuda @kelvindules !
não é bem abaixo do código de barras que gostaria de colocar a tabela, mas sim na parte de cima.
Aguardo e obrigado novamente!
Att.,

**Comment by devyourcode** [comment]
Mas seguindo a lógica, tem que editar então o arquivo html.resx

**Comment by kelvindules** [comment]
@devyourcode  Ah, cara. Mas esse recurso de demonstrativo já existe!

Como não sei como está seu código, vou tentar exemplificar usando os dados da imagem:

```csharp

// esse é o seu boleto
var boleto = new Boleto();

// crie um grupo de demonstrativo
var meuGrupo = new GrupoDemonstrativo { Descricao = "Faturamento Atual" };

// adicione itens no grupo
var item1 = new ItemDemonstrativo { Descricao = "Leitura Anterior", Valor = 0 };
var item2 = new ItemDemonstrativo { Descricao = "Leitura Atual",    Valor = 0 };
var item3 = new ItemDemonstrativo { Descricao = "Consumo Livre" ,  Valor = 12 };
meuGrupo.Itens.Add(item1);
meuGrupo.Itens.Add(item2);
meuGrupo.Itens.Add(item3);

// adicione o grupo à lista de demonstrativos do seu boleto
boleto.Demonstrativos.Add(meuGrupo);

// crie a instancia do BoletoBancario com o seu boleto  já pronto
var boletoBancario = new BoletoBancario
{
    CodigoBanco = 123,
    Boleto = boleto,
    MostrarCodigoCarteira = false
};

// tenha certeza de setar essa propriedade = true
boletoBancario.ExibirDemonstrativo = true;

```
Claro que não vai estar **exatamente** como você mostrou na imagem, mas a lógica é a mesma. A partir disso você pode personalizar a aparência utilizando uma das formas que citei antes.

**Comment by devyourcode** [comment]
@kelvindules eu já havia testado com o demonstrativo mas ele já cria uma tabela meio que pronta já. Sabe se tem como personalizar o layout daquele demonstrativo? Veja como ficou:

![Sem título](https://user-images.githubusercontent.com/29052240/55441495-7266e980-5581-11e9-969a-16a8a990f947.png)

Tô pensando em usar o boleto.net para gerar os dados e com o itextsharp personalizar todo o boleto do jeito que preciso. Não sei se vou chegar perto daquele layout que mostrei na [foto anterior](https://user-images.githubusercontent.com/29052240/55430202-e0041d00-5563-11e9-979e-c52a067cc414.jpg).

**Comment by kelvindules** [comment]
Personalização nesse nível só alterando aquele arquivo ou o [BoletoNet.css](https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net/BoletoImpressao/BoletoNet.css) ou você montando um modelo do zero mesmo.

A ideia de manipular o PDF depois de gerado também pode chegar no resultado que você espera.

**Comment by devyourcode** [comment]
Show! Eu até já tinha começado a ir para o lado de implementar o boleto manualmente mas com os dados que o boleto.net me gera. Muito obrigado pela força @kelvindules ! grande abraço

**Comment by kelvindules** [comment]
@devyourcode se possível fecha a issue
