### ISSUE TITLE
Código de Barras - Asp.net e C#

### ISSUE THREAD

**Issue by danielmarquesvg** [BoletoNet/boletonet#81]
Olá pessoal, estou iniciando os trabalhos com o Boleto.net
adicionei a dll pelo Nuget, fiz um webform utilizando asp.net com apenas um panel para dentro dele exibir um boleto.

O boleto está sendo gerado, mas o código de barras dele não aparece, no lugar dele aparece apenas uma string que possui a frase "Código de Barras" e abaixo dela a linha pontilhada do boleto. Andei lendo alguns comentários do projeto no https://boletonet.codeplex.com/, mas nenhum deles veio a resolver este pequeno problema.

Quanto ao boleto que estou usando, é um exemplo de boleto da Caixa Econômica Federal. Alguém poderia me ajudar a resolver a exibição do código de barras neste exemplo de boleto? Segue o código abaixo.

```c#

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using BoletoNet;

namespace BoletoCAIXA
{
    public partial class WebFormBoleto : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            BoletoBancario boletoBancario = new BoletoBancario();
            boletoBancario.CodigoBanco = (short)104;

            DateTime vencimento = new DateTime(2008, 12, 20);

            Cedente c = new Cedente("000.000.000-00", "Boleto.net ILTDA", "1234", "12345678", "9");

            c.Codigo = "112233";


            BoletoNet.Boleto b = new BoletoNet.Boleto(vencimento, 20.00m, "14", "0123456789", c);

            b.Sacado = new Sacado("000.000.000-00", "Nome do seu Cliente ");
            b.Sacado.Endereco.End = "Endereço do seu Cliente ";
            b.Sacado.Endereco.Bairro = "Bairro";
            b.Sacado.Endereco.Cidade = "Cidade";
            b.Sacado.Endereco.CEP = "00000000";
            b.Sacado.Endereco.UF = "UF";

            //Adiciona as instruções ao boleto
            #region Instruções
            Instrucao_Caixa item;
            //ImportanciaporDiaDesconto
            item = new Instrucao_Caixa((int)EnumInstrucoes_Caixa.Multa, Convert.ToDecimal(0.40));
            b.Instrucoes.Add(item);
            item = new Instrucao_Caixa((int)EnumInstrucoes_Caixa.JurosdeMora, Convert.ToDecimal(0.01));
            b.Instrucoes.Add(item);
            item = new Instrucao_Caixa((int)EnumInstrucoes_Caixa.NaoReceberAposNDias, 90);
            b.Instrucoes.Add(item);
            #endregion Instruções

            EspecieDocumento_Caixa espDocCaixa = new EspecieDocumento_Caixa();
            b.EspecieDocumento = new EspecieDocumento_Caixa(espDocCaixa.getCodigoEspecieByEnum(EnumEspecieDocumento_Caixa.DuplicataMercantil));
            b.NumeroDocumento = "00001";
            b.DataProcessamento = DateTime.Now;
            b.DataDocumento = DateTime.Now;

            boletoBancario.Boleto = b;
            boletoBancario.GeraImagemCodigoBarras(b);
            
            boletoBancario.MostrarComprovanteEntrega = true;
            boletoBancario.Boleto.Valida();
            //boletoBancario.MontaHtmlEmbedded();
            //boletoBancario.MontaHtml();
            //boletoBancario.GeraImagemCodigoBarras(b);
            Panel1.Controls.Add(boletoBancario);
      
        }
    }
}

```

**Comment by danielmarquesvg** [comment]
Esta é uma imagem recortada do firefox, o único problema é apenas o código de barras

![imagemboleto](https://cloud.githubusercontent.com/assets/6758578/9925447/081e2728-5ce2-11e5-9203-f78e418dbd94.png)

**Comment by danielmaia-rj** [comment]
Você chegou a adicionar essas configurações no seu web.config?

<system.webServer>
    <validation validateIntegratedModeConfiguration="false"/>
    <handlers>
      <remove name="ImagemCodigoBarra"/>
      <add name="ImagemCodigoBarra" verb="GET" path="ImagemCodigoBarra.ashx" type="BoletoNet.ImagemCodigoBarraHandler"/>
    </handlers>

**Comment by danielmarquesvg** [comment]
Olá danielmaia-rj

Consegui resolver o problema com a seguinte solução:

1 Criei o arquivo ImagemCodigoBarra.ashx com o seguinte código
``` html
<%@ WebHandler Language="C#" Class="BoletoNet.ImagemCodigoBarraHandler" %>
```

2 Adicionei o arquivo ImagemCodigoBarra.ashx na pasta onde estavam os formulários aspx

3 No arquivo Web.Debug.xml adicionei o seguinte trecho de código
``` xml
<system.webServer>
    <handlers>
      <add name="ImagemCodigoBarras" verb="*" path="ImagemCodigoBarra.ashx" type="BoletoNet.ImagemCodigoBarraHandler"/>
    </handlers>
</system.webServer>
```

Por fim o código de barras apareceu

**Comment by carlezzo** [comment]
Ola Daniel estou com o mesmo problema e quando tento usar oque vc descreveu a cima da esta mensagem. Diretiva 'webhandler' é desconhecida.

**Comment by allanmenezes** [comment]
A solução do danielmarquesvg funcionou pra mim tb.  Abraços

**Comment by ArrowtechTI** [comment]
Estava com o mesmo problema
A solução do danielmarquesvg funcionou pra mim tb.   👍

**Comment by chroma2000** [comment]
Eu nao estou conseguindo, alguém poderia me ajudar, eu uso a Dll que instalei pelo nuget no Visual Studio

**Comment by ArrowtechTI** [comment]
Oi Chroma2000 !
Posta aí seu problema.

**Comment by chroma2000** [comment]
Boa tarde ArrowTech, agradeço o retorno, eu vi que falta colocar o arquivo arquivo ImagemCodigoBarra.ashx, agora ele está gerando o código e surgiu um novo problema, quando mando ler no Itaú ele diz que a linha digitavel precisa ter 44 carácteres. a linha digitavel passada é essa: 34191090088866912293483999180009582560000049800. Ela ler na digitação mas nao no codbarras.

**Comment by ArrowtechTI** [comment]
Olá Chroma2000 !
   Eu tive um problema parecido, dá uma olhada nos campos NOSSO NUMERO (passe 12 caracteres) e NUMERO DO DOCUMENTO (passe 15 caracteres), e deixe que o BoletoNet crie os respectivos digitos.

**Comment by ArrowtechTI** [comment]
Olá Chroma, Após olhar meu códgio, vi que coloquei uma informação equivocada, a DLL do BoletoNet precisa sim calcular o digito verificador (tenho a rotina aqui se precisar) o webservice do Santander que não, desculpe pela má informação. Segue meu e-mail:  arrowtech.ti@gmail.com
