### ISSUE TITLE
Dúvida sobre o layout

### ISSUE THREAD

**Issue by CPrimbee** [BoletoNet/boletonet#816]
Preciso fazer uma, pequena, alteração no layout do boleto carne. Não encontrei na Wiki nada que me ajude nesta questão. Como devo proceder neste caso?

**Comment by carloscds** [comment]
@CPrimbee Você pode mudar o código e depois enviar um PR.

**Comment by CPrimbee** [comment]
> @CPrimbee Você pode mudar o código e depois enviar um PR.

@carloscds A minha dúvida é justamente em qual arquivo eu devo mexer. Se puder me dar uma luz? rsrs

**Comment by carloscds** [comment]
@CPrimbee O carné está aqui: https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net/Html.resx

**Comment by CPrimbee** [comment]
@carloscds Muito Obrigado!
