### ISSUE TITLE
Boleto com comprovante de entrega 

### ISSUE THREAD

**Issue by WPIta** [BoletoNet/boletonet#827]
Não sei o que acontece mas quando faço o boleto ele fica desposicionado, em pdf e html, como não sei quase nada de C# pode ser algum erro meu, alguém tem uma ideia do que possa estar acontecendo. Ou é assim mesmo.

![comprovante](https://user-images.githubusercontent.com/40769809/71545100-d4644c00-2965-11ea-889b-4cdc3a53e864.png)

**Comment by carloscds** [comment]
@WPIta Da uma olhada nas margens da sua impressora no Windows.

**Comment by WPIta** [comment]
Obrigado por responder, as margens estão no default do Windows.

**Comment by carloscds** [comment]
@WPIta Você ja tentou modificar as margens?

**Comment by WPIta** [comment]
Desculpe mas não estou conseguindo ver a relação da visualização em uma página web com a impressora, eu não fiz nenhum alteração de margens. A impressora esta configurada para A4.

![image](https://user-images.githubusercontent.com/40769809/71822934-eab08d00-3074-11ea-8e80-cfa927bf7d5d.png)

**Comment by carloscds** [comment]
@WPIta A sua primeira imagem é de um browser ou da impressao ?

**Comment by WPIta** [comment]
Não esses são os arquivos gerados pelo Boleto.Net veja com estão saindo.

[Banco341Html.zip](https://github.com/BoletoNet/boletonet/files/4026652/Banco341Html.zip)


[Boletos2_341.pdf](https://github.com/BoletoNet/boletonet/files/4026601/Boletos2_341.pdf)
[Boletos1_341.pdf](https://github.com/BoletoNet/boletonet/files/4026602/Boletos1_341.pdf)

**Comment by carloscds** [comment]
@WPIta O CSS do Boleto esta incorreto, você esta usando a versao do Nuget ?

**Comment by WPIta** [comment]
Sim estou usando a dll do projeto Nuget.

**Comment by carloscds** [comment]
@WPIta Me manda um exemplo do codigo que vc esta fazendo para gerar o boleto.

**Comment by WPIta** [comment]
Então eu não uso c# eu uso Visual Cobol e acesso as class da DLL

**Comment by carloscds** [comment]
@WPIta Acertei o problema no componente, Estou gerando uma nova versao.

**Comment by WPIta** [comment]
Valeu pela disposição e paciência

**Comment by carloscds** [comment]
@WPIta Assim que você testar e estiver ok, pode fechar esta issue.

**Comment by WPIta** [comment]
Bom dia, onde esta o logo do banco ficou na posição mas as linhas Local de pagamento e beneficiário não.

[Boletos1_237.pdf](https://github.com/BoletoNet/boletonet/files/4040742/Boletos1_237.pdf)
[boleto.zip](https://github.com/BoletoNet/boletonet/files/4040739/boleto.zip)

Só testei com Bradesco.

**Comment by carloscds** [comment]
@WPIta Corrigido, erro de CSS. Vou publicar uma nova versao.

**Comment by WPIta** [comment]
Você vai atualizar o Nuget também?

**Comment by carloscds** [comment]
@WPIta JA atualizou! :-)

**Comment by WPIta** [comment]
carloscds, testei com Itaú e Bradesco ficou perfeito muito obrigado pela ajuda!

**Comment by carloscds** [comment]
Excelente, vou fechar a issue!
