### ISSUE TITLE
Conta Cedente

### ISSUE THREAD

**Issue by WPIta** [BoletoNet/boletonet#831]
Estou tentando fazer os boletos, mas esbarrei em um problema na formatação da conta do cedente 

Banco.cs linha 282
C3 = string.Format("{0}{1}.{2}{3}{4}", F, GGGGGG.Substring(0, 4), GGGGGG.Substring(4, 2), HHH, Z);

Utilizando banco Itaú aqui quando a conta tiver 4 dígitos não esta fazendo. Aborta o processo.
Eu preciso completar com pelo menos 5 dígitos ou esta com um bug mesmo.

**Comment by carloscds** [comment]
@WPIta Até onde eu sei esta funcionando corretamente!

**Comment by WPIta** [comment]
Em meus testes se eu coloco uma conta Banco Itaú com 4 dígitos (conta 1597) ele acusa o erro se coloco com 5 dígitos (01597) passa na boa.

**Comment by carloscds** [comment]
@WPIta Mas funciona com 5?

**Comment by WPIta** [comment]
Sim com 5 dígitos funciona eu fiquei em dúvida se ele gera corretamento a linha digitável.

**Comment by WPIta** [comment]
Encontrei no manual do banco que o tamanho mínimo/máximo é de 9(05) numérico de 5 posições então estou fazendo meu programa ver e enviar com tamanho correto se for menor.
