### ISSUE TITLE
Recibo do Sacado - Demonstrativo

### ISSUE THREAD

**Issue by WPIta** [BoletoNet/boletonet#836]
Preciso fazer com que o demonstrativo fique com o mesmo tamanho para todos os boletos, mas estou esbarrando nesse "problema", tenho que imprimir linhas em branco e sempre aparece R$0,00, não sei muito de C# então qualquer ajuda será bem vinda.

![image](https://user-images.githubusercontent.com/40769809/73976181-864c4c00-4906-11ea-807c-4f9682c92c16.png)

**Comment by carloscds** [comment]
@WPIta Tem que tratar isto no fonte

**Comment by WPIta** [comment]
É como já comentei em outro issue não manjo muito de C# andei fuçando mas não sei onde devo fazer a alteração se puder indicar, obrigado!

**Comment by WPIta** [comment]
Vou fechar o issue, consegui fazer
