### ISSUE TITLE
Carteira 24(SR) - Caixa

### ISSUE THREAD

**Issue by vmachadot** [BoletoNet/boletonet#85]
Caros, ao gerar um boleto da Caixa com a carteira "24", o boleto que aparece está com o DV do beneficiário errado. Verificando a função ValidaBoleto() da classe Banco_Caixa, a validação da carteira é com o "SR" e, como está diferente, ele calcula o DV com a função Mod10() ao invés da Mod11Base9().

Porém, ao informar a carteira como "SR", a dll me retorna o seguinte erro:
"O índice e o comprimento devem se referir a um local dentro da cadeia de caracteres.
Nome do parâmetro: length"

Alguém tem um sugestão ou teve um problema parecido?

**Comment by danielmarquesvg** [comment]
@vmachadot , passei por esse problema, mas a solução é simples. Preencha os valores de acordo com padrão da caixa.

Link do padrão da caixa:
http://www.caixa.gov.br/downloads/cobranca-caixa-manuais/ESP_COD_BARRAS_SIGCB_COBRANCA_CAIXA.pdf

__Datas__
preencha as datas de vencimento, do documento e de processamento

__Cedente e Boleto__

```C#

Cedente cedente = new Cedente("11.111.111/0001-11", "Nome do Cedente", "1111", "1111", "1");
cedente.Codigo = "111111";
Boleto boleto = new Boleto(dataDeVencimento, 5.00m, "SR", "24000000000000001", cedente);
```

E nem todos os números podem ser gerados aleatoriamente, cuidado nisso também

**Comment by vmachadot** [comment]
@danielmarquesvg, com o seu exemplo eu acabei achando a solução  :+1: 

O tamanho do Nosso Número estava com valor 10 e no exemplo que você me mandou o tamanho era 17. Eu alterei e funcionou.

Muito obrigado pela ajuda.
