### ISSUE TITLE
Conciliação bancaria

### ISSUE THREAD

**Issue by LeonardoCarneiroArruda** [BoletoNet/boletonet#881]
Olá a todos.

Gostaria de saber se existe algo a respeito de importação de conciliação bancaria fluxo de importação.
Obs.: Essa importação seria o retorno do extrato bancário enviado no formato CNAB240 para importação no sistema.

Já viram algo assim aqui na dll?

Grato

**Comment by carloscds** [comment]
@LeonardoCarneiroArruda No BoletoNet nao. Ja vi vários projetos deste tipo no Github, mas a maioria esta parada ha muito tempo.

**Comment by LeonardoCarneiroArruda** [comment]
Você poderia me indicar algum funcional e mais recente? Por favor, estou necessitando.

**Comment by LeonardoCarneiroArruda** [comment]
@carloscds

**Comment by carloscds** [comment]
@LeonardoCarneiroArruda Nao conheço os projetos, so fiz uma busca no GH.
O que encontrei: 
https://github.com/search?q=conciliacao
https://github.com/leonardonhesi/GF-Home
