### ISSUE TITLE
NOVA VERSAO NUGET

### ISSUE THREAD

**Issue by drlimajr** [BoletoNet/boletonet#893]
Fala equipe beleza? Será que vcs conseguem subir o nuget do Boleto.Net (master) para podermos disponibilizar as alterações realizadas? Valeu

**Comment by carloscds** [comment]
@drlimajr Subindo agora, deve estar no ar em alguns minutos.

**Comment by drlimajr** [comment]
@carloscds Recebido! Obrigado =)
