### ISSUE TITLE
Alteração de dados do boleto Itaú

### ISSUE THREAD

**Issue by diegodariolli** [BoletoNet/boletonet#894]
Alguém já enviou na remessa, boletos para alteração de dados (especificamente o valor do boleto).
Se já, como foi preenchido? normalmente, somente alterando o código da ocorrência ou somente com os dados necessários?
Fiz uma alteração na biblioteca na qual eu passo somente os dados necessários para validar o arquivo, mas não sei se está certo pois o ambiente de teste do itaú não devolve o arquivo retorno.

**Comment by carloscds** [comment]
@diegodariolli Eu nunca fiz envio de alteracao de titulo, pois na maioria das vezes o cliente acha mais rapido fazer direto no sistema do banco.

**Comment by diegodariolli** [comment]
Certo, fica assim então
