### ISSUE TITLE
Notificar no codeplex que o projeto foi movido para o github

### ISSUE THREAD

**Issue by AlbertoMonteiro** [BoletoNet/boletonet#9]
Existe alguma possibilidade disso?

**Comment by carloscds** [comment]
Já coloquei a mensagem lá @AlbertoMonteiro Obrigado!

**Comment by AlbertoMonteiro** [comment]
Prazer foi meu 😎
Close #9

Enviado pelo meu Windows Phone
________________________________
De: Carlos dos Santos<mailto:notifications@github.com>
Enviada em: ‎31/‎03/‎2015 16:44
Para: BoletoNet/boletonet<mailto:boletonet@noreply.github.com>
Cc: Alberto Monteiro<mailto:alberto.monteiro@live.com>
Assunto: Re: [boletonet] Notificar no codeplex que o projeto foi movido para o github (#9)

Já coloquei a mensagem lá @AlbertoMonteiro Obrigado!

---
