### ISSUE TITLE
Boleto.Net no Gvinci 

### ISSUE THREAD

**Issue by digsistemas** [BoletoNet/boletonet#91]
Olá a todos!

Agradeço a ajuda recebida e encaminho um post com um projeto de exemplo de utilização do Boleto.Net com o Gvinci (gerador de códigos para aplicações web):

http://forum.ssitecnologia.com.br/viewtopic.php?f=6&t=2246&sid=fe306897323c61185f49f33554a3eb85

http://gvinci.com.br/Home

Heric Souza
DigSistemas

**Comment by carloscds** [comment]
@digsistemas Obrigado pelo exemplo.
