### ISSUE TITLE
GERAR BOLETO EM PDF, AO INVES DE IMAGEM

### ISSUE THREAD

**Issue by PedroCanizela** [BoletoNet/boletonet#916]
Olá, sou novo por aqui no Boleto.Net, gostaria de saber como gerar o boleto em PDF ao invés de imagem, tentei o chamar a classe Boleto Bancario, metodo MontaBytesPDF, mas não consegui.. 

Obrigado

**Comment by carloscds** [comment]
@PedroCanizela O metodo devolve um array de bytes que você pode salvar como um PDF ou retornar em uma aplicacao web.

**Comment by PedroCanizela** [comment]
Olá, obrigado
Consegui
