### ISSUE TITLE
Imprimir Boleto ReportViewer RDLC

### ISSUE THREAD

**Issue by PedroCanizela** [BoletoNet/boletonet#923]
Ola, tudo bem?

Gostaria de saber se posso usar a Dll para gerar o boleto, remessa e ler o retorno.. porém quando for imprimir os boletos puxar do banco de dados para um relatório no rldc, ao invés de gerar pelo método do boleto.net.

Teria algum problema com a autenticidade do boleto ou seguindo o layout e gerando o código de barras, não tem problema?

E gostaria de saber se posso colocar no boleto um cabeçalho com as informações da empresa, logo, etc. antes do recibo do pagador.

Obrigado

**Comment by carloscds** [comment]
@PedroCanizela Nao entendi bem a sua dúvida, quando a logo, dê uma olhada nos exemplos.

**Comment by PedroCanizela** [comment]
> @PedroCanizela Nao entendi bem a sua dúvida, quando a logo, dê uma olhada nos exemplos.

Tá joia

Obrigado
