### ISSUE TITLE
Leitura da remessa gerada

### ISSUE THREAD

**Issue by fischer7** [BoletoNet/boletonet#937]
Olá, é possível com este sistema ler remessas após a sua geração para extração de informações?
Preciso criar um leitor de arquivos REM para extração de valores de títulos.
Grato.

**Comment by carloscds** [comment]
@fischer7 Ler remessa é uma das funcionalidades do projeto.

**Comment by fischer7** [comment]
Nom dia @carloscds grato pelo retorno, a pergunta é pertinente,

Ler a remessa, como se eu fosse o banco!
Processo inverso ao comum.
Grato.

**Comment by carloscds** [comment]
@fischer7 Isto infelizmente o componente nao faz.

**Comment by ivanteles** [comment]
@fischer7 Veja só.. Pra você ler a remessa do banco, basta você tá de posse a documentação de como o banco sugere a criação da remessa.
ou seja, ele delimita como as remessa devem ser geradas pra que ele consiga ler.
Se vc souber como a remessa deve ser gerada você vai conseguir ler conforme as posições que ele sugere!
Não seria isso?
Da mesma forma que lemos os retornos baseado na documentação!

**Comment by carloscds** [comment]
@fischer7 Para remessa nao.
