### ISSUE TITLE
Aumentar tamanho com Campo de Instruções no Boleto em PDF

### ISSUE THREAD

**Issue by D13G0M1R4ND4** [BoletoNet/boletonet#942]
Boa tarde, tudo bem com vocês?

Algum de vocês poderia me dizer como faço pra aumentar esse campo de instruções marcado em vermelho para que as instruções apareçam iguais ao campo da parte de cima de boleto, sem cortes?

Já dei uma boa olhada no código e não tive sucesso em encontrar o local que posso alterar pra aumentar esse campo.

Desde já muito obrigado a todos!

![Boleto](https://user-images.githubusercontent.com/65674322/172242625-e5365ec2-8c3b-4547-9f91-ea7c7f7d9537.jpeg)

**Comment by carloscds** [comment]
@D13G0M1R4ND4 Isto esta em um HTML, mas tem um padrão de tamanho e a CEF é bem rigida nisto. O HTML esta aqui: https://github.com/BoletoNet/boletonet/blob/master/src/Boleto.Net/Html.resx
