### ISSUE TITLE
Erro durante a geração do registro HEADER do arquivo de REMESSA. Santander.

### ISSUE THREAD

**Issue by renydev** [BoletoNet/boletonet#970]
Bom dia.

Eu quero usar o BoletoNet para meu projeto .NET Core 3.0 mas estou com alguns problemas e algumas dúvidas.

Eu fiz as configurações para Itaú e Bradesco e os arquivos são gerados. Eu ainda não mandei pro banco para ter certeza se funcionam, mas de qualquer forma estão sendo gerados.

O Santander está gerando o erro: ```Erro durante a geração do registro HEADER do arquivo de REMESSA```
Com um inner exception ```Unable to cast object of type 'BoletoNetCore.BancoSantander' to type 'BoletoNetCore.IBancoCNAB400'```

O problema é que o bradesco e itaú funcionam mas o Santander não... Na verdade se eu mudar pra CNAB150 o Santander não dá erro.

Eu uso Resharper no Visual Studio pra tentar debugar a biblioteca junto com o 'Decompiler' mas mesmo assim eu não consegui entender como resolver o erro.

Eu queria uma ajuda pra conseguir compilar e testar o código, eu estou com o projeto clonado na minha máquina mas eu não sei como eu posso testar com as minhas entradas.

Alguém consegue me ajudar com isso? Eu não manjo de classes de testes então nem sei como debugar as classes de teste.

**Comment by renydev** [comment]
Eu estou usando sim!
BoletoNetCore (3.0.1.290)
BoletoNetCore.PDF (3.0.0)

Você quer dizer rodar ele? Se sim, eu rodo o projeto, configuro tudo em uma tela e aí eu consigo debugar certinho?

**Comment by carloscds** [comment]
@renydev Se você quer debugar, melhor baixar o codigo.

**Comment by renydev** [comment]
Então @carloscds , eu baixei (clonei do github) e estou mexendo, mas no projeto o que é executável é o projeto de testes. O projeto BoletoNetCore fala que a propriedade RunCommand não está definida. Então só dá pra rodar os testes mesmo?

**Comment by carloscds** [comment]
@carloscds O projeto não é o de testes, é o Boleto.Net

**Comment by renydev** [comment]
@carloscds acho que entendi o erro. Não há modelo CNAB400 cadastrado para o santander no projeto .net core... precisa adicionar... eu ainda não entendi como que eu faço pra ajudar... mas basta adicionar a classe CNAB400 que acho que funciona.
