### ISSUE TITLE
Data de Juros no Banco do Brasil

### ISSUE THREAD

**Issue by vitorlmello** [BoletoNet/boletonet#976]
Banco solicitou que fosse enviado uma data de juros sendo o vencimento +1 (Na configuração estou colocando para o cliente poder informar o dia). Entretanto no código o Banco do brasil pega a data do vencimento.

![image](https://github.com/BoletoNet/boletonet/assets/84418821/79129f94-3b5b-4033-bdad-7dcacd976a91)

**Comment by carloscds** [comment]
@vitorlmello Este procedimento esta descrito no layout do banco ?

**Comment by vitorlmello** [comment]
Está descrito Data de juros

![image](https://github.com/BoletoNet/boletonet/assets/84418821/79824c30-cbcd-46a4-a452-5607b54d3c26)

Nada diz que a Data de Juros deve ser igual a Data de Vencimento.
Eu já tenho a solução pronta, só preciso da permissão para subir a PR

**Comment by carloscds** [comment]
@vitorlmello qual sua solucao ?

**Comment by vitorlmello** [comment]
![image](https://github.com/BoletoNet/boletonet/assets/84418821/0a9354f5-c9a2-4d68-84eb-a2708aa41c52)

Primeiro buscar do campo DataJurosMora, e caso não tenha, pegar da data de Vencimento.
Assim quem já utiliza hoje não terá problema se atualizar o projeto, e quem precisar passar uma data diferente da de vencimento tem a opção.

**Comment by carloscds** [comment]
ok, manda o PR
