### ISSUE TITLE
Derrubando Aplicação ao gerar Boleto

### ISSUE THREAD

**Issue by eduardohg** [BoletoNet/boletonet#994]
Bom dia,
Gostaria de saber se é possível alterar o output path da geração do boleto. 
Aparentemente quando o pdf é gerado, ele é gerado na pasta bin. 
Quando o IIS detecta qualquer mudança nessa pasta ele recarrega tudo, derruba sessão, chama applicaton_end e etc. 
Em resumo, toda vez que eu gero um pdf do boleto o IIS derruba a sessão de todos e recarrega tudo.

_Originally posted by @diegohunter in https://github.com/BoletoNet/boletonet/issues/165#issuecomment-302707346_

Pessoal, estou com um problema parecido, após chamar a função MontaBytesPDF por algum motivo está derrubando a aplicação. chamando Application_End. Não sei qual o motivo

**Comment by carloscds** [comment]
@eduardohg Alguma mensagem de Erro? Se for somente na geracao do PDF, você pode tentar um outro componente para isto: https://www.nuget.org/packages/HtmlToPDFCore

**Comment by eduardohg** [comment]
@carloscds consegui resolver fazendo o código assíncrono usando Tasks
