### ISSUE TITLE
Nosso numero

### ISSUE THREAD

**Issue by PedroCanizela** [BoletoNet/boletonet#996]
Oi bom dia, gostaria de saber qual metodo gera o nosso numero e o que faço pra gerar se preciso informar algum codigo antes, se somente o numero do documento da certo

**Comment by carloscds** [comment]
@PedroCanizela Você pode chamr o metodo: banco.FormataNossoNumero(boleto);

**Comment by PedroCanizela** [comment]
Ola eu tentei chamar o metodo porem ele retorna o seguinte nosso numero 002/-  no itau também tentei da mesma forma retornou igual

segue também meu codigo

Banco banco = new Banco(237);

bb = new BoletoBancario();
bb.CodigoBanco = 237;

DateTime vencimento = DateTime.Now.AddDays(10);
Instrucao_Bradesco item = new Instrucao_Bradesco(9, 5);

Cedente c = new Cedente("19.800.982/0001-24", "Empresa de Atacado", "1234", "5", "123456", "7");
c.Codigo = "13000";
c.DigCedente = "8";
c.Convenio = 011212312312311313;

Endereco end = new Endereco();
end.Bairro = "Lago Sul";
end.CEP = "71666660";
end.Cidade = "Brasília- DF";
end.Complemento = "Quadra XX Conjunto XX Casa XX";
end.End = "Condominio de Brasilia - Quadra XX Conjunto XX Casa XX";
end.Numero = "55";
end.UF = "DF";

Boleto b = new Boleto(vencimento, 1.01m, "02", "", c);
b.NumeroDocumento = "01000000001";

b.Sacado = new Sacado("79.520.758/0001-00", "Eduardo Frare");
b.Sacado.Endereco = end;

item.Descricao += " após " + item.QuantidadeDias.ToString() + " dias corridos do vencimento.";
b.Instrucoes.Add(item); //"Não Receber após o vencimento");

banco.FormataNossoNumero(b);

bb.Boleto = b;
bb.Boleto.Valida();

boletos.Add(bb);

**Comment by carloscds** [comment]
@PedroCanizela O nosso numero é uma sequencia, você precisa informar o numero e o BoletoNet irá formatá-lo.

**Comment by PedroCanizela** [comment]
vc saberia dizer onde encontro a forma de criar essa sequencia? de como ela é formada 
vou dar uma olhada nos testes

**Comment by carloscds** [comment]
@PedroCanizela é um numero inteiro, você precisa controlar isto no seu software e a cada boleto ir incrementando.

**Comment by PedroCanizela** [comment]
> @PedroCanizela muito obrigado

**Comment by PedroCanizela** [comment]
@carloscds  muito obrigado, só uma duvida pra todos os bancos seria da mesma forma?

**Comment by carloscds** [comment]
@PedroCanizela Sim, em todos você precisa controlar o numero.

**Comment by PedroCanizela** [comment]
@carloscds  muito obrigado
